In [1]:
from utils import prepare_dataframe, merge_csv_files_in_directory, filterForEqualLabelCount,filterRepoName

embedding_directory = 'embeddings/GCB_Pooler_embeddings_content_before_only_apache_balanced_46008'
model_directory = 'models/GCB_Pooler_embeddings_content_before_only_apache_balanced_46008.pth'
column = "content_before"
columns_to_keep = [ column]

#merge_csv_files_in_directory()
df = prepare_dataframe("merged.csv", shouldBalance=False, should_merge_csv=False, columns_to_keep=columns_to_keep) 
df = filterRepoName(df,"apache")
df = filterForEqualLabelCount(df=df)
resulting_label_count = df['labels'].nunique()
df

labels
enhancement    37586
bug            32864
clean          17263
performance     5392
refactor        4596
Name: count, dtype: int64
labels
enhancement    37586
bug            32864
clean          17263
Name: count, dtype: int64
15336

,full_repo_name,labels,content_before,index
90648,apache/rocketmq,enhancement,/*\n * Licensed to the Apache Software Foundat...,90648
85016,apache/pinot,enhancement,/**\n * Licensed to the Apache Software Founda...,85016
52956,apache/maven-dependency-plugin,enhancement,/*\n * Licensed to the Apache Software Foundat...,52956
43844,apache/cloudstack,enhancement,// Licensed to the Apache Software Foundation ...,43844
93757,apache/accumulo,enhancement,/*\n * Licensed to the Apache Software Foundat...,93757
...,...,...,...,...
63863,apache/pulsar,clean,/*\n * Licensed to the Apache Software Foundat...,63863
71156,apache/netbeans,clean,/*\n * Licensed to the Apache Software Foundat...,71156
78185,apache/netbeans,clean,/*\n * Licensed to the Apache Software Foundat...,78185
42537,apache/cloudstack,clean,// Licensed to the Apache Software Foundation ...,42537
83887,apache/pinot,clean,/**\n * Licensed to the Apache Software Founda...,83887

In [2]:
import pandas as pd
import torch


# One-hot encoding ile labels sütununu dönüştürme
df_encoded_labels = pd.get_dummies(df, columns=['labels'])
df_encoded_repo = pd.get_dummies(df, columns=['full_repo_name'])

# Özellikler ve etiketler
X_repo = df_encoded_repo.drop(columns=['labels',column,'index'])
X_repo = X_repo.astype(int)

# y = df_encoded.drop(columns=['content_before', 'content_after', 'tokens'])
y = df_encoded_labels.drop(columns=[column, 'full_repo_name','index'])123

y = y.astype(int) # convert it 0,1     instead of true, false 

df['label_tensor'] =[torch.tensor(row,dtype=torch.float32) for row in y.values] 
df['repo_name_tensor'] =[torch.tensor(row,dtype=torch.float32) for row in X_repo.values] 

df = df.drop(columns=['full_repo_name', 'labels',column])


#print(df['label_tensor'][0] )
#print(df['repo_name_tensor'][0] )
df

,index,label_tensor,repo_name_tensor
90648,90648,"[tensor(0.), tensor(0.), tensor(1.)]","[tensor(0.), tensor(0.), tensor(0.), tensor(0...."
85016,85016,"[tensor(0.), tensor(0.), tensor(1.)]","[tensor(0.), tensor(0.), tensor(0.), tensor(0...."
52956,52956,"[tensor(0.), tensor(0.), tensor(1.)]","[tensor(0.), tensor(0.), tensor(0.), tensor(0...."
43844,43844,"[tensor(0.), tensor(0.), tensor(1.)]","[tensor(0.), tensor(0.), tensor(0.), tensor(0...."
93757,93757,"[tensor(0.), tensor(0.), tensor(1.)]","[tensor(1.), tensor(0.), tensor(0.), tensor(0...."
...,...,...,...
63863,63863,"[tensor(0.), tensor(1.), tensor(0.)]","[tensor(0.), tensor(0.), tensor(0.), tensor(0...."
71156,71156,"[tensor(0.), tensor(1.), tensor(0.)]","[tensor(0.), tensor(0.), tensor(0.), tensor(0...."
78185,78185,"[tensor(0.), tensor(1.), tensor(0.)]","[tensor(0.), tensor(0.), tensor(0.), tensor(0...."
42537,42537,"[tensor(0.), tensor(1.), tensor(0.)]","[tensor(0.), tensor(0.), tensor(0.), tensor(0...."
83887,83887,"[tensor(0.), tensor(1.), tensor(0.)]","[tensor(0.), tensor(0.), tensor(0.), tensor(0...."

In [3]:
from utils import load_embeddings_from_directory_for_df
import pandas as pd

df = load_embeddings_from_directory_for_df(directory_path=embedding_directory,df=df)

  0%|          | 0/46008 [00:00<?, ?it/s]

In [4]:
from sklearn.model_selection import train_test_split

X_index = df[['index']]  
# Split the code data into test, train and validation sets
X_index_train, X_index_test = train_test_split(X_index, test_size=0.3, random_state=42) #random_state: 0,3074,42
X_index_test, X_index_val = train_test_split(X_index_test, test_size=0.5, random_state=42)

In [5]:
import gc
import torch

df_train = df[df['index'].isin(X_index_train['index'].values)].reset_index(drop=True)
df_val = df[df['index'].isin(X_index_val['index'].values)].reset_index(drop=True)
df_test = df[df['index'].isin(X_index_test['index'].values)].reset_index(drop=True)

torch.cuda.empty_cache()

df_train

,index,label_tensor,repo_name_tensor,embedding
0,52956,"[tensor(0.), tensor(0.), tensor(1.)]","[tensor(0.), tensor(0.), tensor(0.), tensor(0....","[tensor(-0.2708), tensor(-0.0817), tensor(-0.2..."
1,43844,"[tensor(0.), tensor(0.), tensor(1.)]","[tensor(0.), tensor(0.), tensor(0.), tensor(0....","[tensor(-0.3480), tensor(-0.0658), tensor(-0.1..."
2,90569,"[tensor(0.), tensor(0.), tensor(1.)]","[tensor(0.), tensor(0.), tensor(0.), tensor(0....","[tensor(-0.3614), tensor(-0.0802), tensor(-0.0..."
3,59460,"[tensor(0.), tensor(0.), tensor(1.)]","[tensor(0.), tensor(0.), tensor(0.), tensor(0....","[tensor(-0.3303), tensor(-0.0807), tensor(-0.1..."
4,91168,"[tensor(0.), tensor(0.), tensor(1.)]","[tensor(0.), tensor(0.), tensor(0.), tensor(0....","[tensor(-0.3223), tensor(-0.0390), tensor(-0.1..."
...,...,...,...,...
32200,76968,"[tensor(0.), tensor(1.), tensor(0.)]","[tensor(0.), tensor(0.), tensor(0.), tensor(0....","[tensor(-0.1110), tensor(-0.1491), tensor(-0.1..."
32201,63863,"[tensor(0.), tensor(1.), tensor(0.)]","[tensor(0.), tensor(0.), tensor(0.), tensor(0....","[tensor(-0.2979), tensor(-0.1422), tensor(-0.0..."
32202,78185,"[tensor(0.), tensor(1.), tensor(0.)]","[tensor(0.), tensor(0.), tensor(0.), tensor(0....","[tensor(-0.2940), tensor(-0.0417), tensor(-0.0..."
32203,42537,"[tensor(0.), tensor(1.), tensor(0.)]","[tensor(0.), tensor(0.), tensor(0.), tensor(0....","[tensor(-0.3618), tensor(-0.0180), tensor(-0.2..."
32204,83887,"[tensor(0.), tensor(1.), tensor(0.)]","[tensor(0.), tensor(0.), tensor(0.), tensor(0....","[tensor(-0.2818), tensor(-0.0726), tensor(-0.0..."

In [6]:
from torch.utils.data import DataLoader, Dataset
from utils import load_embedding_from_directory

# Custom Dataset Class to handle the dataframe
class CodeDataset(Dataset):
    def __init__(self, df):
        self.df = df
        self.id_list = df['index'].values 

    def __len__(self):
        return len(self.df)
    
    def __getitem__(self, idx):
    
        index = self.id_list[idx]  

        tensor_3d = self.df.loc[self.df['index'] == index, 'embedding'].iloc[0]
        repo_name_tensor = self.df.loc[self.df['index'] == index, 'repo_name_tensor'].iloc[0]
        label_tensor = self.df.loc[self.df['index'] == index, 'label_tensor'].iloc[0]
        
        #print(f"{repo_name_tensor.shape} {tensor_3d.shape} {label_tensor.shape}")
        #print("-------------------------------")
        
        #Flattening
        #embedding = torch.flatten(tensor_3d)
        embedding = tensor_3d
        return embedding, label_tensor, repo_name_tensor, index

In [7]:
# Create DataLoader

# Creating a DataLoader
def create_dataloader(df, batch_size=32, shuffle=True):
    dataset = CodeDataset(df)
    return DataLoader(dataset, batch_size=batch_size, shuffle=shuffle)

batch_size = 128
test_loader = create_dataloader(df=df_test, batch_size=batch_size)
train_loader = create_dataloader(df=df_train, batch_size=batch_size)
val_loader = create_dataloader(df=df_val,batch_size=batch_size)

full_loader_for_scaler = create_dataloader(df=df, batch_size=512)

In [8]:
from sklearn.preprocessing import StandardScaler
import tqdm

scaler = StandardScaler()

for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(full_loader_for_scaler):
    scaler.partial_fit(batch_X)

/tmp/ipykernel_3408137/796712526.py:6: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(full_loader_for_scaler):

  0%|          | 0/90 [00:00<?, ?it/s]

In [9]:
import joblib

# Save scaler into file
joblib.dump(scaler, 'scalers/scaler_pooler_3labels_15336.pkl')

['scalers/scaler_pooler_3labels_15336.pkl']

In [10]:
import joblib

# Load scaler from file
scaler = joblib.load('scalers/scaler_pooler_3labels_15336.pkl')

In [11]:
import torch.nn as nn

# Define the ANN model
class CodeDiffNN(nn.Module):
    def __init__(self, code_input_size, repo_input_size, hidden_sizes_embedding_pipeline,hidden_sizes_reponame_pipeline,hidden_sizes_merged_pipeline, output_size, dropout_rate):
        super(CodeDiffNN, self).__init__()
        
        # Pipeline for code embeddings
        self.code_fc1 = nn.Linear(code_input_size, hidden_sizes_embedding_pipeline[0])
        self.code_bn1 = nn.BatchNorm1d(hidden_sizes_embedding_pipeline[0])
        self.code_relu1 = nn.ReLU()
        self.code_dropout1 = nn.Dropout(dropout_rate)
        
        self.code_fc2 = nn.Linear(hidden_sizes_embedding_pipeline[0], hidden_sizes_embedding_pipeline[1])
        self.code_bn2 = nn.BatchNorm1d(hidden_sizes_embedding_pipeline[1])
        self.code_relu2 = nn.ReLU()
        self.code_dropout2 = nn.Dropout(dropout_rate)
        
        self.code_fc3 = nn.Linear(hidden_sizes_embedding_pipeline[1], hidden_sizes_embedding_pipeline[2])
        self.code_bn3 = nn.BatchNorm1d(hidden_sizes_embedding_pipeline[2])
        self.code_relu3 = nn.ReLU()
        self.code_dropout3 = nn.Dropout(dropout_rate)  
        
        
        # Pipeline for repo names
        self.repo_fc1 = nn.Linear(repo_input_size, hidden_sizes_reponame_pipeline[0])
        self.repo_bn1 = nn.BatchNorm1d(hidden_sizes_reponame_pipeline[0])
        self.repo_relu1 = nn.ReLU()
        self.repo_dropout1 = nn.Dropout(dropout_rate)
        
        self.repo_fc2 = nn.Linear(hidden_sizes_reponame_pipeline[0], hidden_sizes_reponame_pipeline[1])
        self.repo_bn2 = nn.BatchNorm1d(hidden_sizes_reponame_pipeline[1])
        self.repo_relu2 = nn.ReLU()
        self.repo_dropout2 = nn.Dropout(dropout_rate)

        
        # Combining the outputs of both pipelines
        combined_input_size = hidden_sizes_embedding_pipeline[2] + hidden_sizes_reponame_pipeline[1]   # Since we're combining two pipelines
        self.combined_fc1 = nn.Linear(combined_input_size, hidden_sizes_merged_pipeline[0])
        self.combined_bn1 = nn.BatchNorm1d(hidden_sizes_merged_pipeline[0])
        self.combined_relu1 = nn.ReLU()
        self.combined_dropout1 = nn.Dropout(dropout_rate)

        self.combined_fc2  = nn.Linear(hidden_sizes_merged_pipeline[0], hidden_sizes_merged_pipeline[1])
        self.combined_bn2 = nn.BatchNorm1d(hidden_sizes_merged_pipeline[1])
        self.combined_relu2  = nn.ReLU()
        self.combined_dropout2 = nn.Dropout(dropout_rate)
        
        self.combined_fc3  = nn.Linear(hidden_sizes_merged_pipeline[1], hidden_sizes_merged_pipeline[2])
        self.combined_bn3 = nn.BatchNorm1d(hidden_sizes_merged_pipeline[2])
        self.combined_relu3  = nn.ReLU()
        self.combined_dropout3 = nn.Dropout(dropout_rate)
        
        self.combined_fc4  = nn.Linear(hidden_sizes_merged_pipeline[2], hidden_sizes_merged_pipeline[3])
        self.combined_bn4 = nn.BatchNorm1d(hidden_sizes_merged_pipeline[3])
        self.combined_relu4  = nn.ReLU()
        self.combined_dropout4 = nn.Dropout(dropout_rate)

        # Output layer
        self.fc_out = nn.Linear(hidden_sizes_merged_pipeline[3], output_size)
        
    def forward(self, code_x, repo_x):
        # Process code embeddings
        code_x = self.code_fc1(code_x)
        code_x = self.code_bn1(code_x)
        code_x = self.code_relu1(code_x)
        code_x = self.code_dropout1(code_x)
        
        code_x = self.code_fc2(code_x)
        code_x = self.code_bn2(code_x)
        code_x = self.code_relu2(code_x)
        code_x = self.code_dropout2(code_x)
        
        code_x = self.code_fc3(code_x)
        code_x = self.code_bn3(code_x)
        code_x = self.code_relu3(code_x)
        code_x = self.code_dropout3(code_x)
        
        # Process repo names
        repo_x = self.repo_fc1(repo_x)
        repo_x = self.repo_bn1(repo_x)
        repo_x = self.repo_relu1(repo_x)
        repo_x = self.repo_dropout1(repo_x)
        
        repo_x = self.repo_fc2(repo_x)
        repo_x = self.repo_bn2(repo_x)
        repo_x = self.repo_relu2(repo_x)
        repo_x = self.repo_dropout2(repo_x)
        
        # Combine both outputs
        combined_x = torch.cat((code_x, repo_x), dim=1)
        
        # Process the combined output
        combined_x = self.combined_fc1(combined_x)
        combined_x = self.combined_bn1(combined_x)
        combined_x = self.combined_relu1(combined_x)
        combined_x = self.combined_dropout1(combined_x)

        combined_x = self.combined_fc2(combined_x)
        combined_x = self.combined_bn2(combined_x)
        combined_x = self.combined_relu2(combined_x)
        combined_x = self.combined_dropout2(combined_x)
        
        combined_x = self.combined_fc3(combined_x)
        combined_x = self.combined_bn3(combined_x)
        combined_x = self.combined_relu3(combined_x)
        combined_x = self.combined_dropout3(combined_x)
        
        combined_x = self.combined_fc4(combined_x)
        combined_x = self.combined_bn4(combined_x)
        combined_x = self.combined_relu4(combined_x)
        combined_x = self.combined_dropout4(combined_x)
        
        # Final output
        output = self.fc_out(combined_x)
        return output

In [12]:
import torch.optim as optim
# Define model parameters

code_embedding_dim = df_train['embedding'][5].shape[0]

repo_input_size = len(df_train['repo_name_tensor'][0])
#hidden_sizes = [1024, 512, 256, 128]
hidden_sizes_embedding_pipeline = [1024, 2048, 4096]
hidden_sizes_reponame_pipeline = [512, 1024]
hidden_sizes_merged_pipeline = [2048, 1024, 512, 256]
output_size = resulting_label_count
dropout_rate = 0.05

device = "cuda:0"
model = CodeDiffNN(code_embedding_dim, repo_input_size, hidden_sizes_embedding_pipeline,hidden_sizes_reponame_pipeline,hidden_sizes_merged_pipeline, output_size, dropout_rate).to(device)
# model = SinglePipelineCodeDiffNN(code_embedding_dim, hidden_sizes, output_size).to(device)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=1e-5)

# Decrease learning rate automatically on plateau
scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', patience=400, factor=0.1, verbose=True)

In [13]:
print(resulting_label_count)
print(code_embedding_dim)
torch.cuda.empty_cache()

3
768

In [14]:
# Function to calculate accuracy
def calculate_accuracy(outputs, labels):
    _, predicted = torch.max(outputs, 1)  # Get the index of the max log-probability
    # labels_1d = torch.argmax(labels, dim=1) # turn into 1D tensor
    correct = (predicted == labels).sum().item()
    accuracy = correct / labels.size(0)  # Accuracy = number of correct predictions / total number of samples
    return accuracy

In [15]:
import tqdm

def train_with_data_loader(model,loader):
    
    running_loss = 0.0
    running_accuracy = 0.0
    
    for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):
        
        batch_X = scaler.transform(batch_X)
        batch_X = torch.tensor(batch_X,dtype=torch.float32)
        
        # Forward pass        
        batch_y = batch_y.to(device)
        batch_X = batch_X.to(device)
        batch_X_repo = batch_X_repo.to(device)
        
        batch_y = torch.argmax(batch_y, dim=1)

        # outputs = model(batch_X)
        outputs = model(batch_X, batch_X_repo)
        loss = criterion(outputs, batch_y)
    
        # Backward pass and optimization
        loss.backward()
        optimizer.step()
        
        # Calculate accuracy
        accuracy = calculate_accuracy(outputs, batch_y)
        
        # Update running loss and accuracy
        running_loss += loss.item()
        running_accuracy += accuracy
        
        
    val_loss = running_loss / len(loader)
    val_accuracy = running_accuracy / len(loader)
    
    return val_loss, val_accuracy

In [16]:

import time
from sklearn.metrics import precision_score, recall_score, f1_score


def evaluate_with_data_loader(model, loader):
    
    device = "cpu"
    
    running_loss = 0.0
    running_accuracy = 0.0
    
    all_labels = []
    all_predictions = []
    
    start_time = time.time()  # Inference zamanını başlat
    
    for batch_X, batch_y, batch_X_repo, idx in loader:
        batch_X = scaler.transform(batch_X)
        batch_X = torch.tensor(batch_X, dtype=torch.float32).to(device)  # batch_X'i cihaza taşı
        
        # Forward pass
        batch_y = batch_y.to(device)  # batch_y'yi cihaza taşı
        batch_X_repo = batch_X_repo.to(device)  # batch_X_repo'yu cihaza taşı
        
        batch_y = torch.argmax(batch_y, dim=1)

        outputs = model(batch_X, batch_X_repo)  # Model cihaza zaten taşınmış olmalı
        loss = criterion(outputs, batch_y)
        
        # Calculate accuracy
        accuracy = calculate_accuracy(outputs, batch_y)
        
        # Store labels and predictions for precision, recall, F1-score
        _, predicted = torch.max(outputs, 1)
        all_labels.extend(batch_y.cpu().numpy())  # CPU'ya taşı ve numpy olarak ekle
        all_predictions.extend(predicted.cpu().numpy())  # CPU'ya taşı ve numpy olarak ekle
        
        # Update running loss and accuracy
        running_loss += loss.item()
        running_accuracy += accuracy
        
    end_time = time.time()  # Inference zamanını bitir
    inference_time = end_time - start_time  # Toplam inference zamanı
    
    val_loss = running_loss / len(loader)
    val_accuracy = running_accuracy / len(loader)
    
    # Calculate precision, recall, and F1-score
    precision = precision_score(all_labels, all_predictions, average='weighted')
    recall = recall_score(all_labels, all_predictions, average='weighted')
    f1 = f1_score(all_labels, all_predictions, average='weighted')
    
    # Adjust learning rate based on validation loss
    scheduler.step(val_loss)
    device = "cuda:0"
    return val_loss, val_accuracy, precision, recall, f1, inference_time

In [17]:
def test_with_data_loader(model,loader):
    
    running_loss = 0.0
    running_accuracy = 0.0
    predicted_y = []
    y = []
    
    for batch_X, batch_y, batch_X_repo, idx in loader:
        
        batch_X = scaler.transform(batch_X)
        batch_X = torch.tensor(batch_X,dtype=torch.float32)

        # Forward pass
        batch_y = batch_y.to(device)
        batch_X = batch_X.to(device)
        batch_X_repo = batch_X_repo.to(device)
        
        # index encoding
        batch_y_1D = torch.argmax(batch_y, dim=1)

        outputs = model(batch_X, batch_X_repo)
        # outputs = model(batch_X)
        loss = criterion(outputs, batch_y_1D)
        
        # Calculate accuracy
        accuracy = calculate_accuracy(outputs, batch_y_1D)
        
        # Update running loss and accuracy
        running_loss += loss.item()
        running_accuracy += accuracy

        predicted_y.append(outputs)
        y.append(batch_y)
        
    test_loss = running_loss / len(loader)
    test_accuracy = running_accuracy / len(loader)
    
    return test_loss, test_accuracy, torch.cat(predicted_y, dim=0), torch.cat(y, dim=0)

In [18]:
import copy
import tqdm

# Train the model

# Initialize variables to track the best model and best accuracy
best_accuracy = 0.0

num_epochs = 100

for epoch in tqdm.tqdm_notebook(range(num_epochs)):
    model.train()  # Set the model to training mode
    model.to("cuda:0")  # Modeli cihaza taşı
    
    # Print average loss and accuracy for the epoch
    avg_loss,avg_accuracy = train_with_data_loader(model= model,loader= train_loader)
    print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {avg_loss:.4f}, Accuracy: {avg_accuracy:.4f}')

    # Evaluate on validation data
    model.eval()  # Set the model to evaluation mode
    model.to("cpu")  # Modeli cihaza taşı
    
    with torch.no_grad():  # Disable gradient computation for validation
        val_loss, val_accuracy, precision, recall, f1, inference_time = evaluate_with_data_loader(model, val_loader)
        print(f"Inference Time: {inference_time:.4f} seconds")
        print(f"Loss:{val_loss:.4f}, Accuracy: {val_accuracy:.4f}")
        print(f"Precision: {precision:.4f}, Recall: {recall:.4f}, F1-Score: {f1:.4f}")
    # Check if the current model has the best validation accuracy
    if val_accuracy > best_accuracy:
        best_accuracy = val_accuracy
        torch.save(model.state_dict(), model_directory)

/tmp/ipykernel_3408137/3597344509.py:11: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for epoch in tqdm.tqdm_notebook(range(num_epochs)):

  0%|          | 0/100 [00:00<?, ?it/s]

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [1/100], Loss: 0.6374, Accuracy: 0.7070
Inference Time: 6.2903 seconds
Loss:0.5335, Accuracy: 0.7516
Precision: 0.7558, Recall: 0.7517, F1-Score: 0.7473

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [2/100], Loss: 0.5508, Accuracy: 0.7459
Inference Time: 6.4500 seconds
Loss:0.5442, Accuracy: 0.7463
Precision: 0.7488, Recall: 0.7463, F1-Score: 0.7474

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [3/100], Loss: 0.5245, Accuracy: 0.7580
Inference Time: 6.3692 seconds
Loss:0.5177, Accuracy: 0.7636
Precision: 0.7669, Recall: 0.7635, F1-Score: 0.7639

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [4/100], Loss: 0.5003, Accuracy: 0.7712
Inference Time: 6.3480 seconds
Loss:0.5054, Accuracy: 0.7714
Precision: 0.7751, Recall: 0.7714, F1-Score: 0.7695

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [5/100], Loss: 0.4823, Accuracy: 0.7787
Inference Time: 6.2470 seconds
Loss:0.4957, Accuracy: 0.7729
Precision: 0.7719, Recall: 0.7730, F1-Score: 0.7724

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [6/100], Loss: 0.4627, Accuracy: 0.7852
Inference Time: 6.2363 seconds
Loss:0.4887, Accuracy: 0.7806
Precision: 0.7907, Recall: 0.7806, F1-Score: 0.7805

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [7/100], Loss: 0.4488, Accuracy: 0.7948
Inference Time: 6.3263 seconds
Loss:0.4870, Accuracy: 0.7749
Precision: 0.7765, Recall: 0.7748, F1-Score: 0.7753

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [8/100], Loss: 0.4311, Accuracy: 0.8025
Inference Time: 6.1583 seconds
Loss:0.4852, Accuracy: 0.7854
Precision: 0.7864, Recall: 0.7854, F1-Score: 0.7856

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [9/100], Loss: 0.4159, Accuracy: 0.8114
Inference Time: 6.5598 seconds
Loss:0.4831, Accuracy: 0.7906
Precision: 0.7938, Recall: 0.7906, F1-Score: 0.7909

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [10/100], Loss: 0.4035, Accuracy: 0.8159
Inference Time: 6.1774 seconds
Loss:0.4762, Accuracy: 0.7902
Precision: 0.7886, Recall: 0.7902, F1-Score: 0.7892

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [11/100], Loss: 0.3902, Accuracy: 0.8214
Inference Time: 6.4080 seconds
Loss:0.4832, Accuracy: 0.7974
Precision: 0.7993, Recall: 0.7975, F1-Score: 0.7978

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [12/100], Loss: 0.3799, Accuracy: 0.8290
Inference Time: 6.3779 seconds
Loss:0.4852, Accuracy: 0.7894
Precision: 0.7887, Recall: 0.7895, F1-Score: 0.7888

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [13/100], Loss: 0.3660, Accuracy: 0.8352
Inference Time: 6.2056 seconds
Loss:0.4811, Accuracy: 0.7940
Precision: 0.7955, Recall: 0.7941, F1-Score: 0.7947

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [14/100], Loss: 0.3627, Accuracy: 0.8360
Inference Time: 6.4760 seconds
Loss:0.4814, Accuracy: 0.7994
Precision: 0.8019, Recall: 0.7993, F1-Score: 0.7993

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [15/100], Loss: 0.3492, Accuracy: 0.8423
Inference Time: 6.3628 seconds
Loss:0.4806, Accuracy: 0.7998
Precision: 0.7998, Recall: 0.7998, F1-Score: 0.7998

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [16/100], Loss: 0.3384, Accuracy: 0.8501
Inference Time: 6.1412 seconds
Loss:0.4871, Accuracy: 0.8025
Precision: 0.8042, Recall: 0.8025, F1-Score: 0.8025

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [17/100], Loss: 0.3284, Accuracy: 0.8514
Inference Time: 6.4739 seconds
Loss:0.4856, Accuracy: 0.8050
Precision: 0.8046, Recall: 0.8050, F1-Score: 0.8045

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [18/100], Loss: 0.3221, Accuracy: 0.8544
Inference Time: 6.4220 seconds
Loss:0.5017, Accuracy: 0.8050
Precision: 0.8072, Recall: 0.8050, F1-Score: 0.8047

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [19/100], Loss: 0.3151, Accuracy: 0.8569
Inference Time: 6.2975 seconds
Loss:0.5095, Accuracy: 0.8014
Precision: 0.8020, Recall: 0.8015, F1-Score: 0.8014

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [20/100], Loss: 0.3078, Accuracy: 0.8603
Inference Time: 6.4177 seconds
Loss:0.5132, Accuracy: 0.8002
Precision: 0.8006, Recall: 0.8002, F1-Score: 0.7995

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [21/100], Loss: 0.2981, Accuracy: 0.8646
Inference Time: 6.1876 seconds
Loss:0.5056, Accuracy: 0.8003
Precision: 0.8043, Recall: 0.8003, F1-Score: 0.8015

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [22/100], Loss: 0.2951, Accuracy: 0.8683
Inference Time: 6.3181 seconds
Loss:0.5059, Accuracy: 0.8118
Precision: 0.8140, Recall: 0.8118, F1-Score: 0.8117

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [23/100], Loss: 0.2823, Accuracy: 0.8740
Inference Time: 6.2633 seconds
Loss:0.5507, Accuracy: 0.8087
Precision: 0.8084, Recall: 0.8086, F1-Score: 0.8084

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [24/100], Loss: 0.2781, Accuracy: 0.8760
Inference Time: 6.2102 seconds
Loss:0.5374, Accuracy: 0.8114
Precision: 0.8141, Recall: 0.8114, F1-Score: 0.8118

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [25/100], Loss: 0.2710, Accuracy: 0.8782
Inference Time: 6.5639 seconds
Loss:0.5282, Accuracy: 0.8147
Precision: 0.8155, Recall: 0.8147, F1-Score: 0.8149

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [26/100], Loss: 0.2640, Accuracy: 0.8823
Inference Time: 6.3151 seconds
Loss:0.5430, Accuracy: 0.8095
Precision: 0.8104, Recall: 0.8095, F1-Score: 0.8099

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [27/100], Loss: 0.2555, Accuracy: 0.8845
Inference Time: 6.3691 seconds
Loss:0.5417, Accuracy: 0.8147
Precision: 0.8160, Recall: 0.8147, F1-Score: 0.8152

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [28/100], Loss: 0.2479, Accuracy: 0.8893
Inference Time: 6.2756 seconds
Loss:0.5588, Accuracy: 0.8126
Precision: 0.8132, Recall: 0.8127, F1-Score: 0.8129

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [29/100], Loss: 0.2466, Accuracy: 0.8912
Inference Time: 6.4491 seconds
Loss:0.5623, Accuracy: 0.8149
Precision: 0.8144, Recall: 0.8148, F1-Score: 0.8144

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [30/100], Loss: 0.2382, Accuracy: 0.8938
Inference Time: 6.3506 seconds
Loss:0.5846, Accuracy: 0.8127
Precision: 0.8141, Recall: 0.8127, F1-Score: 0.8133

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [31/100], Loss: 0.2314, Accuracy: 0.8957
Inference Time: 6.4152 seconds
Loss:0.5879, Accuracy: 0.8157
Precision: 0.8170, Recall: 0.8157, F1-Score: 0.8160

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [32/100], Loss: 0.2268, Accuracy: 0.8974
Inference Time: 6.3732 seconds
Loss:0.6093, Accuracy: 0.8164
Precision: 0.8164, Recall: 0.8164, F1-Score: 0.8164

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [33/100], Loss: 0.2217, Accuracy: 0.9006
Inference Time: 6.3820 seconds
Loss:0.6366, Accuracy: 0.8186
Precision: 0.8190, Recall: 0.8186, F1-Score: 0.8186

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [34/100], Loss: 0.2155, Accuracy: 0.9050
Inference Time: 6.4806 seconds
Loss:0.6434, Accuracy: 0.8168
Precision: 0.8182, Recall: 0.8169, F1-Score: 0.8174

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [35/100], Loss: 0.2117, Accuracy: 0.9057
Inference Time: 6.3675 seconds
Loss:0.6465, Accuracy: 0.8135
Precision: 0.8149, Recall: 0.8135, F1-Score: 0.8141

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [36/100], Loss: 0.2113, Accuracy: 0.9042
Inference Time: 6.4048 seconds
Loss:0.6667, Accuracy: 0.8208
Precision: 0.8226, Recall: 0.8208, F1-Score: 0.8206

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [37/100], Loss: 0.2063, Accuracy: 0.9085
Inference Time: 6.2862 seconds
Loss:0.6852, Accuracy: 0.8111
Precision: 0.8125, Recall: 0.8111, F1-Score: 0.8112

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [38/100], Loss: 0.2017, Accuracy: 0.9091
Inference Time: 6.2606 seconds
Loss:0.6785, Accuracy: 0.8170
Precision: 0.8180, Recall: 0.8170, F1-Score: 0.8173

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [39/100], Loss: 0.2024, Accuracy: 0.9082
Inference Time: 6.3031 seconds
Loss:0.6675, Accuracy: 0.8231
Precision: 0.8242, Recall: 0.8231, F1-Score: 0.8233

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [40/100], Loss: 0.1968, Accuracy: 0.9128
Inference Time: 6.3749 seconds
Loss:0.6887, Accuracy: 0.8176
Precision: 0.8182, Recall: 0.8177, F1-Score: 0.8179

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [41/100], Loss: 0.1911, Accuracy: 0.9159
Inference Time: 6.3841 seconds
Loss:0.7106, Accuracy: 0.8163
Precision: 0.8170, Recall: 0.8163, F1-Score: 0.8166

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [42/100], Loss: 0.1915, Accuracy: 0.9135
Inference Time: 6.2271 seconds
Loss:0.7262, Accuracy: 0.8241
Precision: 0.8258, Recall: 0.8241, F1-Score: 0.8248

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [43/100], Loss: 0.1854, Accuracy: 0.9161
Inference Time: 6.1999 seconds
Loss:0.7308, Accuracy: 0.8224
Precision: 0.8235, Recall: 0.8224, F1-Score: 0.8228

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [44/100], Loss: 0.1851, Accuracy: 0.9165
Inference Time: 6.4180 seconds
Loss:0.7513, Accuracy: 0.8206
Precision: 0.8210, Recall: 0.8206, F1-Score: 0.8207

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [45/100], Loss: 0.1785, Accuracy: 0.9191
Inference Time: 6.1873 seconds
Loss:0.7659, Accuracy: 0.8185
Precision: 0.8200, Recall: 0.8185, F1-Score: 0.8191

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [46/100], Loss: 0.1779, Accuracy: 0.9200
Inference Time: 6.2468 seconds
Loss:0.7669, Accuracy: 0.8228
Precision: 0.8236, Recall: 0.8228, F1-Score: 0.8232

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [47/100], Loss: 0.1741, Accuracy: 0.9219
Inference Time: 6.3016 seconds
Loss:0.7910, Accuracy: 0.8251
Precision: 0.8256, Recall: 0.8251, F1-Score: 0.8253

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [48/100], Loss: 0.1738, Accuracy: 0.9206
Inference Time: 6.2573 seconds
Loss:0.7905, Accuracy: 0.8173
Precision: 0.8187, Recall: 0.8173, F1-Score: 0.8178

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [49/100], Loss: 0.1705, Accuracy: 0.9230
Inference Time: 6.1641 seconds
Loss:0.7900, Accuracy: 0.8193
Precision: 0.8201, Recall: 0.8193, F1-Score: 0.8196

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [50/100], Loss: 0.1669, Accuracy: 0.9234
Inference Time: 6.2857 seconds
Loss:0.8245, Accuracy: 0.8213
Precision: 0.8220, Recall: 0.8214, F1-Score: 0.8216

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [51/100], Loss: 0.1651, Accuracy: 0.9263
Inference Time: 6.3110 seconds
Loss:0.8296, Accuracy: 0.8206
Precision: 0.8218, Recall: 0.8206, F1-Score: 0.8210

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [52/100], Loss: 0.1646, Accuracy: 0.9249
Inference Time: 6.4633 seconds
Loss:0.8234, Accuracy: 0.8216
Precision: 0.8233, Recall: 0.8216, F1-Score: 0.8223

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [53/100], Loss: 0.1606, Accuracy: 0.9281
Inference Time: 6.4434 seconds
Loss:0.8302, Accuracy: 0.8216
Precision: 0.8227, Recall: 0.8216, F1-Score: 0.8221

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [54/100], Loss: 0.1594, Accuracy: 0.9296
Inference Time: 6.5052 seconds
Loss:0.8499, Accuracy: 0.8223
Precision: 0.8232, Recall: 0.8224, F1-Score: 0.8226

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [55/100], Loss: 0.1594, Accuracy: 0.9290
Inference Time: 6.5048 seconds
Loss:0.8651, Accuracy: 0.8186
Precision: 0.8199, Recall: 0.8186, F1-Score: 0.8190

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [56/100], Loss: 0.1588, Accuracy: 0.9283
Inference Time: 6.3763 seconds
Loss:0.8701, Accuracy: 0.8218
Precision: 0.8229, Recall: 0.8218, F1-Score: 0.8222

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [57/100], Loss: 0.1551, Accuracy: 0.9305
Inference Time: 6.2750 seconds
Loss:0.8860, Accuracy: 0.8178
Precision: 0.8190, Recall: 0.8177, F1-Score: 0.8181

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [58/100], Loss: 0.1550, Accuracy: 0.9293
Inference Time: 6.3043 seconds
Loss:0.8795, Accuracy: 0.8250
Precision: 0.8255, Recall: 0.8251, F1-Score: 0.8253

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [59/100], Loss: 0.1552, Accuracy: 0.9295
Inference Time: 6.4314 seconds
Loss:0.8951, Accuracy: 0.8239
Precision: 0.8244, Recall: 0.8238, F1-Score: 0.8241

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [60/100], Loss: 0.1527, Accuracy: 0.9313
Inference Time: 6.2225 seconds
Loss:0.9111, Accuracy: 0.8221
Precision: 0.8237, Recall: 0.8221, F1-Score: 0.8226

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [61/100], Loss: 0.1495, Accuracy: 0.9320
Inference Time: 6.3613 seconds
Loss:0.8945, Accuracy: 0.8241
Precision: 0.8250, Recall: 0.8241, F1-Score: 0.8245

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [62/100], Loss: 0.1501, Accuracy: 0.9330
Inference Time: 6.2800 seconds
Loss:0.9064, Accuracy: 0.8240
Precision: 0.8250, Recall: 0.8240, F1-Score: 0.8244

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [63/100], Loss: 0.1486, Accuracy: 0.9311
Inference Time: 6.2747 seconds
Loss:0.9151, Accuracy: 0.8227
Precision: 0.8235, Recall: 0.8228, F1-Score: 0.8231

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [64/100], Loss: 0.1495, Accuracy: 0.9312
Inference Time: 6.4172 seconds
Loss:0.9220, Accuracy: 0.8236
Precision: 0.8244, Recall: 0.8235, F1-Score: 0.8237

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [65/100], Loss: 0.1456, Accuracy: 0.9336
Inference Time: 6.2085 seconds
Loss:0.9392, Accuracy: 0.8249
Precision: 0.8250, Recall: 0.8248, F1-Score: 0.8248

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [66/100], Loss: 0.1426, Accuracy: 0.9332
Inference Time: 6.5714 seconds
Loss:0.9486, Accuracy: 0.8204
Precision: 0.8217, Recall: 0.8205, F1-Score: 0.8210

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [67/100], Loss: 0.1433, Accuracy: 0.9342
Inference Time: 6.2431 seconds
Loss:0.9360, Accuracy: 0.8252
Precision: 0.8263, Recall: 0.8251, F1-Score: 0.8256

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [68/100], Loss: 0.1410, Accuracy: 0.9348
Inference Time: 6.3960 seconds
Loss:0.9424, Accuracy: 0.8244
Precision: 0.8249, Recall: 0.8244, F1-Score: 0.8246

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [69/100], Loss: 0.1400, Accuracy: 0.9361
Inference Time: 6.4708 seconds
Loss:0.9713, Accuracy: 0.8227
Precision: 0.8234, Recall: 0.8227, F1-Score: 0.8229

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [70/100], Loss: 0.1380, Accuracy: 0.9383
Inference Time: 6.3671 seconds
Loss:0.9810, Accuracy: 0.8235
Precision: 0.8249, Recall: 0.8235, F1-Score: 0.8238

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [71/100], Loss: 0.1377, Accuracy: 0.9376
Inference Time: 6.2777 seconds
Loss:0.9887, Accuracy: 0.8252
Precision: 0.8265, Recall: 0.8253, F1-Score: 0.8256

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [72/100], Loss: 0.1345, Accuracy: 0.9379
Inference Time: 6.2636 seconds
Loss:1.0175, Accuracy: 0.8213
Precision: 0.8228, Recall: 0.8214, F1-Score: 0.8218

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [73/100], Loss: 0.1338, Accuracy: 0.9377
Inference Time: 6.4414 seconds
Loss:1.0367, Accuracy: 0.8221
Precision: 0.8234, Recall: 0.8221, F1-Score: 0.8225

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [74/100], Loss: 0.1328, Accuracy: 0.9392
Inference Time: 6.3228 seconds
Loss:1.0475, Accuracy: 0.8222
Precision: 0.8233, Recall: 0.8221, F1-Score: 0.8224

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [75/100], Loss: 0.1322, Accuracy: 0.9384
Inference Time: 6.1942 seconds
Loss:1.0435, Accuracy: 0.8224
Precision: 0.8229, Recall: 0.8224, F1-Score: 0.8225

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [76/100], Loss: 0.1304, Accuracy: 0.9393
Inference Time: 6.4791 seconds
Loss:1.0534, Accuracy: 0.8247
Precision: 0.8255, Recall: 0.8247, F1-Score: 0.8250

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [77/100], Loss: 0.1302, Accuracy: 0.9407
Inference Time: 6.3536 seconds
Loss:1.0832, Accuracy: 0.8242
Precision: 0.8260, Recall: 0.8243, F1-Score: 0.8246

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [78/100], Loss: 0.1287, Accuracy: 0.9396
Inference Time: 6.6231 seconds
Loss:1.0968, Accuracy: 0.8240
Precision: 0.8251, Recall: 0.8241, F1-Score: 0.8244

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [79/100], Loss: 0.1293, Accuracy: 0.9399
Inference Time: 6.5660 seconds
Loss:1.1146, Accuracy: 0.8242
Precision: 0.8246, Recall: 0.8241, F1-Score: 0.8243

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [80/100], Loss: 0.1269, Accuracy: 0.9416
Inference Time: 6.4774 seconds
Loss:1.1166, Accuracy: 0.8228
Precision: 0.8230, Recall: 0.8228, F1-Score: 0.8228

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [81/100], Loss: 0.1283, Accuracy: 0.9406
Inference Time: 6.5578 seconds
Loss:1.1425, Accuracy: 0.8240
Precision: 0.8256, Recall: 0.8241, F1-Score: 0.8246

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [82/100], Loss: 0.1250, Accuracy: 0.9407
Inference Time: 6.0731 seconds
Loss:1.1308, Accuracy: 0.8230
Precision: 0.8242, Recall: 0.8229, F1-Score: 0.8234

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [83/100], Loss: 0.1244, Accuracy: 0.9417
Inference Time: 6.2127 seconds
Loss:1.1653, Accuracy: 0.8213
Precision: 0.8221, Recall: 0.8214, F1-Score: 0.8216

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [84/100], Loss: 0.1266, Accuracy: 0.9407
Inference Time: 6.5282 seconds
Loss:1.1769, Accuracy: 0.8200
Precision: 0.8217, Recall: 0.8201, F1-Score: 0.8202

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [85/100], Loss: 0.1265, Accuracy: 0.9416
Inference Time: 6.4984 seconds
Loss:1.1762, Accuracy: 0.8251
Precision: 0.8257, Recall: 0.8251, F1-Score: 0.8254

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [86/100], Loss: 0.1249, Accuracy: 0.9411
Inference Time: 6.2912 seconds
Loss:1.1633, Accuracy: 0.8228
Precision: 0.8236, Recall: 0.8228, F1-Score: 0.8231

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [87/100], Loss: 0.1229, Accuracy: 0.9426
Inference Time: 6.6438 seconds
Loss:1.1818, Accuracy: 0.8236
Precision: 0.8247, Recall: 0.8235, F1-Score: 0.8238

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [88/100], Loss: 0.1228, Accuracy: 0.9427
Inference Time: 6.6495 seconds
Loss:1.1990, Accuracy: 0.8225
Precision: 0.8236, Recall: 0.8225, F1-Score: 0.8229

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [89/100], Loss: 0.1197, Accuracy: 0.9442
Inference Time: 6.5986 seconds
Loss:1.1983, Accuracy: 0.8225
Precision: 0.8236, Recall: 0.8225, F1-Score: 0.8228

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [90/100], Loss: 0.1207, Accuracy: 0.9430
Inference Time: 6.2964 seconds
Loss:1.1917, Accuracy: 0.8195
Precision: 0.8199, Recall: 0.8195, F1-Score: 0.8196

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [91/100], Loss: 0.1199, Accuracy: 0.9433
Inference Time: 6.3930 seconds
Loss:1.2274, Accuracy: 0.8245
Precision: 0.8253, Recall: 0.8245, F1-Score: 0.8249

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [92/100], Loss: 0.1205, Accuracy: 0.9422
Inference Time: 6.2059 seconds
Loss:1.2303, Accuracy: 0.8248
Precision: 0.8256, Recall: 0.8247, F1-Score: 0.8250

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [93/100], Loss: 0.1192, Accuracy: 0.9433
Inference Time: 6.4182 seconds
Loss:1.2390, Accuracy: 0.8242
Precision: 0.8254, Recall: 0.8243, F1-Score: 0.8247

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [94/100], Loss: 0.1176, Accuracy: 0.9445
Inference Time: 6.3633 seconds
Loss:1.2569, Accuracy: 0.8216
Precision: 0.8222, Recall: 0.8215, F1-Score: 0.8217

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [95/100], Loss: 0.1157, Accuracy: 0.9453
Inference Time: 6.3053 seconds
Loss:1.2652, Accuracy: 0.8219
Precision: 0.8230, Recall: 0.8219, F1-Score: 0.8222

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [96/100], Loss: 0.1176, Accuracy: 0.9453
Inference Time: 6.2538 seconds
Loss:1.2569, Accuracy: 0.8223
Precision: 0.8238, Recall: 0.8222, F1-Score: 0.8227

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [97/100], Loss: 0.1153, Accuracy: 0.9447
Inference Time: 6.2841 seconds
Loss:1.3006, Accuracy: 0.8210
Precision: 0.8220, Recall: 0.8211, F1-Score: 0.8215

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [98/100], Loss: 0.1168, Accuracy: 0.9436
Inference Time: 6.3862 seconds
Loss:1.2856, Accuracy: 0.8201
Precision: 0.8213, Recall: 0.8201, F1-Score: 0.8205

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [99/100], Loss: 0.1139, Accuracy: 0.9458
Inference Time: 6.2761 seconds
Loss:1.2976, Accuracy: 0.8248
Precision: 0.8253, Recall: 0.8248, F1-Score: 0.8250

/tmp/ipykernel_3408137/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [100/100], Loss: 0.1131, Accuracy: 0.9452
Inference Time: 6.4564 seconds
Loss:1.3349, Accuracy: 0.8235
Precision: 0.8247, Recall: 0.8235, F1-Score: 0.8240

In [19]:
# Load model from file
model = CodeDiffNN(code_embedding_dim, repo_input_size, hidden_sizes_embedding_pipeline,hidden_sizes_reponame_pipeline, hidden_sizes_merged_pipeline, output_size, dropout_rate).to(device)
model.load_state_dict(torch.load(model_directory))

In [20]:
with torch.no_grad():
    # Load best model from previous training cycle

    model.eval()
    model.to("cpu")
    
    val_loss, val_accuracy, precision, recall, f1, inference_time = evaluate_with_data_loader(model, test_loader)
    print(f'Accuracy on test data: {val_accuracy}')
    print(f"Inference Time: {inference_time} seconds")
    print(f"Loss:{val_loss}")
    print(f"Precision: {precision}, Recall: {recall}, F1-Score: {f1}")

Accuracy on test data: 0.815727386039886
Inference Time: 6.213409662246704 seconds
Loss:0.9830954880626114
Precision: 0.8175245627832689, Recall: 0.815678887117809, F1-Score: 0.8164334492125461

In [21]:
with torch.no_grad():
    # Load best model from previous training cycle
    model.to("cuda:0")
    model.eval()
    test_loss,test_accuracy,test_outputs,y_test = test_with_data_loader(model=model,loader=test_loader)
    
    print(f'Accuracy on test data: {test_accuracy:.4f}')
    print(test_outputs.shape)

Accuracy on test data: 0.8156
torch.Size([6901, 3])

In [ ]:
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

_, predicted = torch.max(test_outputs.detach().cpu(), 1)  # Get the index of the max log-probability
labels_1d = torch.argmax(y_test, dim=1).cpu() # turn into 1D tensor

# Convert to numpy arrays
y_test_np = labels_1d.numpy()
predicted_np = predicted.numpy()

# Compute confusion matrix
cm = confusion_matrix(y_test_np, predicted_np)
disp = ConfusionMatrixDisplay(confusion_matrix=cm)
disp.plot()
plt.title('Confusion Matrix for Multi-Class Classification')
plt.show()

print(predicted_np)
print(y_test_np)

In [ ]:
import gc
# Free up GPU memory (testing)
print(f"Cached GPU memory before: {torch.cuda.memory_reserved()} bytes")
del model
del test_outputs
del y_test
del predicted
del labels_1d
del val_loader, test_loader, train_loader
del cm
gc.collect()
torch.cuda.empty_cache()
print(f"Cached GPU memory after: {torch.cuda.memory_reserved()} bytes")

In [ ]:
print(df.shape)
print(df_train.shape)
print(df_val.shape)
print(df_test.shape)

In [ ]:
df_ml_train = pd.concat([df_train, df_val], axis=0, ignore_index=True)
df_ml_train

In [ ]:
import numpy as np
# Özellikleri birleştirme ve normalize etme
X_train = np.vstack(df_train.apply(lambda row: np.concatenate([row['embedding'], row['repo_name_tensor']]), axis=1))

# Label tensor'leri argmax ile sınıf etiketine çevirme
y_train = df_train['label_tensor'].apply(lambda x: x.numpy().argmax() if isinstance(x, torch.Tensor) else x).values

X_test = np.vstack(df_test.apply(lambda row: np.concatenate([row['embedding'], row['repo_name_tensor']]), axis=1))

y_test = df_test['label_tensor'].apply(lambda x: x.numpy().argmax() if isinstance(x, torch.Tensor) else x).values

In [ ]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

In [ ]:
from utils import prepare_dataframe, load_embeddings_from_directory_for_df
import time
import csv
import pandas as pd
import torch
import numpy as np
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from catboost import CatBoostClassifier
from lightgbm import LGBMClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

# Modelleri tanımlıyoruz
models = [
    ("XGBoost", xgb.XGBClassifier(objective="multi:softmax", num_class=3, eval_metric="mlogloss")),
    ("RandomForest", RandomForestClassifier(n_estimators=100, random_state=42)),
    ("CatBoost", CatBoostClassifier(iterations=100, learning_rate=0.1, depth=6, verbose=0)),
    ("LightGBM", LGBMClassifier(num_class=3)),
    ("KNN", KNeighborsClassifier(n_neighbors=5)),
    ("NaiveBayes", GaussianNB()),
    ("LogisticRegression", LogisticRegression(max_iter=1000, random_state=42)),
    ("AdaBoost", AdaBoostClassifier(n_estimators=100, random_state=42)),
    ("SVM", SVC(decision_function_shape='ovo', kernel='linear', random_state=42))
]
# Modelleri eğitip tahmin sürelerini hesapla ve hemen CSV'ye kaydet
output_file = "model_metrics.csv"

# CSV dosyasını başlatma
with open(output_file, mode='w', newline='', encoding='utf-8') as file:
    writer = csv.writer(file)
    # Başlıkları yaz
    writer.writerow(["Model Name", "Accuracy", "Precision", "Recall", "F1 Score", "Prediction Time (s)"])

metrics ={} 
# Modelleri işlemeye başla
for model_name, model in models:
    # Modeli eğit
    model.fit(X_train, y_train)

    # Tahmin süresini ölç
    start_time = time.time()
    y_pred = model.predict(X_test)  
    end_time = time.time()
    prediction_time = end_time - start_time  

    # Metrikleri hesapla
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='macro')
    recall = recall_score(y_test, y_pred, average='macro')
    f1 = f1_score(y_test, y_pred, average='macro')
    
    metrics[model_name] = {
        "Accuracy": accuracy,
        "Precision": precision,
        "Recall": recall,
        "F1 Score": f1,
        "Prediction Time (s)": prediction_time
    }

    # Metrikleri ve tahmin süresini yazdır
    print(f"Metrics for {model_name}:")
    print(f"  Accuracy: {accuracy}")
    print(f"  Precision: {precision}")
    print(f"  Recall: {recall}")
    print(f"  F1 Score: {f1}")
    print(f"  Prediction Time (s): {prediction_time:.4f}")

    # Metrikleri CSV'ye yaz
    with open(output_file, mode='a', newline='', encoding='utf-8') as file:  
        writer = csv.writer(file)
        writer.writerow([
            model_name,
            accuracy,
            precision,
            recall,
            f1,
            prediction_time
        ])

print(f"\nMetrics saved incrementally to {output_file}")

In [ ]:
import os
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix

# Eğitilmiş modeller ile confusion matrix'i hesaplama
confusion_matrices = {}
for model_name, model in models:
    y_pred = model.predict(X_test)  # Test verisi üzerinde tahmin yap
    cm = confusion_matrix(y_test, y_pred)
    confusion_matrices[model_name] = cm  # Confusion matrix'i sakla

# Confusion matrix'leri görselleştirme ve tek bir resimde kaydetme
num_models = len(confusion_matrices)
rows = (num_models + 2) // 3  # 3 sütun, gereken satır sayısını hesapla
fig, axes = plt.subplots(nrows=rows, ncols=3, figsize=(18, 6 * rows))

fig.suptitle("Confusion Matrices for Trained Models", fontsize=20)

# Tüm confusion matrix'leri çiz
for ax, (model_name, cm) in zip(axes.flatten(), confusion_matrices.items()):
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False, ax=ax)
    ax.set_title(f"{model_name} Accuracy:{metrics[model_name]['Accuracy']}")
    ax.set_xlabel("Predicted Label")
    ax.set_ylabel("True Label")

# Boş kalan eksenleri kapat
for i in range(num_models, len(axes.flatten())):
    fig.delaxes(axes.flatten()[i])

# Layout'u ayarla ve resmi kaydet
plt.tight_layout(rect=[0, 0.03, 1, 0.95])
output_file = "all_confusion_matrices.png"
plt.savefig(output_file)
plt.close()

print(f"All confusion matrices saved to {output_file}")