In [13]:
from utils import prepare_dataframe, merge_csv_files_in_directory, filterForEqualLabelCount,filterRepoName

embedding_directory = 'embeddings/BERT_Pooler_embeddings_patch_before_only_apache_balanced_46008'
model_directory = 'models/BERT_Pooler_embeddings_patch_before_only_apache_balanced_46008.pth'
column = "patch"
columns_to_keep = [ column]

#merge_csv_files_in_directory()
df = prepare_dataframe("merged.csv", shouldBalance=False, should_merge_csv=False, columns_to_keep=columns_to_keep) 
df = filterRepoName(df,"apache")
df = filterForEqualLabelCount(df=df)
resulting_label_count = df['labels'].nunique()
df

labels
enhancement    37586
bug            32864
clean          17263
performance     5392
refactor        4596
Name: count, dtype: int64
labels
enhancement    37586
bug            32864
clean          17263
Name: count, dtype: int64
15336

,full_repo_name,labels,content_before,index
90648,apache/rocketmq,enhancement,/*\n * Licensed to the Apache Software Foundat...,90648
85016,apache/pinot,enhancement,/**\n * Licensed to the Apache Software Founda...,85016
52956,apache/maven-dependency-plugin,enhancement,/*\n * Licensed to the Apache Software Foundat...,52956
43844,apache/cloudstack,enhancement,// Licensed to the Apache Software Foundation ...,43844
93757,apache/accumulo,enhancement,/*\n * Licensed to the Apache Software Foundat...,93757
...,...,...,...,...
63863,apache/pulsar,clean,/*\n * Licensed to the Apache Software Foundat...,63863
71156,apache/netbeans,clean,/*\n * Licensed to the Apache Software Foundat...,71156
78185,apache/netbeans,clean,/*\n * Licensed to the Apache Software Foundat...,78185
42537,apache/cloudstack,clean,// Licensed to the Apache Software Foundation ...,42537
83887,apache/pinot,clean,/**\n * Licensed to the Apache Software Founda...,83887

In [14]:
import pandas as pd
import torch


# One-hot encoding ile labels sütununu dönüştürme
df_encoded_labels = pd.get_dummies(df, columns=['labels'])
df_encoded_repo = pd.get_dummies(df, columns=['full_repo_name'])

# Özellikler ve etiketler
X_repo = df_encoded_repo.drop(columns=['labels',column,'index'])
X_repo = X_repo.astype(int)

# y = df_encoded.drop(columns=['content_before', 'content_after', 'tokens'])
y = df_encoded_labels.drop(columns=[column, 'full_repo_name','index'])

y = y.astype(int) # convert it 0,1     instead of true, false 

df['label_tensor'] =[torch.tensor(row,dtype=torch.float32) for row in y.values] 
df['repo_name_tensor'] =[torch.tensor(row,dtype=torch.float32) for row in X_repo.values] 

df = df.drop(columns=['full_repo_name', 'labels',column])


#print(df['label_tensor'][0] )
#print(df['repo_name_tensor'][0] )
df

,index,label_tensor,repo_name_tensor
90648,90648,"[tensor(0.), tensor(0.), tensor(1.)]","[tensor(0.), tensor(0.), tensor(0.), tensor(0...."
85016,85016,"[tensor(0.), tensor(0.), tensor(1.)]","[tensor(0.), tensor(0.), tensor(0.), tensor(0...."
52956,52956,"[tensor(0.), tensor(0.), tensor(1.)]","[tensor(0.), tensor(0.), tensor(0.), tensor(0...."
43844,43844,"[tensor(0.), tensor(0.), tensor(1.)]","[tensor(0.), tensor(0.), tensor(0.), tensor(0...."
93757,93757,"[tensor(0.), tensor(0.), tensor(1.)]","[tensor(1.), tensor(0.), tensor(0.), tensor(0...."
...,...,...,...
63863,63863,"[tensor(0.), tensor(1.), tensor(0.)]","[tensor(0.), tensor(0.), tensor(0.), tensor(0...."
71156,71156,"[tensor(0.), tensor(1.), tensor(0.)]","[tensor(0.), tensor(0.), tensor(0.), tensor(0...."
78185,78185,"[tensor(0.), tensor(1.), tensor(0.)]","[tensor(0.), tensor(0.), tensor(0.), tensor(0...."
42537,42537,"[tensor(0.), tensor(1.), tensor(0.)]","[tensor(0.), tensor(0.), tensor(0.), tensor(0...."
83887,83887,"[tensor(0.), tensor(1.), tensor(0.)]","[tensor(0.), tensor(0.), tensor(0.), tensor(0...."

In [15]:
from utils import load_embeddings_from_directory_for_df
import pandas as pd

df = load_embeddings_from_directory_for_df(directory_path=embedding_directory,df=df)

  0%|          | 0/46008 [00:00<?, ?it/s]

In [16]:
from sklearn.model_selection import train_test_split

X_index = df[['index']]  
# Split the code data into test, train and validation sets
X_index_train, X_index_test = train_test_split(X_index, test_size=0.3, random_state=42) #random_state: 0,3074,42
X_index_test, X_index_val = train_test_split(X_index_test, test_size=0.5, random_state=42)

In [17]:
import gc
import torch

df_train = df[df['index'].isin(X_index_train['index'].values)].reset_index(drop=True)
df_val = df[df['index'].isin(X_index_val['index'].values)].reset_index(drop=True)
df_test = df[df['index'].isin(X_index_test['index'].values)].reset_index(drop=True)

torch.cuda.empty_cache()

df_train

,index,label_tensor,repo_name_tensor,embedding
0,52956,"[tensor(0.), tensor(0.), tensor(1.)]","[tensor(0.), tensor(0.), tensor(0.), tensor(0....","[tensor(-0.2511), tensor(-0.3358), tensor(-0.8..."
1,43844,"[tensor(0.), tensor(0.), tensor(1.)]","[tensor(0.), tensor(0.), tensor(0.), tensor(0....","[tensor(-0.5141), tensor(-0.4201), tensor(-0.9..."
2,90569,"[tensor(0.), tensor(0.), tensor(1.)]","[tensor(0.), tensor(0.), tensor(0.), tensor(0....","[tensor(-0.4330), tensor(-0.4168), tensor(-0.9..."
3,59460,"[tensor(0.), tensor(0.), tensor(1.)]","[tensor(0.), tensor(0.), tensor(0.), tensor(0....","[tensor(-0.2931), tensor(-0.4084), tensor(-0.9..."
4,91168,"[tensor(0.), tensor(0.), tensor(1.)]","[tensor(0.), tensor(0.), tensor(0.), tensor(0....","[tensor(-0.4049), tensor(-0.4592), tensor(-0.9..."
...,...,...,...,...
32200,76968,"[tensor(0.), tensor(1.), tensor(0.)]","[tensor(0.), tensor(0.), tensor(0.), tensor(0....","[tensor(-0.3663), tensor(-0.4174), tensor(-0.9..."
32201,63863,"[tensor(0.), tensor(1.), tensor(0.)]","[tensor(0.), tensor(0.), tensor(0.), tensor(0....","[tensor(-0.4989), tensor(-0.4779), tensor(-0.9..."
32202,78185,"[tensor(0.), tensor(1.), tensor(0.)]","[tensor(0.), tensor(0.), tensor(0.), tensor(0....","[tensor(-0.3850), tensor(-0.3938), tensor(-0.9..."
32203,42537,"[tensor(0.), tensor(1.), tensor(0.)]","[tensor(0.), tensor(0.), tensor(0.), tensor(0....","[tensor(-0.4726), tensor(-0.3329), tensor(-0.9..."
32204,83887,"[tensor(0.), tensor(1.), tensor(0.)]","[tensor(0.), tensor(0.), tensor(0.), tensor(0....","[tensor(-0.1514), tensor(-0.3488), tensor(-0.9..."

In [18]:
from torch.utils.data import DataLoader, Dataset
from utils import load_embedding_from_directory

# Custom Dataset Class to handle the dataframe
class CodeDataset(Dataset):
    def __init__(self, df):
        self.df = df
        self.id_list = df['index'].values 

    def __len__(self):
        return len(self.df)
    
    def __getitem__(self, idx):
    
        index = self.id_list[idx]  

        tensor_3d = self.df.loc[self.df['index'] == index, 'embedding'].iloc[0]
        repo_name_tensor = self.df.loc[self.df['index'] == index, 'repo_name_tensor'].iloc[0]
        label_tensor = self.df.loc[self.df['index'] == index, 'label_tensor'].iloc[0]
        
        #print(f"{repo_name_tensor.shape} {tensor_3d.shape} {label_tensor.shape}")
        #print("-------------------------------")
        
        #Flattening
        #embedding = torch.flatten(tensor_3d)
        embedding = tensor_3d
        return embedding, label_tensor, repo_name_tensor, index

In [19]:
# Create DataLoader

# Creating a DataLoader
def create_dataloader(df, batch_size=32, shuffle=True):
    dataset = CodeDataset(df)
    return DataLoader(dataset, batch_size=batch_size, shuffle=shuffle)

batch_size = 128
test_loader = create_dataloader(df=df_test, batch_size=batch_size)
train_loader = create_dataloader(df=df_train, batch_size=batch_size)
val_loader = create_dataloader(df=df_val,batch_size=batch_size)

full_loader_for_scaler = create_dataloader(df=df, batch_size=512)

In [20]:
from sklearn.preprocessing import StandardScaler
import tqdm

scaler = StandardScaler()

for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(full_loader_for_scaler):
    scaler.partial_fit(batch_X)

/tmp/ipykernel_3904407/796712526.py:6: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(full_loader_for_scaler):

  0%|          | 0/90 [00:00<?, ?it/s]

In [21]:
import joblib

# Save scaler into file
joblib.dump(scaler, 'scalers/scaler_pooler_3labels_15336.pkl')

['scalers/scaler_pooler_3labels_15336.pkl']

In [22]:
import joblib

# Load scaler from file
scaler = joblib.load('scalers/scaler_pooler_3labels_15336.pkl')

In [31]:
import torch.nn as nn

# Define the ANN model
class CodeDiffNN(nn.Module):
    def __init__(self, code_input_size, repo_input_size, hidden_sizes_embedding_pipeline,hidden_sizes_reponame_pipeline,hidden_sizes_merged_pipeline, output_size, dropout_rate):
        super(CodeDiffNN, self).__init__()
        
        # Pipeline for code embeddings
        self.code_fc1 = nn.Linear(code_input_size, hidden_sizes_embedding_pipeline[0])
        self.code_bn1 = nn.BatchNorm1d(hidden_sizes_embedding_pipeline[0])
        self.code_relu1 = nn.ReLU()
        self.code_dropout1 = nn.Dropout(dropout_rate)
        
        self.code_fc2 = nn.Linear(hidden_sizes_embedding_pipeline[0], hidden_sizes_embedding_pipeline[1])
        self.code_bn2 = nn.BatchNorm1d(hidden_sizes_embedding_pipeline[1])
        self.code_relu2 = nn.ReLU()
        self.code_dropout2 = nn.Dropout(dropout_rate)
        
        self.code_fc3 = nn.Linear(hidden_sizes_embedding_pipeline[1], hidden_sizes_embedding_pipeline[2])
        self.code_bn3 = nn.BatchNorm1d(hidden_sizes_embedding_pipeline[2])
        self.code_relu3 = nn.ReLU()
        self.code_dropout3 = nn.Dropout(dropout_rate)  

        # Output layer
        self.fc_out = nn.Linear(hidden_sizes_embedding_pipeline[2], output_size)
        
    def forward(self, code_x, repo_x):
        # Process code embeddings
        code_x = self.code_fc1(code_x)
        code_x = self.code_bn1(code_x)
        code_x = self.code_relu1(code_x)
        code_x = self.code_dropout1(code_x)
        
        code_x = self.code_fc2(code_x)
        code_x = self.code_bn2(code_x)
        code_x = self.code_relu2(code_x)
        code_x = self.code_dropout2(code_x)
        
        code_x = self.code_fc3(code_x)
        code_x = self.code_bn3(code_x)
        code_x = self.code_relu3(code_x)
        code_x = self.code_dropout3(code_x)
        
        # Final output
        output = self.fc_out(code_x)
        return output

In [32]:
import torch.optim as optim
# Define model parameters

code_embedding_dim = df_train['embedding'][5].shape[0]

repo_input_size = len(df_train['repo_name_tensor'][0])
#hidden_sizes = [1024, 512, 256, 128]
hidden_sizes_embedding_pipeline = [1024, 2048, 4096]
hidden_sizes_reponame_pipeline = [512, 1024]
hidden_sizes_merged_pipeline = [2048, 1024, 512, 256]
output_size = resulting_label_count
dropout_rate = 0.05

device = "cuda:0"
model = CodeDiffNN(code_embedding_dim, repo_input_size, hidden_sizes_embedding_pipeline,hidden_sizes_reponame_pipeline,hidden_sizes_merged_pipeline, output_size, dropout_rate).to(device)
# model = SinglePipelineCodeDiffNN(code_embedding_dim, hidden_sizes, output_size).to(device)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=1e-5)

# Decrease learning rate automatically on plateau
scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', patience=400, factor=0.1, verbose=True)

In [33]:
print(resulting_label_count)
print(code_embedding_dim)
torch.cuda.empty_cache()

3
768

In [34]:
# Function to calculate accuracy
def calculate_accuracy(outputs, labels):
    _, predicted = torch.max(outputs, 1)  # Get the index of the max log-probability
    # labels_1d = torch.argmax(labels, dim=1) # turn into 1D tensor
    correct = (predicted == labels).sum().item()
    accuracy = correct / labels.size(0)  # Accuracy = number of correct predictions / total number of samples
    return accuracy

In [35]:
import tqdm

def train_with_data_loader(model,loader):
    
    running_loss = 0.0
    running_accuracy = 0.0
    
    for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):
        
        batch_X = scaler.transform(batch_X)
        batch_X = torch.tensor(batch_X,dtype=torch.float32)
        
        # Forward pass        
        batch_y = batch_y.to(device)
        batch_X = batch_X.to(device)
        batch_X_repo = batch_X_repo.to(device)
        
        batch_y = torch.argmax(batch_y, dim=1)

        # outputs = model(batch_X)
        outputs = model(batch_X, batch_X_repo)
        loss = criterion(outputs, batch_y)
    
        # Backward pass and optimization
        loss.backward()
        optimizer.step()
        
        # Calculate accuracy
        accuracy = calculate_accuracy(outputs, batch_y)
        
        # Update running loss and accuracy
        running_loss += loss.item()
        running_accuracy += accuracy
        
        
    val_loss = running_loss / len(loader)
    val_accuracy = running_accuracy / len(loader)
    
    return val_loss, val_accuracy

In [36]:

import time
from sklearn.metrics import precision_score, recall_score, f1_score


def evaluate_with_data_loader(model, loader):
    
    device = "cpu"
    
    running_loss = 0.0
    running_accuracy = 0.0
    
    all_labels = []
    all_predictions = []
    
    start_time = time.time()  # Inference zamanını başlat
    
    for batch_X, batch_y, batch_X_repo, idx in loader:
        batch_X = scaler.transform(batch_X)
        batch_X = torch.tensor(batch_X, dtype=torch.float32).to(device)  # batch_X'i cihaza taşı
        
        # Forward pass
        batch_y = batch_y.to(device)  # batch_y'yi cihaza taşı
        batch_X_repo = batch_X_repo.to(device)  # batch_X_repo'yu cihaza taşı
        
        batch_y = torch.argmax(batch_y, dim=1)

        outputs = model(batch_X, batch_X_repo)  # Model cihaza zaten taşınmış olmalı
        loss = criterion(outputs, batch_y)
        
        # Calculate accuracy
        accuracy = calculate_accuracy(outputs, batch_y)
        
        # Store labels and predictions for precision, recall, F1-score
        _, predicted = torch.max(outputs, 1)
        all_labels.extend(batch_y.cpu().numpy())  # CPU'ya taşı ve numpy olarak ekle
        all_predictions.extend(predicted.cpu().numpy())  # CPU'ya taşı ve numpy olarak ekle
        
        # Update running loss and accuracy
        running_loss += loss.item()
        running_accuracy += accuracy
        
    end_time = time.time()  # Inference zamanını bitir
    inference_time = end_time - start_time  # Toplam inference zamanı
    
    val_loss = running_loss / len(loader)
    val_accuracy = running_accuracy / len(loader)
    
    # Calculate precision, recall, and F1-score
    precision = precision_score(all_labels, all_predictions, average='weighted')
    recall = recall_score(all_labels, all_predictions, average='weighted')
    f1 = f1_score(all_labels, all_predictions, average='weighted')
    
    # Adjust learning rate based on validation loss
    scheduler.step(val_loss)
    device = "cuda:0"
    return val_loss, val_accuracy, precision, recall, f1, inference_time

In [37]:
def test_with_data_loader(model,loader):
    
    running_loss = 0.0
    running_accuracy = 0.0
    predicted_y = []
    y = []
    
    for batch_X, batch_y, batch_X_repo, idx in loader:
        
        batch_X = scaler.transform(batch_X)
        batch_X = torch.tensor(batch_X,dtype=torch.float32)

        # Forward pass
        batch_y = batch_y.to(device)
        batch_X = batch_X.to(device)
        batch_X_repo = batch_X_repo.to(device)
        
        # index encoding
        batch_y_1D = torch.argmax(batch_y, dim=1)

        outputs = model(batch_X, batch_X_repo)
        # outputs = model(batch_X)
        loss = criterion(outputs, batch_y_1D)
        
        # Calculate accuracy
        accuracy = calculate_accuracy(outputs, batch_y_1D)
        
        # Update running loss and accuracy
        running_loss += loss.item()
        running_accuracy += accuracy

        predicted_y.append(outputs)
        y.append(batch_y)
        
    test_loss = running_loss / len(loader)
    test_accuracy = running_accuracy / len(loader)
    
    return test_loss, test_accuracy, torch.cat(predicted_y, dim=0), torch.cat(y, dim=0)

In [38]:
import copy
import tqdm

# Train the model

# Initialize variables to track the best model and best accuracy
best_accuracy = 0.0

num_epochs = 100

for epoch in tqdm.tqdm_notebook(range(num_epochs)):
    model.train()  # Set the model to training mode
    model.to("cuda:0")  # Modeli cihaza taşı
    
    # Print average loss and accuracy for the epoch
    avg_loss,avg_accuracy = train_with_data_loader(model= model,loader= train_loader)
    print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {avg_loss:.4f}, Accuracy: {avg_accuracy:.4f}')

    # Evaluate on validation data
    model.eval()  # Set the model to evaluation mode
    model.to("cpu")  # Modeli cihaza taşı
    
    with torch.no_grad():  # Disable gradient computation for validation
        val_loss, val_accuracy, precision, recall, f1, inference_time = evaluate_with_data_loader(model, val_loader)
        print(f"Inference Time: {inference_time:.4f} seconds")
        print(f"Loss:{val_loss:.4f}, Accuracy: {val_accuracy:.4f}")
        print(f"Precision: {precision:.4f}, Recall: {recall:.4f}, F1-Score: {f1:.4f}")
    # Check if the current model has the best validation accuracy
    if val_accuracy > best_accuracy:
        best_accuracy = val_accuracy
        torch.save(model.state_dict(), model_directory)

/tmp/ipykernel_3904407/3597344509.py:11: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for epoch in tqdm.tqdm_notebook(range(num_epochs)):

  0%|          | 0/100 [00:00<?, ?it/s]

/tmp/ipykernel_3904407/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [1/100], Loss: 1.2788, Accuracy: 0.4777
Inference Time: 12.8475 seconds
Loss:1.1563, Accuracy: 0.4951
Precision: 0.4944, Recall: 0.4951, F1-Score: 0.4905

/tmp/ipykernel_3904407/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [2/100], Loss: 1.1097, Accuracy: 0.4988
Inference Time: 13.1835 seconds
Loss:0.9377, Accuracy: 0.5212
Precision: 0.5196, Recall: 0.5213, F1-Score: 0.4939

/tmp/ipykernel_3904407/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [3/100], Loss: 1.0419, Accuracy: 0.5172
Inference Time: 13.2961 seconds
Loss:1.0943, Accuracy: 0.4966
Precision: 0.4959, Recall: 0.4967, F1-Score: 0.4500

/tmp/ipykernel_3904407/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [4/100], Loss: 1.0755, Accuracy: 0.5244
Inference Time: 13.7517 seconds
Loss:1.2053, Accuracy: 0.5135
Precision: 0.5267, Recall: 0.5135, F1-Score: 0.4425

/tmp/ipykernel_3904407/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [5/100], Loss: 1.0884, Accuracy: 0.5208
Inference Time: 13.5064 seconds
Loss:1.1782, Accuracy: 0.5280
Precision: 0.5786, Recall: 0.5280, F1-Score: 0.5107

/tmp/ipykernel_3904407/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [6/100], Loss: 1.1071, Accuracy: 0.5273
Inference Time: 13.3272 seconds
Loss:1.2191, Accuracy: 0.5211
Precision: 0.5042, Recall: 0.5212, F1-Score: 0.4724

/tmp/ipykernel_3904407/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [7/100], Loss: 1.0834, Accuracy: 0.5274
Inference Time: 13.0681 seconds
Loss:1.1942, Accuracy: 0.5188
Precision: 0.5626, Recall: 0.5190, F1-Score: 0.4907

/tmp/ipykernel_3904407/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [8/100], Loss: 1.0978, Accuracy: 0.5361
Inference Time: 13.3467 seconds
Loss:1.0822, Accuracy: 0.5339
Precision: 0.5412, Recall: 0.5339, F1-Score: 0.4613

/tmp/ipykernel_3904407/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [9/100], Loss: 1.1736, Accuracy: 0.5227
Inference Time: 13.2489 seconds
Loss:0.9958, Accuracy: 0.5465
Precision: 0.5654, Recall: 0.5465, F1-Score: 0.5374

/tmp/ipykernel_3904407/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [10/100], Loss: 1.1070, Accuracy: 0.5331
Inference Time: 13.2759 seconds
Loss:1.0703, Accuracy: 0.5484
Precision: 0.5463, Recall: 0.5484, F1-Score: 0.5440

/tmp/ipykernel_3904407/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [11/100], Loss: 1.1179, Accuracy: 0.5482
Inference Time: 13.2098 seconds
Loss:1.0492, Accuracy: 0.5905
Precision: 0.6163, Recall: 0.5904, F1-Score: 0.5948

/tmp/ipykernel_3904407/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [12/100], Loss: 1.2010, Accuracy: 0.5486
Inference Time: 13.2620 seconds
Loss:1.1366, Accuracy: 0.5303
Precision: 0.5197, Recall: 0.5303, F1-Score: 0.5003

/tmp/ipykernel_3904407/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [13/100], Loss: 1.1536, Accuracy: 0.5432
Inference Time: 13.6515 seconds
Loss:1.2482, Accuracy: 0.5724
Precision: 0.6069, Recall: 0.5724, F1-Score: 0.5736

/tmp/ipykernel_3904407/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [14/100], Loss: 1.1253, Accuracy: 0.5582
Inference Time: 13.5182 seconds
Loss:0.9867, Accuracy: 0.5656
Precision: 0.5795, Recall: 0.5656, F1-Score: 0.5515

/tmp/ipykernel_3904407/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [15/100], Loss: 1.2688, Accuracy: 0.5404
Inference Time: 13.4958 seconds
Loss:1.1658, Accuracy: 0.5904
Precision: 0.5852, Recall: 0.5904, F1-Score: 0.5851

/tmp/ipykernel_3904407/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [16/100], Loss: 1.0631, Accuracy: 0.5493
Inference Time: 13.5211 seconds
Loss:1.0822, Accuracy: 0.5616
Precision: 0.5822, Recall: 0.5616, F1-Score: 0.5294

/tmp/ipykernel_3904407/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [17/100], Loss: 1.2621, Accuracy: 0.5455
Inference Time: 13.6471 seconds
Loss:1.1009, Accuracy: 0.5309
Precision: 0.5319, Recall: 0.5309, F1-Score: 0.4887

/tmp/ipykernel_3904407/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [18/100], Loss: 1.0844, Accuracy: 0.5638
Inference Time: 13.8005 seconds
Loss:1.1514, Accuracy: 0.5788
Precision: 0.6488, Recall: 0.5790, F1-Score: 0.5502

/tmp/ipykernel_3904407/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [19/100], Loss: 1.3091, Accuracy: 0.5659
Inference Time: 13.6876 seconds
Loss:1.2160, Accuracy: 0.5683
Precision: 0.5981, Recall: 0.5682, F1-Score: 0.5516

/tmp/ipykernel_3904407/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [20/100], Loss: 1.0443, Accuracy: 0.5662
Inference Time: 13.8920 seconds
Loss:1.2893, Accuracy: 0.5731
Precision: 0.5700, Recall: 0.5730, F1-Score: 0.5705

/tmp/ipykernel_3904407/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [21/100], Loss: 1.2461, Accuracy: 0.5661
Inference Time: 13.7018 seconds
Loss:1.0818, Accuracy: 0.5869
Precision: 0.6417, Recall: 0.5869, F1-Score: 0.5628

/tmp/ipykernel_3904407/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [22/100], Loss: 1.0259, Accuracy: 0.5713
Inference Time: 13.7375 seconds
Loss:0.9961, Accuracy: 0.5500
Precision: 0.5949, Recall: 0.5500, F1-Score: 0.5052

/tmp/ipykernel_3904407/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [23/100], Loss: 1.1884, Accuracy: 0.5757
Inference Time: 13.8012 seconds
Loss:1.1127, Accuracy: 0.5782
Precision: 0.6014, Recall: 0.5782, F1-Score: 0.5308

/tmp/ipykernel_3904407/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [24/100], Loss: 1.1559, Accuracy: 0.5758
Inference Time: 13.5388 seconds
Loss:1.2652, Accuracy: 0.5772
Precision: 0.6112, Recall: 0.5772, F1-Score: 0.5865

/tmp/ipykernel_3904407/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [25/100], Loss: 1.0622, Accuracy: 0.5686
Inference Time: 13.4218 seconds
Loss:0.9580, Accuracy: 0.5830
Precision: 0.6156, Recall: 0.5829, F1-Score: 0.5764

/tmp/ipykernel_3904407/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [26/100], Loss: 1.0958, Accuracy: 0.5905
Inference Time: 12.9525 seconds
Loss:1.0431, Accuracy: 0.5830
Precision: 0.6445, Recall: 0.5830, F1-Score: 0.5223

/tmp/ipykernel_3904407/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [27/100], Loss: 1.2193, Accuracy: 0.5861
Inference Time: 12.7807 seconds
Loss:1.0562, Accuracy: 0.5868
Precision: 0.6244, Recall: 0.5869, F1-Score: 0.5701

/tmp/ipykernel_3904407/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [28/100], Loss: 1.0976, Accuracy: 0.5749
Inference Time: 13.5534 seconds
Loss:0.9764, Accuracy: 0.5767
Precision: 0.6152, Recall: 0.5766, F1-Score: 0.5756

/tmp/ipykernel_3904407/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [29/100], Loss: 1.0275, Accuracy: 0.5927
Inference Time: 13.0866 seconds
Loss:1.1206, Accuracy: 0.5973
Precision: 0.6198, Recall: 0.5974, F1-Score: 0.5707

/tmp/ipykernel_3904407/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [30/100], Loss: 1.0955, Accuracy: 0.5917
Inference Time: 13.0217 seconds
Loss:0.9934, Accuracy: 0.5924
Precision: 0.6066, Recall: 0.5926, F1-Score: 0.5716

/tmp/ipykernel_3904407/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [31/100], Loss: 1.1502, Accuracy: 0.5932
Inference Time: 12.9123 seconds
Loss:1.0196, Accuracy: 0.6064
Precision: 0.6263, Recall: 0.6063, F1-Score: 0.6103

/tmp/ipykernel_3904407/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [32/100], Loss: 1.0771, Accuracy: 0.6007
Inference Time: 12.7707 seconds
Loss:1.1740, Accuracy: 0.5958
Precision: 0.6525, Recall: 0.5959, F1-Score: 0.5805

/tmp/ipykernel_3904407/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [33/100], Loss: 1.1491, Accuracy: 0.6048
Inference Time: 13.1108 seconds
Loss:1.0000, Accuracy: 0.5890
Precision: 0.6087, Recall: 0.5888, F1-Score: 0.5698

/tmp/ipykernel_3904407/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [34/100], Loss: 0.9491, Accuracy: 0.5948
Inference Time: 12.7893 seconds
Loss:1.0817, Accuracy: 0.6080
Precision: 0.5997, Recall: 0.6079, F1-Score: 0.5973

/tmp/ipykernel_3904407/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [35/100], Loss: 1.1031, Accuracy: 0.6009
Inference Time: 12.8427 seconds
Loss:1.0762, Accuracy: 0.6178
Precision: 0.6559, Recall: 0.6178, F1-Score: 0.6037

/tmp/ipykernel_3904407/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [36/100], Loss: 1.1708, Accuracy: 0.6109
Inference Time: 13.1632 seconds
Loss:1.1274, Accuracy: 0.5897
Precision: 0.6260, Recall: 0.5897, F1-Score: 0.5900

/tmp/ipykernel_3904407/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [37/100], Loss: 1.1330, Accuracy: 0.6013
Inference Time: 12.6400 seconds
Loss:1.0835, Accuracy: 0.6108
Precision: 0.6107, Recall: 0.6108, F1-Score: 0.6107

/tmp/ipykernel_3904407/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [38/100], Loss: 0.9711, Accuracy: 0.6108
Inference Time: 12.8051 seconds
Loss:0.9139, Accuracy: 0.6145
Precision: 0.6137, Recall: 0.6146, F1-Score: 0.5973

/tmp/ipykernel_3904407/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [39/100], Loss: 0.9596, Accuracy: 0.6041
Inference Time: 13.2247 seconds
Loss:1.0626, Accuracy: 0.6143
Precision: 0.6299, Recall: 0.6143, F1-Score: 0.6193

/tmp/ipykernel_3904407/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [40/100], Loss: 0.9995, Accuracy: 0.6130
Inference Time: 12.7453 seconds
Loss:0.9689, Accuracy: 0.6222
Precision: 0.6462, Recall: 0.6221, F1-Score: 0.6293

/tmp/ipykernel_3904407/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [41/100], Loss: 1.0572, Accuracy: 0.6168
Inference Time: 13.2302 seconds
Loss:0.9794, Accuracy: 0.6268
Precision: 0.6344, Recall: 0.6269, F1-Score: 0.6298

/tmp/ipykernel_3904407/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [42/100], Loss: 0.9259, Accuracy: 0.6164
Inference Time: 13.1074 seconds
Loss:1.0493, Accuracy: 0.6139
Precision: 0.6225, Recall: 0.6139, F1-Score: 0.6052

/tmp/ipykernel_3904407/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [43/100], Loss: 1.0075, Accuracy: 0.6124
Inference Time: 13.2230 seconds
Loss:0.9823, Accuracy: 0.6290
Precision: 0.6290, Recall: 0.6289, F1-Score: 0.6260

/tmp/ipykernel_3904407/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [44/100], Loss: 0.9412, Accuracy: 0.6181
Inference Time: 12.8635 seconds
Loss:1.0281, Accuracy: 0.6157
Precision: 0.6328, Recall: 0.6156, F1-Score: 0.6175

/tmp/ipykernel_3904407/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [45/100], Loss: 1.0773, Accuracy: 0.6128
Inference Time: 12.8570 seconds
Loss:1.0390, Accuracy: 0.6157
Precision: 0.6272, Recall: 0.6156, F1-Score: 0.6153

/tmp/ipykernel_3904407/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [46/100], Loss: 0.9723, Accuracy: 0.6192
Inference Time: 13.1604 seconds
Loss:0.7838, Accuracy: 0.6314
Precision: 0.6408, Recall: 0.6314, F1-Score: 0.6344

/tmp/ipykernel_3904407/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [47/100], Loss: 0.9167, Accuracy: 0.6149
Inference Time: 13.1781 seconds
Loss:1.1120, Accuracy: 0.6221
Precision: 0.6296, Recall: 0.6221, F1-Score: 0.6234

/tmp/ipykernel_3904407/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [48/100], Loss: 1.0203, Accuracy: 0.6158
Inference Time: 13.2043 seconds
Loss:0.9037, Accuracy: 0.6318
Precision: 0.6495, Recall: 0.6317, F1-Score: 0.6343

/tmp/ipykernel_3904407/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [49/100], Loss: 0.8621, Accuracy: 0.6298
Inference Time: 13.2557 seconds
Loss:0.8873, Accuracy: 0.6365
Precision: 0.6459, Recall: 0.6365, F1-Score: 0.6362

/tmp/ipykernel_3904407/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [50/100], Loss: 1.0426, Accuracy: 0.6212
Inference Time: 13.3046 seconds
Loss:0.9362, Accuracy: 0.6254
Precision: 0.6278, Recall: 0.6253, F1-Score: 0.6248

/tmp/ipykernel_3904407/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [51/100], Loss: 0.9416, Accuracy: 0.6176
Inference Time: 13.1763 seconds
Loss:0.8158, Accuracy: 0.6409
Precision: 0.6441, Recall: 0.6408, F1-Score: 0.6380

/tmp/ipykernel_3904407/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [52/100], Loss: 0.8918, Accuracy: 0.6247
Inference Time: 13.6299 seconds
Loss:1.0793, Accuracy: 0.6320
Precision: 0.6472, Recall: 0.6320, F1-Score: 0.6351

/tmp/ipykernel_3904407/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [53/100], Loss: 0.9845, Accuracy: 0.6227
Inference Time: 13.4882 seconds
Loss:0.9282, Accuracy: 0.6294
Precision: 0.6461, Recall: 0.6294, F1-Score: 0.6344

/tmp/ipykernel_3904407/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [54/100], Loss: 0.8565, Accuracy: 0.6312
Inference Time: 13.1343 seconds
Loss:0.8882, Accuracy: 0.6354
Precision: 0.6451, Recall: 0.6353, F1-Score: 0.6363

/tmp/ipykernel_3904407/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [55/100], Loss: 0.9698, Accuracy: 0.6367
Inference Time: 12.8891 seconds
Loss:0.8912, Accuracy: 0.6442
Precision: 0.6518, Recall: 0.6442, F1-Score: 0.6467

/tmp/ipykernel_3904407/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [56/100], Loss: 0.9340, Accuracy: 0.6369
Inference Time: 13.1710 seconds
Loss:0.7979, Accuracy: 0.6456
Precision: 0.6538, Recall: 0.6456, F1-Score: 0.6486

/tmp/ipykernel_3904407/2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

In [ ]:
# Load model from file
model = CodeDiffNN(code_embedding_dim, repo_input_size, hidden_sizes_embedding_pipeline,hidden_sizes_reponame_pipeline, hidden_sizes_merged_pipeline, output_size, dropout_rate).to(device)
model.load_state_dict(torch.load(model_directory))

In [ ]:
with torch.no_grad():
    # Load best model from previous training cycle

    model.eval()
    model.to("cpu")
    
    val_loss, val_accuracy, precision, recall, f1, inference_time = evaluate_with_data_loader(model, test_loader)
    print(f'Accuracy on test data: {val_accuracy}')
    print(f"Inference Time: {inference_time} seconds")
    print(f"Loss:{val_loss}")
    print(f"Precision: {precision}, Recall: {recall}, F1-Score: {f1}")

In [ ]:
with torch.no_grad():
    # Load best model from previous training cycle
    model.to("cuda:0")
    model.eval()
    test_loss,test_accuracy,test_outputs,y_test = test_with_data_loader(model=model,loader=test_loader)
    
    print(f'Accuracy on test data: {test_accuracy:.4f}')
    print(test_outputs.shape)

In [ ]:
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

_, predicted = torch.max(test_outputs.detach().cpu(), 1)  # Get the index of the max log-probability
labels_1d = torch.argmax(y_test, dim=1).cpu() # turn into 1D tensor

# Convert to numpy arrays
y_test_np = labels_1d.numpy()
predicted_np = predicted.numpy()

# Compute confusion matrix
cm = confusion_matrix(y_test_np, predicted_np)
disp = ConfusionMatrixDisplay(confusion_matrix=cm)
disp.plot()
plt.title('Confusion Matrix for Multi-Class Classification')
plt.show()

print(predicted_np)
print(y_test_np)

In [ ]:
import gc
# Free up GPU memory (testing)
print(f"Cached GPU memory before: {torch.cuda.memory_reserved()} bytes")
del model
del test_outputs
del y_test
del predicted
del labels_1d
del val_loader, test_loader, train_loader
del cm
gc.collect()
torch.cuda.empty_cache()
print(f"Cached GPU memory after: {torch.cuda.memory_reserved()} bytes")

In [ ]:
print(df.shape)
print(df_train.shape)
print(df_val.shape)
print(df_test.shape)

In [ ]:
df_ml_train = pd.concat([df_train, df_val], axis=0, ignore_index=True)
df_ml_train

In [ ]:
import numpy as np
# Özellikleri birleştirme ve normalize etme
X_train = np.vstack(df_train.apply(lambda row: np.concatenate([row['embedding'], row['repo_name_tensor']]), axis=1))

# Label tensor'leri argmax ile sınıf etiketine çevirme
y_train = df_train['label_tensor'].apply(lambda x: x.numpy().argmax() if isinstance(x, torch.Tensor) else x).values

X_test = np.vstack(df_test.apply(lambda row: np.concatenate([row['embedding'], row['repo_name_tensor']]), axis=1))

y_test = df_test['label_tensor'].apply(lambda x: x.numpy().argmax() if isinstance(x, torch.Tensor) else x).values

In [ ]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

In [ ]:
from utils import prepare_dataframe, load_embeddings_from_directory_for_df
import time
import csv
import pandas as pd
import torch
import numpy as np
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from catboost import CatBoostClassifier
from lightgbm import LGBMClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

# Modelleri tanımlıyoruz
models = [
    ("XGBoost", xgb.XGBClassifier(objective="multi:softmax", num_class=3, eval_metric="mlogloss")),
    ("RandomForest", RandomForestClassifier(n_estimators=100, random_state=42)),
    ("CatBoost", CatBoostClassifier(iterations=100, learning_rate=0.1, depth=6, verbose=0)),
    ("LightGBM", LGBMClassifier(num_class=3)),
    ("KNN", KNeighborsClassifier(n_neighbors=5)),
    ("NaiveBayes", GaussianNB()),
    ("LogisticRegression", LogisticRegression(max_iter=1000, random_state=42)),
    ("AdaBoost", AdaBoostClassifier(n_estimators=100, random_state=42)),
    ("SVM", SVC(decision_function_shape='ovo', kernel='linear', random_state=42))
]
# Modelleri eğitip tahmin sürelerini hesapla ve hemen CSV'ye kaydet
output_file = "model_metrics.csv"

# CSV dosyasını başlatma
with open(output_file, mode='w', newline='', encoding='utf-8') as file:
    writer = csv.writer(file)
    # Başlıkları yaz
    writer.writerow(["Model Name", "Accuracy", "Precision", "Recall", "F1 Score", "Prediction Time (s)"])

metrics ={} 
# Modelleri işlemeye başla
for model_name, model in models:
    # Modeli eğit
    model.fit(X_train, y_train)

    # Tahmin süresini ölç
    start_time = time.time()
    y_pred = model.predict(X_test)  
    end_time = time.time()
    prediction_time = end_time - start_time  

    # Metrikleri hesapla
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='macro')
    recall = recall_score(y_test, y_pred, average='macro')
    f1 = f1_score(y_test, y_pred, average='macro')
    
    metrics[model_name] = {
        "Accuracy": accuracy,
        "Precision": precision,
        "Recall": recall,
        "F1 Score": f1,
        "Prediction Time (s)": prediction_time
    }

    # Metrikleri ve tahmin süresini yazdır
    print(f"Metrics for {model_name}:")
    print(f"  Accuracy: {accuracy}")
    print(f"  Precision: {precision}")
    print(f"  Recall: {recall}")
    print(f"  F1 Score: {f1}")
    print(f"  Prediction Time (s): {prediction_time:.4f}")

    # Metrikleri CSV'ye yaz
    with open(output_file, mode='a', newline='', encoding='utf-8') as file:  
        writer = csv.writer(file)
        writer.writerow([
            model_name,
            accuracy,
            precision,
            recall,
            f1,
            prediction_time
        ])

print(f"\nMetrics saved incrementally to {output_file}")

In [ ]:
import os
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix

# Eğitilmiş modeller ile confusion matrix'i hesaplama
confusion_matrices = {}
for model_name, model in models:
    y_pred = model.predict(X_test)  # Test verisi üzerinde tahmin yap
    cm = confusion_matrix(y_test, y_pred)
    confusion_matrices[model_name] = cm  # Confusion matrix'i sakla

# Confusion matrix'leri görselleştirme ve tek bir resimde kaydetme
num_models = len(confusion_matrices)
rows = (num_models + 2) // 3  # 3 sütun, gereken satır sayısını hesapla
fig, axes = plt.subplots(nrows=rows, ncols=3, figsize=(18, 6 * rows))

fig.suptitle("Confusion Matrices for Trained Models", fontsize=20)

# Tüm confusion matrix'leri çiz
for ax, (model_name, cm) in zip(axes.flatten(), confusion_matrices.items()):
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False, ax=ax)
    ax.set_title(f"{model_name} Accuracy:{metrics[model_name]['Accuracy']}")
    ax.set_xlabel("Predicted Label")
    ax.set_ylabel("True Label")

# Boş kalan eksenleri kapat
for i in range(num_models, len(axes.flatten())):
    fig.delaxes(axes.flatten()[i])

# Layout'u ayarla ve resmi kaydet
plt.tight_layout(rect=[0, 0.03, 1, 0.95])
output_file = "all_confusion_matrices.png"
plt.savefig(output_file)
plt.close()

print(f"All confusion matrices saved to {output_file}")