In [1]:
import pandas as pd

from sklearn.preprocessing import OneHotEncoder

import torch.nn as nn

In [2]:
df = pd.read_csv("all_pull_requests_with_update_over_time.csv")
df

,full_repo_name,class_names,pr_title,labels,created_at,closed_at,commit_sha,commit_message,file_path,file_name,status,additions,deletions,patch
0,mockito/mockito,InterceptedInvocation | MockingProgress | Mock...,Do not pass static mocks to regular listener c...,bug,2020-07-28T08:12:05Z,2020-07-29T15:22:12Z,724619b544096a5bdf488053865f5cccdba2fda1,Does not include static mocks in regular liste...,src/main/java/org/mockito/internal/invocation/...,InterceptedInvocation.java,modified,24,0,"@@ -141,6 +141,30 @@ public Object callRealMet..."
1,mockito/mockito,InterceptedInvocation | MockingProgress | Mock...,Do not pass static mocks to regular listener c...,bug,2020-07-28T08:12:05Z,2020-07-29T15:22:12Z,724619b544096a5bdf488053865f5cccdba2fda1,Does not include static mocks in regular liste...,src/main/java/org/mockito/internal/progress/Mo...,MockingProgress.java,modified,2,0,"@@ -43,6 +43,8 @@ public interface MockingProg..."
2,mockito/mockito,InterceptedInvocation | MockingProgress | Mock...,Do not pass static mocks to regular listener c...,bug,2020-07-28T08:12:05Z,2020-07-29T15:22:12Z,724619b544096a5bdf488053865f5cccdba2fda1,Does not include static mocks in regular liste...,src/main/java/org/mockito/internal/progress/Mo...,MockingProgressImpl.java,modified,9,0,"@@ -159,6 +159,15 @@ public void mockingStarte..."
3,mockito/mockito,InterceptedInvocation | MockingProgress | Mock...,Do not pass static mocks to regular listener c...,bug,2020-07-28T08:12:05Z,2020-07-29T15:22:12Z,724619b544096a5bdf488053865f5cccdba2fda1,Does not include static mocks in regular liste...,src/main/java/org/mockito/listeners/MockCreati...,MockCreationListener.java,modified,8,0,"@@ -19,4 +19,12 @@ public interface MockCreati..."
4,mockito/mockito,InterceptedInvocation | MockingProgress | Mock...,Do not pass static mocks to regular listener c...,bug,2020-07-28T08:12:05Z,2020-07-29T15:22:12Z,724619b544096a5bdf488053865f5cccdba2fda1,Does not include static mocks in regular liste...,subprojects/inline/src/test/java/org/mockitoin...,StaticMockTest.java,modified,0,6,"@@ -11,21 +11,15 @@\n \n import java.util.conc..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8614,mockito/mockito,InterceptedInvocation | StackTraceFilter | Inv...,#365 Simplified the API to get an argument in ...,enhancement,2016-03-02T21:33:39Z,2016-03-10T20:03:18Z,b90d742504301ab25db82b86e7de41f458f5df79,Fixes #365 removed unneccessary cast in Stubbi...,src/test/java/org/mockitousage/stubbing/Stubbi...,StubbingWithCustomAnswerTest.java,modified,1,1,"@@ -28,7 +28,7 @@ public class StubbingWithCus..."
8615,mockito/mockito,InterceptedInvocation | StackTraceFilter | Inv...,#365 Simplified the API to get an argument in ...,enhancement,2016-03-02T21:33:39Z,2016-03-10T20:03:18Z,d138dc3b99547709889d2d6189e264759255ffad,Merge pull request #349 from tarnowskijan/Issu...,src/main/java/org/mockito/internal/verificatio...,AtMost.java,modified,12,1,"@@ -5,6 +5,7 @@\n \n package org.mockito.inter..."
8616,mockito/mockito,InterceptedInvocation | StackTraceFilter | Inv...,#365 Simplified the API to get an argument in ...,enhancement,2016-03-02T21:33:39Z,2016-03-10T20:03:18Z,d138dc3b99547709889d2d6189e264759255ffad,Merge pull request #349 from tarnowskijan/Issu...,src/test/java/org/mockitousage/verification/Ve...,VerificationAfterDelayTest.java,modified,30,0,"@@ -15,6 +15,8 @@\n import org.junit.Rule;\n i..."
8617,mockito/mockito,InterceptedInvocation | StackTraceFilter | Inv...,#365 Simplified the API to get an argument in ...,enhancement,2016-03-02T21:33:39Z,2016-03-10T20:03:18Z,0e1ff58c906ace0411e1f1eedb37ca50bae12599,Merge pull request #317 from astafev/master\n\...,src/main/java/org/mockito/internal/exceptions/...,StackTraceFilter.java,modified,10,28,"@@ -10,8 +10,6 @@\n \n import java.io.Serializ..."
8618,mockito/mockito,InterceptedInvocation | StackTraceFilter | Inv...,#365 Simplified the API to get an argument in ...,enhancement,2016-03-02T21:33:39Z,2016-03-10T20:03:18Z,0e1ff58c906ace0411e1f1eedb37ca50bae12599,Merge pull request #317 from astafev/master\n\...,src/test/java/org/mockito/internal/exceptions/...,StackTraceFilterTest.java,modified,2,2,"@@ -53,7 +53,7 @@ public void shouldFilterOutM..."

In [3]:
#remove unnecessary columns
df.drop("pr_title",inplace = True,axis=1)
df.drop("class_names",inplace = True,axis=1)
df.drop("commit_sha",inplace = True,axis=1)
df.drop("commit_message",inplace = True,axis=1)
df.drop("file_path",inplace = True,axis=1)
df.drop("additions",inplace = True,axis=1)
df.drop("deletions",inplace = True,axis=1)
#df.drop("patch",inplace = True,axis=1)

#remove duplicates
#df = df.drop_duplicates(keep='first')

df

,full_repo_name,labels,created_at,closed_at,file_name,status,patch
0,mockito/mockito,bug,2020-07-28T08:12:05Z,2020-07-29T15:22:12Z,InterceptedInvocation.java,modified,"@@ -141,6 +141,30 @@ public Object callRealMet..."
1,mockito/mockito,bug,2020-07-28T08:12:05Z,2020-07-29T15:22:12Z,MockingProgress.java,modified,"@@ -43,6 +43,8 @@ public interface MockingProg..."
2,mockito/mockito,bug,2020-07-28T08:12:05Z,2020-07-29T15:22:12Z,MockingProgressImpl.java,modified,"@@ -159,6 +159,15 @@ public void mockingStarte..."
3,mockito/mockito,bug,2020-07-28T08:12:05Z,2020-07-29T15:22:12Z,MockCreationListener.java,modified,"@@ -19,4 +19,12 @@ public interface MockCreati..."
4,mockito/mockito,bug,2020-07-28T08:12:05Z,2020-07-29T15:22:12Z,StaticMockTest.java,modified,"@@ -11,21 +11,15 @@\n \n import java.util.conc..."
...,...,...,...,...,...,...,...
8614,mockito/mockito,enhancement,2016-03-02T21:33:39Z,2016-03-10T20:03:18Z,StubbingWithCustomAnswerTest.java,modified,"@@ -28,7 +28,7 @@ public class StubbingWithCus..."
8615,mockito/mockito,enhancement,2016-03-02T21:33:39Z,2016-03-10T20:03:18Z,AtMost.java,modified,"@@ -5,6 +5,7 @@\n \n package org.mockito.inter..."
8616,mockito/mockito,enhancement,2016-03-02T21:33:39Z,2016-03-10T20:03:18Z,VerificationAfterDelayTest.java,modified,"@@ -15,6 +15,8 @@\n import org.junit.Rule;\n i..."
8617,mockito/mockito,enhancement,2016-03-02T21:33:39Z,2016-03-10T20:03:18Z,StackTraceFilter.java,modified,"@@ -10,8 +10,6 @@\n \n import java.io.Serializ..."
8618,mockito/mockito,enhancement,2016-03-02T21:33:39Z,2016-03-10T20:03:18Z,StackTraceFilterTest.java,modified,"@@ -53,7 +53,7 @@ public void shouldFilterOutM..."

In [4]:
# Filter rows where 'labels' doesn't contain '|'
df = df[~df['labels'].str.contains('|', regex=False)]

df

,full_repo_name,labels,created_at,closed_at,file_name,status,patch
0,mockito/mockito,bug,2020-07-28T08:12:05Z,2020-07-29T15:22:12Z,InterceptedInvocation.java,modified,"@@ -141,6 +141,30 @@ public Object callRealMet..."
1,mockito/mockito,bug,2020-07-28T08:12:05Z,2020-07-29T15:22:12Z,MockingProgress.java,modified,"@@ -43,6 +43,8 @@ public interface MockingProg..."
2,mockito/mockito,bug,2020-07-28T08:12:05Z,2020-07-29T15:22:12Z,MockingProgressImpl.java,modified,"@@ -159,6 +159,15 @@ public void mockingStarte..."
3,mockito/mockito,bug,2020-07-28T08:12:05Z,2020-07-29T15:22:12Z,MockCreationListener.java,modified,"@@ -19,4 +19,12 @@ public interface MockCreati..."
4,mockito/mockito,bug,2020-07-28T08:12:05Z,2020-07-29T15:22:12Z,StaticMockTest.java,modified,"@@ -11,21 +11,15 @@\n \n import java.util.conc..."
...,...,...,...,...,...,...,...
8614,mockito/mockito,enhancement,2016-03-02T21:33:39Z,2016-03-10T20:03:18Z,StubbingWithCustomAnswerTest.java,modified,"@@ -28,7 +28,7 @@ public class StubbingWithCus..."
8615,mockito/mockito,enhancement,2016-03-02T21:33:39Z,2016-03-10T20:03:18Z,AtMost.java,modified,"@@ -5,6 +5,7 @@\n \n package org.mockito.inter..."
8616,mockito/mockito,enhancement,2016-03-02T21:33:39Z,2016-03-10T20:03:18Z,VerificationAfterDelayTest.java,modified,"@@ -15,6 +15,8 @@\n import org.junit.Rule;\n i..."
8617,mockito/mockito,enhancement,2016-03-02T21:33:39Z,2016-03-10T20:03:18Z,StackTraceFilter.java,modified,"@@ -10,8 +10,6 @@\n \n import java.io.Serializ..."
8618,mockito/mockito,enhancement,2016-03-02T21:33:39Z,2016-03-10T20:03:18Z,StackTraceFilterTest.java,modified,"@@ -53,7 +53,7 @@ public void shouldFilterOutM..."

In [5]:
# OneHotEncoder creation
encoder = OneHotEncoder()
columns_to_encode = ['labels', 'file_name']

# convert chosen columns and create new dataframe
encoded_data = pd.DataFrame(encoder.fit_transform(df[columns_to_encode]).toarray())

# determine new column names
encoded_data.columns = encoder.get_feature_names_out(columns_to_encode)

# Add new data columns to dataframe
df = pd.concat([df.reset_index(drop=True), encoded_data.reset_index(drop=True)], axis=1)

df

,full_repo_name,labels,created_at,closed_at,file_name,status,patch,labels_bug,labels_enhancement,file_name_AdditionalMatchers.java,...,file_name_VerificationStrategy.java,file_name_VerificationSucceededEvent.java,file_name_VerificationWithTimeout.java,file_name_VerificationWithTimeoutTest.java,file_name_VerificationWrapper.java,file_name_VerificationWrapperInOrderWrapper.java,file_name_WarningsCollector.java,file_name_ZipComparator.java,file_name_ZipCompare.java,file_name_myClass.java
0,mockito/mockito,bug,2020-07-28T08:12:05Z,2020-07-29T15:22:12Z,InterceptedInvocation.java,modified,"@@ -141,6 +141,30 @@ public Object callRealMet...",1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,mockito/mockito,bug,2020-07-28T08:12:05Z,2020-07-29T15:22:12Z,MockingProgress.java,modified,"@@ -43,6 +43,8 @@ public interface MockingProg...",1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,mockito/mockito,bug,2020-07-28T08:12:05Z,2020-07-29T15:22:12Z,MockingProgressImpl.java,modified,"@@ -159,6 +159,15 @@ public void mockingStarte...",1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,mockito/mockito,bug,2020-07-28T08:12:05Z,2020-07-29T15:22:12Z,MockCreationListener.java,modified,"@@ -19,4 +19,12 @@ public interface MockCreati...",1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,mockito/mockito,bug,2020-07-28T08:12:05Z,2020-07-29T15:22:12Z,StaticMockTest.java,modified,"@@ -11,21 +11,15 @@\n \n import java.util.conc...",1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6792,mockito/mockito,enhancement,2016-03-02T21:33:39Z,2016-03-10T20:03:18Z,StubbingWithCustomAnswerTest.java,modified,"@@ -28,7 +28,7 @@ public class StubbingWithCus...",0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6793,mockito/mockito,enhancement,2016-03-02T21:33:39Z,2016-03-10T20:03:18Z,AtMost.java,modified,"@@ -5,6 +5,7 @@\n \n package org.mockito.inter...",0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6794,mockito/mockito,enhancement,2016-03-02T21:33:39Z,2016-03-10T20:03:18Z,VerificationAfterDelayTest.java,modified,"@@ -15,6 +15,8 @@\n import org.junit.Rule;\n i...",0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6795,mockito/mockito,enhancement,2016-03-02T21:33:39Z,2016-03-10T20:03:18Z,StackTraceFilter.java,modified,"@@ -10,8 +10,6 @@\n \n import java.io.Serializ...",0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6796,mockito/mockito,enhancement,2016-03-02T21:33:39Z,2016-03-10T20:03:18Z,StackTraceFilterTest.java,modified,"@@ -53,7 +53,7 @@ public void shouldFilterOutM...",0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [7]:
# convert created_at and closed_at columns to datetime format
df['created_at'] = pd.to_datetime(df['created_at'])
df['closed_at'] = pd.to_datetime(df['closed_at'])

# convert created_at and closed_at columns to epoch-time format
df['created_at_epoch'] = df['created_at'].astype('int64') // 10**9
df['closed_at_epoch'] = df['closed_at'].astype('int64') // 10**9
df

,full_repo_name,labels,created_at,closed_at,file_name,status,patch,labels_bug,labels_enhancement,file_name_AdditionalMatchers.java,...,file_name_VerificationWithTimeout.java,file_name_VerificationWithTimeoutTest.java,file_name_VerificationWrapper.java,file_name_VerificationWrapperInOrderWrapper.java,file_name_WarningsCollector.java,file_name_ZipComparator.java,file_name_ZipCompare.java,file_name_myClass.java,created_at_epoch,closed_at_epoch
0,mockito/mockito,bug,2020-07-28 08:12:05+00:00,2020-07-29 15:22:12+00:00,InterceptedInvocation.java,modified,"@@ -141,6 +141,30 @@ public Object callRealMet...",1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1595923925,1596036132
1,mockito/mockito,bug,2020-07-28 08:12:05+00:00,2020-07-29 15:22:12+00:00,MockingProgress.java,modified,"@@ -43,6 +43,8 @@ public interface MockingProg...",1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1595923925,1596036132
2,mockito/mockito,bug,2020-07-28 08:12:05+00:00,2020-07-29 15:22:12+00:00,MockingProgressImpl.java,modified,"@@ -159,6 +159,15 @@ public void mockingStarte...",1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1595923925,1596036132
3,mockito/mockito,bug,2020-07-28 08:12:05+00:00,2020-07-29 15:22:12+00:00,MockCreationListener.java,modified,"@@ -19,4 +19,12 @@ public interface MockCreati...",1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1595923925,1596036132
4,mockito/mockito,bug,2020-07-28 08:12:05+00:00,2020-07-29 15:22:12+00:00,StaticMockTest.java,modified,"@@ -11,21 +11,15 @@\n \n import java.util.conc...",1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1595923925,1596036132
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6792,mockito/mockito,enhancement,2016-03-02 21:33:39+00:00,2016-03-10 20:03:18+00:00,StubbingWithCustomAnswerTest.java,modified,"@@ -28,7 +28,7 @@ public class StubbingWithCus...",0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1456954419,1457640198
6793,mockito/mockito,enhancement,2016-03-02 21:33:39+00:00,2016-03-10 20:03:18+00:00,AtMost.java,modified,"@@ -5,6 +5,7 @@\n \n package org.mockito.inter...",0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1456954419,1457640198
6794,mockito/mockito,enhancement,2016-03-02 21:33:39+00:00,2016-03-10 20:03:18+00:00,VerificationAfterDelayTest.java,modified,"@@ -15,6 +15,8 @@\n import org.junit.Rule;\n i...",0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1456954419,1457640198
6795,mockito/mockito,enhancement,2016-03-02 21:33:39+00:00,2016-03-10 20:03:18+00:00,StackTraceFilter.java,modified,"@@ -10,8 +10,6 @@\n \n import java.io.Serializ...",0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1456954419,1457640198
6796,mockito/mockito,enhancement,2016-03-02 21:33:39+00:00,2016-03-10 20:03:18+00:00,StackTraceFilterTest.java,modified,"@@ -53,7 +53,7 @@ public void shouldFilterOutM...",0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1456954419,1457640198