In [1]:
from utils import prepare_dataframe

df = prepare_dataframe("merged.csv")
resulting_label_count = df['labels'].nunique()
df

labels
bug            17934
enhancement    16113
clean          15336
performance     5332
refactor        3320
Name: count, dtype: int64
labels
enhancement    15300
bug            15300
clean          15300
Name: count, dtype: int64

,full_repo_name,labels,patch,index
20575,apache/incubator-nemo,enhancement,"@@ -68,4 +68,9 @@ public Set<ExecutorRepresent...",20575
22175,apache/maven-invoker-plugin,enhancement,"@@ -43,12 +43,12 @@\n import java.util.List;\n...",22175
45510,apache/pulsar,enhancement,"@@ -486,8 +486,11 @@ public void testCardinali...",45510
15849,apache/hbase,enhancement,"@@ -1962,9 +1962,9 @@ private void startServic...",15849
5140,apache/cloudstack,enhancement,"@@ -1887,18 +1887,10 @@ public static HostResp...",5140
...,...,...,...,...
24020,apache/netbeans,clean,"@@ -45,7 +45,7 @@ public class WLTargetModuleI...",24020
25558,apache/netbeans,clean,"@@ -95,11 +95,10 @@ public Item getObjectAt(St...",25558
4503,apache/cloudstack,clean,"@@ -113,7 +113,7 @@ public Date getRemoved() {...",4503
27264,apache/netbeans,clean,"@@ -38,7 +38,7 @@ public class SuperPatternFil...",27264
27428,apache/netbeans,clean,"@@ -45,7 +45,7 @@\n */\n public interface Ele...",27428

In [2]:
embedding_directory = 'embeddings/GCB_Pooler_embeddings_patch_before_largewithcodedata_15300limit3label'

In [3]:
import pandas as pd
import torch

# One-hot encoding ile labels sütununu dönüştürme
df_encoded_labels = pd.get_dummies(df, columns=['labels'])
df_encoded_repo = pd.get_dummies(df, columns=['full_repo_name'])

# Özellikler ve etiketler
X_repo = df_encoded_repo.drop(columns=['labels','patch','index'])
X_repo = X_repo.astype(int)

# y = df_encoded.drop(columns=['content_before', 'content_after', 'tokens'])
y = df_encoded_labels.drop(columns=['patch', 'full_repo_name','index'])
y = y.astype(int) # convert it 0,1     instead of true, false 

df['label_tensor'] =[torch.tensor(row,dtype=torch.float32) for row in y.values] 
df['repo_name_tensor'] =[torch.tensor(row,dtype=torch.float32) for row in X_repo.values] 

df = df.drop(columns=['full_repo_name', 'labels','patch'])


print(df['label_tensor'][0] )
print(df['repo_name_tensor'][0] )
df

tensor([1., 0., 0.])
tensor([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.])

,index,label_tensor,repo_name_tensor
20575,20575,"[tensor(0.), tensor(0.), tensor(1.)]","[tensor(0.), tensor(0.), tensor(0.), tensor(0...."
22175,22175,"[tensor(0.), tensor(0.), tensor(1.)]","[tensor(0.), tensor(0.), tensor(0.), tensor(0...."
45510,45510,"[tensor(0.), tensor(0.), tensor(1.)]","[tensor(0.), tensor(0.), tensor(0.), tensor(0...."
15849,15849,"[tensor(0.), tensor(0.), tensor(1.)]","[tensor(0.), tensor(0.), tensor(0.), tensor(0...."
5140,5140,"[tensor(0.), tensor(0.), tensor(1.)]","[tensor(0.), tensor(0.), tensor(0.), tensor(0...."
...,...,...,...
24020,24020,"[tensor(0.), tensor(1.), tensor(0.)]","[tensor(0.), tensor(0.), tensor(0.), tensor(0...."
25558,25558,"[tensor(0.), tensor(1.), tensor(0.)]","[tensor(0.), tensor(0.), tensor(0.), tensor(0...."
4503,4503,"[tensor(0.), tensor(1.), tensor(0.)]","[tensor(0.), tensor(0.), tensor(0.), tensor(0...."
27264,27264,"[tensor(0.), tensor(1.), tensor(0.)]","[tensor(0.), tensor(0.), tensor(0.), tensor(0...."
27428,27428,"[tensor(0.), tensor(1.), tensor(0.)]","[tensor(0.), tensor(0.), tensor(0.), tensor(0...."

In [4]:
from utils import load_embeddings_from_directory_for_df
import pandas as pd

df = load_embeddings_from_directory_for_df(directory_path=embedding_directory,df=df)

  0%|          | 0/45900 [00:00<?, ?it/s]

In [5]:
from sklearn.model_selection import train_test_split

X_index = df[['index']]  
# Split the code data into test, train and validation sets
X_index_train, X_index_test = train_test_split(X_index, test_size=0.3, random_state=42) #random_state: 0,3074,42
X_index_test, X_index_val = train_test_split(X_index_test, test_size=0.5, random_state=42)

In [6]:
import gc
import torch

df_train = df[df['index'].isin(X_index_train['index'].values)].reset_index(drop=True)
df_val = df[df['index'].isin(X_index_val['index'].values)].reset_index(drop=True)
df_test = df[df['index'].isin(X_index_test['index'].values)].reset_index(drop=True)

torch.cuda.empty_cache()

df_train

,index,label_tensor,repo_name_tensor,embedding
0,45510,"[tensor(0.), tensor(0.), tensor(1.)]","[tensor(0.), tensor(0.), tensor(0.), tensor(0....","[tensor(-0.0029), tensor(0.0908), tensor(0.482..."
1,15849,"[tensor(0.), tensor(0.), tensor(1.)]","[tensor(0.), tensor(0.), tensor(0.), tensor(0....","[tensor(-0.0856), tensor(0.0825), tensor(0.423..."
2,46694,"[tensor(0.), tensor(0.), tensor(1.)]","[tensor(0.), tensor(0.), tensor(0.), tensor(0....","[tensor(-0.0422), tensor(-0.0916), tensor(0.47..."
3,2904,"[tensor(0.), tensor(0.), tensor(1.)]","[tensor(0.), tensor(0.), tensor(0.), tensor(0....","[tensor(0.0331), tensor(0.0548), tensor(0.6226..."
4,54362,"[tensor(0.), tensor(0.), tensor(1.)]","[tensor(0.), tensor(0.), tensor(0.), tensor(0....","[tensor(0.0202), tensor(0.0028), tensor(0.4435..."
...,...,...,...,...
32125,24020,"[tensor(0.), tensor(1.), tensor(0.)]","[tensor(0.), tensor(0.), tensor(0.), tensor(0....","[tensor(0.0980), tensor(0.0561), tensor(0.5557..."
32126,25558,"[tensor(0.), tensor(1.), tensor(0.)]","[tensor(0.), tensor(0.), tensor(0.), tensor(0....","[tensor(-0.1340), tensor(0.1632), tensor(0.522..."
32127,4503,"[tensor(0.), tensor(1.), tensor(0.)]","[tensor(0.), tensor(0.), tensor(0.), tensor(0....","[tensor(0.0082), tensor(-0.0061), tensor(0.522..."
32128,27264,"[tensor(0.), tensor(1.), tensor(0.)]","[tensor(0.), tensor(0.), tensor(0.), tensor(0....","[tensor(-0.0277), tensor(0.0247), tensor(0.507..."
32129,27428,"[tensor(0.), tensor(1.), tensor(0.)]","[tensor(0.), tensor(0.), tensor(0.), tensor(0....","[tensor(0.1017), tensor(0.0339), tensor(0.3724..."

In [7]:
from torch.utils.data import DataLoader, Dataset
from utils import load_embedding_from_directory

# Custom Dataset Class to handle the dataframe
class CodeDataset(Dataset):
    def __init__(self, df):
        self.df = df
        self.id_list = df['index'].values 

    def __len__(self):
        return len(self.df)
    
    def __getitem__(self, idx):
    
        index = self.id_list[idx]  

        tensor_3d = self.df.loc[self.df['index'] == index, 'embedding'].iloc[0]
        repo_name_tensor = self.df.loc[self.df['index'] == index, 'repo_name_tensor'].iloc[0]
        label_tensor = self.df.loc[self.df['index'] == index, 'label_tensor'].iloc[0]
        
        #print(f"{repo_name_tensor.shape} {tensor_3d.shape} {label_tensor.shape}")
        #print("-------------------------------")
        
        #Flattening
        #embedding = torch.flatten(tensor_3d)
        embedding = tensor_3d
        return embedding, label_tensor, repo_name_tensor, index

In [8]:
# Create DataLoader

# Creating a DataLoader
def create_dataloader(df, batch_size=32, shuffle=True):
    dataset = CodeDataset(df)
    return DataLoader(dataset, batch_size=batch_size, shuffle=shuffle)

batch_size = 128
test_loader = create_dataloader(df=df_test, batch_size=batch_size)
train_loader = create_dataloader(df=df_train, batch_size=batch_size)
val_loader = create_dataloader(df=df_val,batch_size=batch_size)

full_loader_for_scaler = create_dataloader(df=df, batch_size=512)

In [9]:
from sklearn.preprocessing import StandardScaler
import tqdm

scaler = StandardScaler()

for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(full_loader_for_scaler):
    scaler.partial_fit(batch_X)

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\796712526.py:6: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(full_loader_for_scaler):

  0%|          | 0/90 [00:00<?, ?it/s]

In [10]:
import joblib

# Save scaler into file
joblib.dump(scaler, 'scalers/scaler_pooler_3labels_15300.pkl')

['scalers/scaler_pooler_3labels_15300.pkl']

In [9]:
import joblib

# Load scaler from file
scaler = joblib.load('scalers/scaler_3labels_15300.pkl')

FileNotFoundError: [Errno 2] No such file or directory: 'scalers/scaler_3labels_15300.pkl'

In [ ]:
import torch.nn as nn

# Define the ANN model
class SinglePipelineCodeDiffNN(nn.Module):
    def __init__(self, code_input_size, hidden_sizes, output_size, dropout_rate=0.05):
        super(SinglePipelineCodeDiffNN, self).__init__()
        
        # Pipeline for code embeddings
        self.code_fc1 = nn.Linear(code_input_size, hidden_sizes[0])
        self.code_relu1 = nn.ReLU()
        self.code_dropout1 = nn.Dropout(dropout_rate)
        
        self.code_fc2 = nn.Linear(hidden_sizes[0], hidden_sizes[1])
        self.code_relu2 = nn.ReLU()
        self.code_dropout2 = nn.Dropout(dropout_rate)

        self.code_fc3 = nn.Linear(hidden_sizes[1], hidden_sizes[2])
        self.code_relu3 = nn.ReLU()
        self.code_dropout3 = nn.Dropout(dropout_rate)

        self.code_fc4 = nn.Linear(hidden_sizes[2], hidden_sizes[3])
        self.code_relu4 = nn.ReLU()
        self.code_dropout4 = nn.Dropout(dropout_rate)

        self.code_fc5 = nn.Linear(hidden_sizes[3], hidden_sizes[4])
        self.code_relu5 = nn.ReLU()
        
        self.code_fc_out = nn.Linear(hidden_sizes[4], output_size)

        
    def forward(self, code_x):
        # Process code embeddings
        code_x = self.code_fc1(code_x)
        code_x = self.code_relu1(code_x)
        code_x = self.code_dropout1(code_x)
        
        code_x = self.code_fc2(code_x)
        code_x = self.code_relu2(code_x)
        code_x = self.code_dropout2(code_x)

        code_x = self.code_fc3(code_x)
        code_x = self.code_relu3(code_x)
        code_x = self.code_dropout3(code_x)

        code_x = self.code_fc4(code_x)
        code_x = self.code_relu4(code_x)
        code_x = self.code_dropout4(code_x)

        code_x = self.code_fc5(code_x)
        code_x = self.code_relu5(code_x)

        # Final output
        output = self.code_fc_out(code_x)
        return output

In [ ]:
import torch.nn as nn

# Define the ANN model
class CodeDiffNN(nn.Module):
    def __init__(self, code_input_size, repo_input_size, hidden_sizes_pipeline_1,hidden_sizes_pipeline_2, output_size, dropout_rate=0.2):
        super(CodeDiffNN, self).__init__()
        
        # Pipeline for code embeddings
        self.code_fc1 = nn.Linear(code_input_size, hidden_sizes_pipeline_1[0])
        self.code_relu1 = nn.ReLU()
        self.code_dropout1 = nn.Dropout(dropout_rate)
        
        self.code_fc2 = nn.Linear(hidden_sizes_pipeline_1[0], hidden_sizes_pipeline_1[1])
        self.code_relu2 = nn.ReLU()
        self.code_dropout2 = nn.Dropout(dropout_rate)
        
        self.code_fc3 = nn.Linear(hidden_sizes_pipeline_1[1], hidden_sizes_pipeline_1[2])
        self.code_relu3 = nn.ReLU()
        self.code_dropout3 = nn.Dropout(dropout_rate)  
        
        
        # Pipeline for repo names
        self.repo_fc1 = nn.Linear(repo_input_size, hidden_sizes_pipeline_2[0])
        self.repo_relu1 = nn.ReLU()
        self.repo_dropout1 = nn.Dropout(dropout_rate)
        
        self.repo_fc2 = nn.Linear(hidden_sizes_pipeline_2[0], hidden_sizes_pipeline_2[1])
        self.repo_relu2 = nn.ReLU()
        self.repo_dropout2 = nn.Dropout(dropout_rate)

        
        # Combining the outputs of both pipelines
        combined_input_size = hidden_sizes_pipeline_1[2] + hidden_sizes_pipeline_2[1]   # Since we're combining two pipelines
        self.fc_combined1 = nn.Linear(combined_input_size, hidden_sizes_pipeline_2[2])
        self.relu_combined1 = nn.ReLU()
        self.dropout_combined1 = nn.Dropout(dropout_rate)

        self.fc_combined2 = nn.Linear(hidden_sizes_pipeline_2[2], hidden_sizes_pipeline_2[3])
        self.relu_combined2 = nn.ReLU()
        self.dropout_combined2 = nn.Dropout(dropout_rate)

        # Output layer
        self.fc_out = nn.Linear(hidden_sizes_pipeline_2[3], output_size)
        
    def forward(self, code_x, repo_x):
        # Process code embeddings
        code_x = self.code_fc1(code_x)
        code_x = self.code_relu1(code_x)
        code_x = self.code_dropout1(code_x)
        
        code_x = self.code_fc2(code_x)
        code_x = self.code_relu2(code_x)
        code_x = self.code_dropout2(code_x)
        
        code_x = self.code_fc3(code_x)
        code_x = self.code_relu3(code_x)
        code_x = self.code_dropout3(code_x)
        
        # Process repo names
        repo_x = self.repo_fc1(repo_x)
        repo_x = self.repo_relu1(repo_x)
        repo_x = self.repo_dropout1(repo_x)
        
        repo_x = self.repo_fc2(repo_x)
        repo_x = self.repo_relu2(repo_x)
        repo_x = self.repo_dropout2(repo_x)
        
        # Combine both outputs
        combined_x = torch.cat((code_x, repo_x), dim=1)
        
        # Process the combined output
        combined_x = self.fc_combined1(combined_x)
        combined_x = self.relu_combined1(combined_x)
        combined_x = self.dropout_combined1(combined_x)

        combined_x = self.fc_combined2(combined_x)
        combined_x = self.relu_combined2(combined_x)
        combined_x = self.dropout_combined2(combined_x)
        
        # Final output
        output = self.fc_out(combined_x)
        return output

In [ ]:
# import torch.nn as nn

# # Define the ANN model
# class CodeDiffNN(nn.Module):
#     def __init__(self, code_embedding_dim, repo_input_size, hidden_sizes, output_size, dropout_rate=0.001):
#         super(CodeDiffNN, self).__init__()
        
#         # Pipeline for code embeddings (Conv2D for 2D input)
#         # Set in_channels to the embedding dimension (e.g., 768)
#         # Increase out_channels to better handle high-dimensional inputs
#         self.code_conv1 = nn.Conv2d(in_channels=code_embedding_dim, out_channels=128, kernel_size=3, padding=1)
#         self.code_relu1 = nn.ReLU()
#         self.code_dropout1 = nn.Dropout(dropout_rate)
        
#         self.code_conv2 = nn.Conv2d(in_channels=128, out_channels=256, kernel_size=3, padding=1)
#         self.code_relu2 = nn.ReLU()
#         self.code_dropout2 = nn.Dropout(dropout_rate)

#         # Assuming a fixed input size for flattening (adjust this based on the input size and conv layer operations)
#         self.code_flatten = nn.Flatten()

#         # Flattened output from conv layers should map to hidden_sizes[1]
#         self.code_fc = nn.Linear(256*512, hidden_sizes[1])  # Modify based on input dimensions
        
#         # Pipeline for repo names (still using Linear layers for 1D input)
#         self.repo_fc1 = nn.Linear(repo_input_size, hidden_sizes[0])
#         self.repo_relu1 = nn.ReLU()
#         self.repo_dropout1 = nn.Dropout(dropout_rate)
        
#         self.repo_fc2 = nn.Linear(hidden_sizes[0], hidden_sizes[1])
#         self.repo_relu2 = nn.ReLU()
#         self.repo_dropout2 = nn.Dropout(dropout_rate)
        
#         # Combining the outputs of both pipelines
#         combined_input_size = hidden_sizes[1] * 2  # Since we're combining two pipelines
#         self.fc_combined = nn.Linear(combined_input_size, hidden_sizes[2])
#         self.relu_combined = nn.ReLU()
#         self.dropout_combined = nn.Dropout(dropout_rate)

#         # Output layer
#         self.fc_out = nn.Linear(hidden_sizes[2], output_size)
        
#     def forward(self, code_x, repo_x):
#         # Reformat input
#         # [batch_size, sequence_length, embedding_dim] -> [batch_size, embedding_dim, sequence_length, 1]
#         code_x = code_x.permute(0, 2, 1).unsqueeze(-1)
        
#         # Process code embeddings (2D input)
#         code_x = self.code_conv1(code_x)
#         code_x = self.code_relu1(code_x)
#         code_x = self.code_dropout1(code_x)
        
#         code_x = self.code_conv2(code_x)
#         code_x = self.code_relu2(code_x)
#         code_x = self.code_dropout2(code_x)
        
#         # Flatten the output from the conv layers before the fully connected layer
#         code_x = self.code_flatten(code_x)
#         code_x = self.code_fc(code_x)
        
#         # Process repo names (1D input)
#         repo_x = self.repo_fc1(repo_x)
#         repo_x = self.repo_relu1(repo_x)
#         repo_x = self.repo_dropout1(repo_x)
        
#         repo_x = self.repo_fc2(repo_x)
#         repo_x = self.repo_relu2(repo_x)
#         repo_x = self.repo_dropout2(repo_x)
        
#         # Combine both outputs
#         combined_x = torch.cat((code_x, repo_x), dim=1)
        
#         # Process the combined output
#         combined_x = self.fc_combined(combined_x)
#         combined_x = self.relu_combined(combined_x)
#         combined_x = self.dropout_combined(combined_x)
        
#         # Final output
#         output = self.fc_out(combined_x)
#         return output

In [ ]:
import torch.optim as optim
# Define model parameters

code_embedding_dim = df_train['embedding'][5].shape[0]

repo_input_size = len(df_train['repo_name_tensor'][0])
hidden_sizes = [1024, 512, 256, 128]
hidden_sizes_pipeline_1 = [1024, 512, 256]
hidden_sizes_pipeline_2 = [512, 256, 256, 128]
output_size = resulting_label_count
dropout_rate = 0.2

device = "cuda:0"
model = CodeDiffNN(code_embedding_dim, repo_input_size, hidden_sizes_pipeline_1,hidden_sizes_pipeline_2, output_size, dropout_rate).to(device)
# model = SinglePipelineCodeDiffNN(code_embedding_dim, hidden_sizes, output_size).to(device)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=1e-4)

# Decrease learning rate automatically on plateau
scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', patience=400, factor=0.1, verbose=True)

In [ ]:
print(resulting_label_count)
print(code_embedding_dim)
torch.cuda.empty_cache()

3
768

In [ ]:
# Function to calculate accuracy
def calculate_accuracy(outputs, labels):
    _, predicted = torch.max(outputs, 1)  # Get the index of the max log-probability
    # labels_1d = torch.argmax(labels, dim=1) # turn into 1D tensor
    correct = (predicted == labels).sum().item()
    accuracy = correct / labels.size(0)  # Accuracy = number of correct predictions / total number of samples
    return accuracy

In [ ]:
import tqdm

def train_with_data_loader(model,loader):
    
    running_loss = 0.0
    running_accuracy = 0.0
    
    for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):
        
        batch_X = scaler.transform(batch_X)
        batch_X = torch.tensor(batch_X,dtype=torch.float32)
        
        # Forward pass        
        batch_y = batch_y.to(device)
        batch_X = batch_X.to(device)
        batch_X_repo = batch_X_repo.to(device)
        
        batch_y = torch.argmax(batch_y, dim=1)

        # outputs = model(batch_X)
        outputs = model(batch_X, batch_X_repo)
        loss = criterion(outputs, batch_y)
    
        # Backward pass and optimization
        loss.backward()
        optimizer.step()
        
        # Calculate accuracy
        accuracy = calculate_accuracy(outputs, batch_y)
        
        # Update running loss and accuracy
        running_loss += loss.item()
        running_accuracy += accuracy
        
        
    val_loss = running_loss / len(loader)
    val_accuracy = running_accuracy / len(loader)
    
    return val_loss, val_accuracy

In [ ]:
def evaluate_with_data_loader(model,loader):
    
    running_loss = 0.0
    running_accuracy = 0.0
    
    for batch_X, batch_y, batch_X_repo, idx in loader:
        
        batch_X = scaler.transform(batch_X)
        batch_X = torch.tensor(batch_X,dtype=torch.float32)
        
        # Forward pass
        batch_y = batch_y.to(device)
        batch_X = batch_X.to(device)
        batch_X_repo = batch_X_repo.to(device)
        
        batch_y = torch.argmax(batch_y, dim=1)

        outputs = model(batch_X, batch_X_repo)
        # outputs = model(batch_X)
        loss = criterion(outputs, batch_y)
        
        # Calculate accuracy
        accuracy = calculate_accuracy(outputs, batch_y)
        
        # Update running loss and accuracy
        running_loss += loss.item()
        running_accuracy += accuracy
        
        
    val_loss = running_loss / len(loader)
    val_accuracy = running_accuracy / len(loader)
    
    # Adjust learning rate based on validation loss
    scheduler.step(val_loss)
    
    return val_loss, val_accuracy

In [ ]:
def test_with_data_loader(model,loader):
    
    running_loss = 0.0
    running_accuracy = 0.0
    predicted_y = []
    y = []
    
    for batch_X, batch_y, batch_X_repo, idx in loader:
        
        batch_X = scaler.transform(batch_X)
        batch_X = torch.tensor(batch_X,dtype=torch.float32)

        # Forward pass
        batch_y = batch_y.to(device)
        batch_X = batch_X.to(device)
        batch_X_repo = batch_X_repo.to(device)
        
        # index encoding
        batch_y_1D = torch.argmax(batch_y, dim=1)

        outputs = model(batch_X, batch_X_repo)
        # outputs = model(batch_X)
        loss = criterion(outputs, batch_y_1D)
        
        # Calculate accuracy
        accuracy = calculate_accuracy(outputs, batch_y_1D)
        
        # Update running loss and accuracy
        running_loss += loss.item()
        running_accuracy += accuracy

        predicted_y.append(outputs)
        y.append(batch_y)
        
    test_loss = running_loss / len(loader)
    test_accuracy = running_accuracy / len(loader)
    
    return test_loss, test_accuracy, torch.cat(predicted_y, dim=0), torch.cat(y, dim=0)

In [ ]:
import copy
import tqdm

# Train the model

# Initialize variables to track the best model and best accuracy
best_accuracy = 0.0
best_model = None

num_epochs = 500

for epoch in tqdm.tqdm_notebook(range(num_epochs)):
    model.train()  # Set the model to training mode
    
    # Print average loss and accuracy for the epoch
    avg_loss,avg_accuracy = train_with_data_loader(model= model,loader= train_loader)
    print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {avg_loss:.4f}, Accuracy: {avg_accuracy:.4f}')

    # Evaluate on validation data
    model.eval()  # Set the model to evaluation mode
    
    with torch.no_grad():  # Disable gradient computation for validation
        val_loss,val_accuracy = evaluate_with_data_loader(model=model,loader=val_loader)
        print(f'Validation Loss: {val_loss:.4f}, Validation Accuracy: {val_accuracy:.4f}')
    
    # Check if the current model has the best validation accuracy
    if val_accuracy > best_accuracy:
        best_accuracy = val_accuracy
        best_model = copy.deepcopy(model.state_dict())  # Save the model with the best accuracy

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\902125487.py:12: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for epoch in tqdm.tqdm_notebook(range(num_epochs)):

  0%|          | 0/500 [00:00<?, ?it/s]

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [1/500], Loss: 0.9352, Accuracy: 0.6011
Validation Loss: 0.8220, Validation Accuracy: 0.6305

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [2/500], Loss: 0.8337, Accuracy: 0.6077
Validation Loss: 0.7485, Validation Accuracy: 0.6650

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [3/500], Loss: 0.7195, Accuracy: 0.6623
Validation Loss: 0.6714, Validation Accuracy: 0.6884

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [4/500], Loss: 0.6465, Accuracy: 0.7051
Validation Loss: 0.6403, Validation Accuracy: 0.7103

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [5/500], Loss: 0.6057, Accuracy: 0.7302
Validation Loss: 0.6027, Validation Accuracy: 0.7195

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [6/500], Loss: 0.5644, Accuracy: 0.7394
Validation Loss: 0.5735, Validation Accuracy: 0.7307

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [7/500], Loss: 0.5414, Accuracy: 0.7456
Validation Loss: 0.5493, Validation Accuracy: 0.7468

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [8/500], Loss: 0.5192, Accuracy: 0.7619
Validation Loss: 0.5440, Validation Accuracy: 0.7455

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [9/500], Loss: 0.5063, Accuracy: 0.7657
Validation Loss: 0.5383, Validation Accuracy: 0.7525

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [10/500], Loss: 0.4924, Accuracy: 0.7778
Validation Loss: 0.5334, Validation Accuracy: 0.7490

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [11/500], Loss: 0.4831, Accuracy: 0.7789
Validation Loss: 0.5344, Validation Accuracy: 0.7563

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [12/500], Loss: 0.4665, Accuracy: 0.7862
Validation Loss: 0.5182, Validation Accuracy: 0.7584

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [13/500], Loss: 0.4605, Accuracy: 0.7944
Validation Loss: 0.5175, Validation Accuracy: 0.7703

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [14/500], Loss: 0.4445, Accuracy: 0.8011
Validation Loss: 0.5186, Validation Accuracy: 0.7679

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [15/500], Loss: 0.4419, Accuracy: 0.8000
Validation Loss: 0.5167, Validation Accuracy: 0.7707

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [16/500], Loss: 0.4322, Accuracy: 0.8095
Validation Loss: 0.5667, Validation Accuracy: 0.7610

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [17/500], Loss: 0.4260, Accuracy: 0.8100
Validation Loss: 0.5315, Validation Accuracy: 0.7667

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [18/500], Loss: 0.4247, Accuracy: 0.8057
Validation Loss: 0.5522, Validation Accuracy: 0.7513

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [19/500], Loss: 0.4008, Accuracy: 0.8251
Validation Loss: 0.5453, Validation Accuracy: 0.7840

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [20/500], Loss: 0.3910, Accuracy: 0.8318
Validation Loss: 0.5628, Validation Accuracy: 0.7762

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [21/500], Loss: 0.3693, Accuracy: 0.8423
Validation Loss: 0.5053, Validation Accuracy: 0.7863

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [22/500], Loss: 0.3659, Accuracy: 0.8403
Validation Loss: 0.5056, Validation Accuracy: 0.7872

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [23/500], Loss: 0.3481, Accuracy: 0.8541
Validation Loss: 0.5215, Validation Accuracy: 0.7915

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [24/500], Loss: 0.3486, Accuracy: 0.8579
Validation Loss: 0.5744, Validation Accuracy: 0.7871

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [25/500], Loss: 0.3155, Accuracy: 0.8686
Validation Loss: 0.5526, Validation Accuracy: 0.7928

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [26/500], Loss: 0.3109, Accuracy: 0.8726
Validation Loss: 0.5604, Validation Accuracy: 0.7855

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [27/500], Loss: 0.2902, Accuracy: 0.8817
Validation Loss: 0.5711, Validation Accuracy: 0.7994

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [28/500], Loss: 0.2834, Accuracy: 0.8867
Validation Loss: 0.5943, Validation Accuracy: 0.8011

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [29/500], Loss: 0.2641, Accuracy: 0.8906
Validation Loss: 0.5804, Validation Accuracy: 0.7945

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [30/500], Loss: 0.2536, Accuracy: 0.8938
Validation Loss: 0.6329, Validation Accuracy: 0.7925

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [31/500], Loss: 0.2343, Accuracy: 0.9059
Validation Loss: 0.6511, Validation Accuracy: 0.8079

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [32/500], Loss: 0.2222, Accuracy: 0.9105
Validation Loss: 0.7403, Validation Accuracy: 0.8015

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [33/500], Loss: 0.2018, Accuracy: 0.9174
Validation Loss: 0.7330, Validation Accuracy: 0.8030

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [34/500], Loss: 0.1924, Accuracy: 0.9236
Validation Loss: 0.7625, Validation Accuracy: 0.8014

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [35/500], Loss: 0.1819, Accuracy: 0.9275
Validation Loss: 0.7405, Validation Accuracy: 0.8077

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [36/500], Loss: 0.1714, Accuracy: 0.9310
Validation Loss: 0.8389, Validation Accuracy: 0.8044

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [37/500], Loss: 0.1595, Accuracy: 0.9366
Validation Loss: 0.8888, Validation Accuracy: 0.8084

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [38/500], Loss: 0.1549, Accuracy: 0.9379
Validation Loss: 0.9333, Validation Accuracy: 0.8094

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [39/500], Loss: 0.1497, Accuracy: 0.9399
Validation Loss: 1.0829, Validation Accuracy: 0.7992

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [40/500], Loss: 0.1389, Accuracy: 0.9450
Validation Loss: 0.9978, Validation Accuracy: 0.8057

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [41/500], Loss: 0.1413, Accuracy: 0.9433
Validation Loss: 1.1171, Validation Accuracy: 0.8067

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [42/500], Loss: 0.1303, Accuracy: 0.9489
Validation Loss: 1.0821, Validation Accuracy: 0.8054

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [43/500], Loss: 0.1232, Accuracy: 0.9514
Validation Loss: 1.1241, Validation Accuracy: 0.8078

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [44/500], Loss: 0.1157, Accuracy: 0.9544
Validation Loss: 1.1914, Validation Accuracy: 0.8067

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [45/500], Loss: 0.1092, Accuracy: 0.9578
Validation Loss: 1.3013, Validation Accuracy: 0.8059

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [46/500], Loss: 0.1083, Accuracy: 0.9595
Validation Loss: 1.4003, Validation Accuracy: 0.8051

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [47/500], Loss: 0.1062, Accuracy: 0.9584
Validation Loss: 1.2870, Validation Accuracy: 0.8105

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [48/500], Loss: 0.1025, Accuracy: 0.9611
Validation Loss: 1.4746, Validation Accuracy: 0.8044

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [49/500], Loss: 0.0948, Accuracy: 0.9627
Validation Loss: 1.4807, Validation Accuracy: 0.8109

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [50/500], Loss: 0.0923, Accuracy: 0.9632
Validation Loss: 1.5556, Validation Accuracy: 0.8064

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [51/500], Loss: 0.0924, Accuracy: 0.9640
Validation Loss: 1.5985, Validation Accuracy: 0.8127

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [52/500], Loss: 0.0881, Accuracy: 0.9662
Validation Loss: 1.6021, Validation Accuracy: 0.8135

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [53/500], Loss: 0.0843, Accuracy: 0.9661
Validation Loss: 1.6654, Validation Accuracy: 0.8071

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [54/500], Loss: 0.0844, Accuracy: 0.9691
Validation Loss: 1.5922, Validation Accuracy: 0.8166

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [55/500], Loss: 0.0815, Accuracy: 0.9686
Validation Loss: 1.8189, Validation Accuracy: 0.8066

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [56/500], Loss: 0.0782, Accuracy: 0.9713
Validation Loss: 1.7666, Validation Accuracy: 0.8145

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [57/500], Loss: 0.0737, Accuracy: 0.9716
Validation Loss: 1.6228, Validation Accuracy: 0.8131

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [58/500], Loss: 0.0748, Accuracy: 0.9713
Validation Loss: 1.8169, Validation Accuracy: 0.8124

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [59/500], Loss: 0.0700, Accuracy: 0.9735
Validation Loss: 2.0356, Validation Accuracy: 0.8129

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [60/500], Loss: 0.0659, Accuracy: 0.9751
Validation Loss: 1.9588, Validation Accuracy: 0.8127

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [61/500], Loss: 0.0695, Accuracy: 0.9750
Validation Loss: 1.9341, Validation Accuracy: 0.8116

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [62/500], Loss: 0.0625, Accuracy: 0.9762
Validation Loss: 1.8239, Validation Accuracy: 0.8117

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [63/500], Loss: 0.0655, Accuracy: 0.9752
Validation Loss: 1.9099, Validation Accuracy: 0.8151

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [64/500], Loss: 0.0603, Accuracy: 0.9772
Validation Loss: 2.0602, Validation Accuracy: 0.8108

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [65/500], Loss: 0.0606, Accuracy: 0.9765
Validation Loss: 2.0093, Validation Accuracy: 0.8152

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [66/500], Loss: 0.0604, Accuracy: 0.9786
Validation Loss: 1.9796, Validation Accuracy: 0.8145

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [67/500], Loss: 0.0567, Accuracy: 0.9780
Validation Loss: 1.9578, Validation Accuracy: 0.8094

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [68/500], Loss: 0.0543, Accuracy: 0.9797
Validation Loss: 1.8577, Validation Accuracy: 0.8156

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [69/500], Loss: 0.0548, Accuracy: 0.9800
Validation Loss: 2.0296, Validation Accuracy: 0.8132

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [70/500], Loss: 0.0533, Accuracy: 0.9805
Validation Loss: 2.3841, Validation Accuracy: 0.8138

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [71/500], Loss: 0.0530, Accuracy: 0.9803
Validation Loss: 2.4753, Validation Accuracy: 0.8119

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [72/500], Loss: 0.0519, Accuracy: 0.9805
Validation Loss: 2.2773, Validation Accuracy: 0.8127

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [73/500], Loss: 0.0520, Accuracy: 0.9806
Validation Loss: 2.2107, Validation Accuracy: 0.8127

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [74/500], Loss: 0.0520, Accuracy: 0.9809
Validation Loss: 2.2482, Validation Accuracy: 0.8115

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [75/500], Loss: 0.0516, Accuracy: 0.9807
Validation Loss: 2.3011, Validation Accuracy: 0.8149

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [76/500], Loss: 0.0506, Accuracy: 0.9807
Validation Loss: 2.3532, Validation Accuracy: 0.8098

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [77/500], Loss: 0.0510, Accuracy: 0.9822
Validation Loss: 2.2717, Validation Accuracy: 0.8106

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [78/500], Loss: 0.0503, Accuracy: 0.9823
Validation Loss: 2.2841, Validation Accuracy: 0.8138

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [79/500], Loss: 0.0522, Accuracy: 0.9807
Validation Loss: 2.4281, Validation Accuracy: 0.8094

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [80/500], Loss: 0.0493, Accuracy: 0.9826
Validation Loss: 2.4199, Validation Accuracy: 0.8102

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [81/500], Loss: 0.0502, Accuracy: 0.9815
Validation Loss: 2.4596, Validation Accuracy: 0.8114

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [82/500], Loss: 0.0459, Accuracy: 0.9829
Validation Loss: 2.6160, Validation Accuracy: 0.8109

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [83/500], Loss: 0.0477, Accuracy: 0.9830
Validation Loss: 2.6494, Validation Accuracy: 0.8117

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [84/500], Loss: 0.0467, Accuracy: 0.9823
Validation Loss: 2.5509, Validation Accuracy: 0.8105

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [85/500], Loss: 0.0464, Accuracy: 0.9835
Validation Loss: 2.4789, Validation Accuracy: 0.8109

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [86/500], Loss: 0.0427, Accuracy: 0.9836
Validation Loss: 2.5257, Validation Accuracy: 0.8096

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [87/500], Loss: 0.0430, Accuracy: 0.9846
Validation Loss: 2.6717, Validation Accuracy: 0.8048

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [88/500], Loss: 0.0438, Accuracy: 0.9844
Validation Loss: 2.7229, Validation Accuracy: 0.8097

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [89/500], Loss: 0.0417, Accuracy: 0.9839
Validation Loss: 2.7029, Validation Accuracy: 0.8052

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [90/500], Loss: 0.0409, Accuracy: 0.9846
Validation Loss: 2.6358, Validation Accuracy: 0.8068

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [91/500], Loss: 0.0417, Accuracy: 0.9845
Validation Loss: 2.5869, Validation Accuracy: 0.8097

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [92/500], Loss: 0.0437, Accuracy: 0.9842
Validation Loss: 2.6351, Validation Accuracy: 0.8079

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [93/500], Loss: 0.0396, Accuracy: 0.9852
Validation Loss: 2.7330, Validation Accuracy: 0.8118

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [94/500], Loss: 0.0392, Accuracy: 0.9859
Validation Loss: 2.7792, Validation Accuracy: 0.8098

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [95/500], Loss: 0.0414, Accuracy: 0.9849
Validation Loss: 2.7812, Validation Accuracy: 0.8084

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [96/500], Loss: 0.0453, Accuracy: 0.9836
Validation Loss: 2.7114, Validation Accuracy: 0.8094

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [97/500], Loss: 0.0431, Accuracy: 0.9849
Validation Loss: 2.6826, Validation Accuracy: 0.8053

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [98/500], Loss: 0.0379, Accuracy: 0.9853
Validation Loss: 2.6406, Validation Accuracy: 0.8098

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [99/500], Loss: 0.0396, Accuracy: 0.9851
Validation Loss: 2.6963, Validation Accuracy: 0.8078

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [100/500], Loss: 0.0417, Accuracy: 0.9850
Validation Loss: 2.6881, Validation Accuracy: 0.8049

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [101/500], Loss: 0.0397, Accuracy: 0.9856
Validation Loss: 2.7456, Validation Accuracy: 0.8117

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [102/500], Loss: 0.0399, Accuracy: 0.9851
Validation Loss: 2.9587, Validation Accuracy: 0.8039

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [103/500], Loss: 0.0413, Accuracy: 0.9842
Validation Loss: 3.1020, Validation Accuracy: 0.8070

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [104/500], Loss: 0.0440, Accuracy: 0.9849
Validation Loss: 2.9670, Validation Accuracy: 0.8057

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [105/500], Loss: 0.0479, Accuracy: 0.9825
Validation Loss: 2.8116, Validation Accuracy: 0.8063

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [106/500], Loss: 0.0394, Accuracy: 0.9849
Validation Loss: 2.8234, Validation Accuracy: 0.8038

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [107/500], Loss: 0.0424, Accuracy: 0.9845
Validation Loss: 2.8860, Validation Accuracy: 0.8043

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [108/500], Loss: 0.0472, Accuracy: 0.9824
Validation Loss: 2.7996, Validation Accuracy: 0.8058

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [109/500], Loss: 0.0493, Accuracy: 0.9836
Validation Loss: 2.8035, Validation Accuracy: 0.8054

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [110/500], Loss: 0.0356, Accuracy: 0.9853
Validation Loss: 2.7409, Validation Accuracy: 0.8087

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [111/500], Loss: 0.0415, Accuracy: 0.9842
Validation Loss: 2.7715, Validation Accuracy: 0.8023

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [112/500], Loss: 0.0385, Accuracy: 0.9856
Validation Loss: 2.8514, Validation Accuracy: 0.7995

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [113/500], Loss: 0.0427, Accuracy: 0.9840
Validation Loss: 2.9811, Validation Accuracy: 0.8036

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [114/500], Loss: 0.0380, Accuracy: 0.9856
Validation Loss: 3.0544, Validation Accuracy: 0.8027

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [115/500], Loss: 0.0425, Accuracy: 0.9854
Validation Loss: 3.0413, Validation Accuracy: 0.8014

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [116/500], Loss: 0.0400, Accuracy: 0.9848
Validation Loss: 2.9625, Validation Accuracy: 0.8063

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [117/500], Loss: 0.0390, Accuracy: 0.9861
Validation Loss: 2.9195, Validation Accuracy: 0.8086

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [118/500], Loss: 0.0357, Accuracy: 0.9865
Validation Loss: 2.9168, Validation Accuracy: 0.8028

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [119/500], Loss: 0.0381, Accuracy: 0.9862
Validation Loss: 2.9334, Validation Accuracy: 0.8056

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [120/500], Loss: 0.0359, Accuracy: 0.9863
Validation Loss: 2.9377, Validation Accuracy: 0.8109

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [121/500], Loss: 0.0384, Accuracy: 0.9869
Validation Loss: 3.0044, Validation Accuracy: 0.8054

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [122/500], Loss: 0.0372, Accuracy: 0.9865
Validation Loss: 3.0505, Validation Accuracy: 0.8074

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [123/500], Loss: 0.0355, Accuracy: 0.9865
Validation Loss: 2.9447, Validation Accuracy: 0.8110

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [124/500], Loss: 0.0340, Accuracy: 0.9875
Validation Loss: 2.8321, Validation Accuracy: 0.8076

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [125/500], Loss: 0.0365, Accuracy: 0.9869
Validation Loss: 2.7659, Validation Accuracy: 0.8055

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [126/500], Loss: 0.0321, Accuracy: 0.9872
Validation Loss: 2.7300, Validation Accuracy: 0.8067

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [127/500], Loss: 0.0382, Accuracy: 0.9859
Validation Loss: 2.7543, Validation Accuracy: 0.8070

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [128/500], Loss: 0.0336, Accuracy: 0.9868
Validation Loss: 2.7968, Validation Accuracy: 0.8042

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [129/500], Loss: 0.0361, Accuracy: 0.9873
Validation Loss: 2.8520, Validation Accuracy: 0.8080

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [130/500], Loss: 0.0348, Accuracy: 0.9868
Validation Loss: 2.9525, Validation Accuracy: 0.8074

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [131/500], Loss: 0.0367, Accuracy: 0.9871
Validation Loss: 2.9148, Validation Accuracy: 0.8038

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [132/500], Loss: 0.0350, Accuracy: 0.9869
Validation Loss: 2.7015, Validation Accuracy: 0.8080

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [133/500], Loss: 0.0340, Accuracy: 0.9875
Validation Loss: 2.8202, Validation Accuracy: 0.8092

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [134/500], Loss: 0.0379, Accuracy: 0.9872
Validation Loss: 3.1293, Validation Accuracy: 0.8051

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [135/500], Loss: 0.0329, Accuracy: 0.9869
Validation Loss: 3.3921, Validation Accuracy: 0.8086

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [136/500], Loss: 0.0330, Accuracy: 0.9873
Validation Loss: 3.5143, Validation Accuracy: 0.8091

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [137/500], Loss: 0.0315, Accuracy: 0.9881
Validation Loss: 3.3925, Validation Accuracy: 0.8097

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [138/500], Loss: 0.0332, Accuracy: 0.9885
Validation Loss: 3.1595, Validation Accuracy: 0.8102

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [139/500], Loss: 0.0317, Accuracy: 0.9874
Validation Loss: 3.1915, Validation Accuracy: 0.8112

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [140/500], Loss: 0.0338, Accuracy: 0.9859
Validation Loss: 3.3989, Validation Accuracy: 0.8097

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [141/500], Loss: 0.0366, Accuracy: 0.9870
Validation Loss: 3.5266, Validation Accuracy: 0.8074

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [142/500], Loss: 0.0330, Accuracy: 0.9880
Validation Loss: 3.6701, Validation Accuracy: 0.8144

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [143/500], Loss: 0.0325, Accuracy: 0.9882
Validation Loss: 3.7299, Validation Accuracy: 0.8098

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [144/500], Loss: 0.0353, Accuracy: 0.9876
Validation Loss: 3.4884, Validation Accuracy: 0.8059

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [145/500], Loss: 0.0375, Accuracy: 0.9874
Validation Loss: 3.1568, Validation Accuracy: 0.8102

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [146/500], Loss: 0.0329, Accuracy: 0.9878
Validation Loss: 3.0553, Validation Accuracy: 0.8107

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [147/500], Loss: 0.0359, Accuracy: 0.9853
Validation Loss: 3.0497, Validation Accuracy: 0.8054

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [148/500], Loss: 0.0334, Accuracy: 0.9870
Validation Loss: 3.0062, Validation Accuracy: 0.8063

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [149/500], Loss: 0.0315, Accuracy: 0.9885
Validation Loss: 3.0077, Validation Accuracy: 0.8107

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [150/500], Loss: 0.0326, Accuracy: 0.9884
Validation Loss: 3.2167, Validation Accuracy: 0.8100

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [151/500], Loss: 0.0289, Accuracy: 0.9890
Validation Loss: 3.4350, Validation Accuracy: 0.8072

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [152/500], Loss: 0.0313, Accuracy: 0.9885
Validation Loss: 3.4256, Validation Accuracy: 0.8089

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [153/500], Loss: 0.0312, Accuracy: 0.9889
Validation Loss: 3.4192, Validation Accuracy: 0.8126

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [154/500], Loss: 0.0320, Accuracy: 0.9889
Validation Loss: 3.4119, Validation Accuracy: 0.8119

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [155/500], Loss: 0.0283, Accuracy: 0.9891
Validation Loss: 3.3346, Validation Accuracy: 0.8092

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [156/500], Loss: 0.0365, Accuracy: 0.9882
Validation Loss: 3.1966, Validation Accuracy: 0.8098

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [157/500], Loss: 0.0296, Accuracy: 0.9892
Validation Loss: 3.0752, Validation Accuracy: 0.8112

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [158/500], Loss: 0.0303, Accuracy: 0.9892
Validation Loss: 3.1156, Validation Accuracy: 0.8103

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [159/500], Loss: 0.0264, Accuracy: 0.9902
Validation Loss: 3.3607, Validation Accuracy: 0.8076

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [160/500], Loss: 0.0281, Accuracy: 0.9895
Validation Loss: 3.6680, Validation Accuracy: 0.8081

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [161/500], Loss: 0.0316, Accuracy: 0.9886
Validation Loss: 3.7104, Validation Accuracy: 0.8096

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [162/500], Loss: 0.0295, Accuracy: 0.9893
Validation Loss: 3.7020, Validation Accuracy: 0.8102

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [163/500], Loss: 0.0303, Accuracy: 0.9893
Validation Loss: 3.6484, Validation Accuracy: 0.8089

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [164/500], Loss: 0.0285, Accuracy: 0.9893
Validation Loss: 3.4506, Validation Accuracy: 0.8085

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [165/500], Loss: 0.0309, Accuracy: 0.9886
Validation Loss: 3.3077, Validation Accuracy: 0.8107

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [166/500], Loss: 0.0286, Accuracy: 0.9887
Validation Loss: 3.3516, Validation Accuracy: 0.8071

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [167/500], Loss: 0.0299, Accuracy: 0.9885
Validation Loss: 3.4648, Validation Accuracy: 0.8085

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [168/500], Loss: 0.0299, Accuracy: 0.9891
Validation Loss: 3.5477, Validation Accuracy: 0.8141

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [169/500], Loss: 0.0352, Accuracy: 0.9891
Validation Loss: 3.8128, Validation Accuracy: 0.8127

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [170/500], Loss: 0.0333, Accuracy: 0.9900
Validation Loss: 3.9763, Validation Accuracy: 0.8063

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [171/500], Loss: 0.0284, Accuracy: 0.9898
Validation Loss: 3.6603, Validation Accuracy: 0.8096

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [172/500], Loss: 0.0318, Accuracy: 0.9896
Validation Loss: 3.3275, Validation Accuracy: 0.8104

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [173/500], Loss: 0.0318, Accuracy: 0.9896
Validation Loss: 3.1482, Validation Accuracy: 0.8119

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [174/500], Loss: 0.0396, Accuracy: 0.9900
Validation Loss: 3.1931, Validation Accuracy: 0.8062

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [175/500], Loss: 0.0339, Accuracy: 0.9880
Validation Loss: 3.1451, Validation Accuracy: 0.8061

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [176/500], Loss: 0.0346, Accuracy: 0.9877
Validation Loss: 2.9657, Validation Accuracy: 0.8110

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [177/500], Loss: 0.0316, Accuracy: 0.9883
Validation Loss: 2.9435, Validation Accuracy: 0.8065

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [178/500], Loss: 0.0330, Accuracy: 0.9885
Validation Loss: 3.0404, Validation Accuracy: 0.8069

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [179/500], Loss: 0.0304, Accuracy: 0.9887
Validation Loss: 3.2357, Validation Accuracy: 0.8103

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [180/500], Loss: 0.0302, Accuracy: 0.9882
Validation Loss: 3.3990, Validation Accuracy: 0.8094

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [181/500], Loss: 0.0292, Accuracy: 0.9897
Validation Loss: 3.5655, Validation Accuracy: 0.8080

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [182/500], Loss: 0.0286, Accuracy: 0.9892
Validation Loss: 3.5332, Validation Accuracy: 0.8081

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [183/500], Loss: 0.0307, Accuracy: 0.9893
Validation Loss: 3.4336, Validation Accuracy: 0.8086

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [184/500], Loss: 0.0309, Accuracy: 0.9882
Validation Loss: 3.4057, Validation Accuracy: 0.8090

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [185/500], Loss: 0.0345, Accuracy: 0.9883
Validation Loss: 3.3344, Validation Accuracy: 0.8063

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [186/500], Loss: 0.0313, Accuracy: 0.9889
Validation Loss: 3.1259, Validation Accuracy: 0.8081

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [187/500], Loss: 0.0304, Accuracy: 0.9895
Validation Loss: 2.9946, Validation Accuracy: 0.8109

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [188/500], Loss: 0.0349, Accuracy: 0.9869
Validation Loss: 3.0354, Validation Accuracy: 0.8084

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [189/500], Loss: 0.0287, Accuracy: 0.9888
Validation Loss: 3.2288, Validation Accuracy: 0.8045

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [190/500], Loss: 0.0288, Accuracy: 0.9895
Validation Loss: 3.4705, Validation Accuracy: 0.8088

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [191/500], Loss: 0.0346, Accuracy: 0.9884
Validation Loss: 3.6611, Validation Accuracy: 0.8100

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [192/500], Loss: 0.0441, Accuracy: 0.9896
Validation Loss: 3.9066, Validation Accuracy: 0.8084

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [193/500], Loss: 0.0419, Accuracy: 0.9893
Validation Loss: 3.9849, Validation Accuracy: 0.8067

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [194/500], Loss: 0.0308, Accuracy: 0.9895
Validation Loss: 3.7041, Validation Accuracy: 0.8087

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [195/500], Loss: 0.0314, Accuracy: 0.9877
Validation Loss: 3.4277, Validation Accuracy: 0.8110

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [196/500], Loss: 0.0294, Accuracy: 0.9891
Validation Loss: 3.3130, Validation Accuracy: 0.8078

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [197/500], Loss: 0.0332, Accuracy: 0.9883
Validation Loss: 3.3885, Validation Accuracy: 0.8066

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [198/500], Loss: 0.0310, Accuracy: 0.9892
Validation Loss: 3.3921, Validation Accuracy: 0.8100

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [199/500], Loss: 0.0314, Accuracy: 0.9883
Validation Loss: 3.4154, Validation Accuracy: 0.8124

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [200/500], Loss: 0.0292, Accuracy: 0.9891
Validation Loss: 3.4865, Validation Accuracy: 0.8092

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [201/500], Loss: 0.0264, Accuracy: 0.9902
Validation Loss: 3.6059, Validation Accuracy: 0.8078

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [202/500], Loss: 0.0322, Accuracy: 0.9885
Validation Loss: 3.4607, Validation Accuracy: 0.8098

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [203/500], Loss: 0.0295, Accuracy: 0.9890
Validation Loss: 3.1110, Validation Accuracy: 0.8113

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [204/500], Loss: 0.0343, Accuracy: 0.9886
Validation Loss: 3.0158, Validation Accuracy: 0.8124

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [205/500], Loss: 0.0307, Accuracy: 0.9887
Validation Loss: 3.1743, Validation Accuracy: 0.8130

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [206/500], Loss: 0.0337, Accuracy: 0.9882
Validation Loss: 3.2547, Validation Accuracy: 0.8100

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [207/500], Loss: 0.0320, Accuracy: 0.9886
Validation Loss: 3.2155, Validation Accuracy: 0.8098

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [208/500], Loss: 0.0377, Accuracy: 0.9888
Validation Loss: 3.2491, Validation Accuracy: 0.8120

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [209/500], Loss: 0.0268, Accuracy: 0.9898
Validation Loss: 3.3440, Validation Accuracy: 0.8126

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [210/500], Loss: 0.0307, Accuracy: 0.9891
Validation Loss: 3.3561, Validation Accuracy: 0.8089

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [211/500], Loss: 0.0300, Accuracy: 0.9900
Validation Loss: 3.2808, Validation Accuracy: 0.8127

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [212/500], Loss: 0.0303, Accuracy: 0.9893
Validation Loss: 3.0394, Validation Accuracy: 0.8122

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [213/500], Loss: 0.0311, Accuracy: 0.9896
Validation Loss: 2.8930, Validation Accuracy: 0.8095

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [214/500], Loss: 0.0308, Accuracy: 0.9886
Validation Loss: 2.9215, Validation Accuracy: 0.8096

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [215/500], Loss: 0.0297, Accuracy: 0.9894
Validation Loss: 3.1306, Validation Accuracy: 0.8114

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [216/500], Loss: 0.0337, Accuracy: 0.9886
Validation Loss: 3.2414, Validation Accuracy: 0.8098

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [217/500], Loss: 0.0330, Accuracy: 0.9891
Validation Loss: 3.1267, Validation Accuracy: 0.8116

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [218/500], Loss: 0.0295, Accuracy: 0.9900
Validation Loss: 3.0112, Validation Accuracy: 0.8116

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [219/500], Loss: 0.0260, Accuracy: 0.9898
Validation Loss: 2.9970, Validation Accuracy: 0.8105

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [220/500], Loss: 0.0282, Accuracy: 0.9896
Validation Loss: 3.1109, Validation Accuracy: 0.8098

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [221/500], Loss: 0.0266, Accuracy: 0.9897
Validation Loss: 3.1981, Validation Accuracy: 0.8113

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [222/500], Loss: 0.0284, Accuracy: 0.9893
Validation Loss: 3.2059, Validation Accuracy: 0.8112

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [223/500], Loss: 0.0330, Accuracy: 0.9897
Validation Loss: 3.2414, Validation Accuracy: 0.8095

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [224/500], Loss: 0.0275, Accuracy: 0.9895
Validation Loss: 3.0805, Validation Accuracy: 0.8086

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [225/500], Loss: 0.0263, Accuracy: 0.9900
Validation Loss: 2.8075, Validation Accuracy: 0.8120

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [226/500], Loss: 0.0268, Accuracy: 0.9901
Validation Loss: 2.9849, Validation Accuracy: 0.8118

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [227/500], Loss: 0.0253, Accuracy: 0.9899
Validation Loss: 3.3002, Validation Accuracy: 0.8119

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [228/500], Loss: 0.0251, Accuracy: 0.9910
Validation Loss: 3.5005, Validation Accuracy: 0.8117

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [229/500], Loss: 0.0291, Accuracy: 0.9904
Validation Loss: 3.6896, Validation Accuracy: 0.8134

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [230/500], Loss: 0.0282, Accuracy: 0.9904
Validation Loss: 3.7971, Validation Accuracy: 0.8100

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [231/500], Loss: 0.0285, Accuracy: 0.9903
Validation Loss: 3.7864, Validation Accuracy: 0.8097

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [232/500], Loss: 0.0338, Accuracy: 0.9898
Validation Loss: 3.6332, Validation Accuracy: 0.8111

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [233/500], Loss: 0.0285, Accuracy: 0.9892
Validation Loss: 3.3942, Validation Accuracy: 0.8087

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [234/500], Loss: 0.0312, Accuracy: 0.9897
Validation Loss: 3.2073, Validation Accuracy: 0.8072

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [235/500], Loss: 0.0313, Accuracy: 0.9873
Validation Loss: 3.1365, Validation Accuracy: 0.8104

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [236/500], Loss: 0.0266, Accuracy: 0.9899
Validation Loss: 3.3954, Validation Accuracy: 0.8109

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [237/500], Loss: 0.0292, Accuracy: 0.9898
Validation Loss: 3.6041, Validation Accuracy: 0.8088

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [238/500], Loss: 0.0265, Accuracy: 0.9896
Validation Loss: 3.5912, Validation Accuracy: 0.8084

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [239/500], Loss: 0.0292, Accuracy: 0.9903
Validation Loss: 3.4222, Validation Accuracy: 0.8108

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [240/500], Loss: 0.0235, Accuracy: 0.9899
Validation Loss: 3.3604, Validation Accuracy: 0.8101

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [241/500], Loss: 0.0261, Accuracy: 0.9898
Validation Loss: 3.3848, Validation Accuracy: 0.8068

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [242/500], Loss: 0.0291, Accuracy: 0.9895
Validation Loss: 3.4211, Validation Accuracy: 0.8117

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [243/500], Loss: 0.0297, Accuracy: 0.9893
Validation Loss: 3.6744, Validation Accuracy: 0.8090

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [244/500], Loss: 0.0301, Accuracy: 0.9891
Validation Loss: 3.7173, Validation Accuracy: 0.8091

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [245/500], Loss: 0.0472, Accuracy: 0.9900
Validation Loss: 3.5952, Validation Accuracy: 0.8128

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [246/500], Loss: 0.0281, Accuracy: 0.9888
Validation Loss: 3.6559, Validation Accuracy: 0.8116

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [247/500], Loss: 0.0289, Accuracy: 0.9900
Validation Loss: 3.7272, Validation Accuracy: 0.8068

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [248/500], Loss: 0.0279, Accuracy: 0.9887
Validation Loss: 3.5677, Validation Accuracy: 0.8081

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [249/500], Loss: 0.0306, Accuracy: 0.9896
Validation Loss: 3.4452, Validation Accuracy: 0.8127

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [250/500], Loss: 0.0303, Accuracy: 0.9892
Validation Loss: 3.6959, Validation Accuracy: 0.8100

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [251/500], Loss: 0.0310, Accuracy: 0.9892
Validation Loss: 4.0031, Validation Accuracy: 0.8035

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [252/500], Loss: 0.0308, Accuracy: 0.9886
Validation Loss: 4.0141, Validation Accuracy: 0.8065

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [253/500], Loss: 0.0273, Accuracy: 0.9889
Validation Loss: 3.8337, Validation Accuracy: 0.8092

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [254/500], Loss: 0.0267, Accuracy: 0.9892
Validation Loss: 3.6791, Validation Accuracy: 0.8105

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [255/500], Loss: 0.0296, Accuracy: 0.9893
Validation Loss: 3.6805, Validation Accuracy: 0.8093

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [256/500], Loss: 0.0315, Accuracy: 0.9893
Validation Loss: 3.8229, Validation Accuracy: 0.8069

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [257/500], Loss: 0.0300, Accuracy: 0.9902
Validation Loss: 3.7407, Validation Accuracy: 0.8095

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [258/500], Loss: 0.0318, Accuracy: 0.9896
Validation Loss: 3.8818, Validation Accuracy: 0.8100

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [259/500], Loss: 0.0284, Accuracy: 0.9896
Validation Loss: 3.9315, Validation Accuracy: 0.8063

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [260/500], Loss: 0.0291, Accuracy: 0.9892
Validation Loss: 3.7076, Validation Accuracy: 0.8082

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [261/500], Loss: 0.0294, Accuracy: 0.9891
Validation Loss: 3.6602, Validation Accuracy: 0.8077

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [262/500], Loss: 0.0300, Accuracy: 0.9883
Validation Loss: 3.9235, Validation Accuracy: 0.8058

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [263/500], Loss: 0.0310, Accuracy: 0.9893
Validation Loss: 3.7899, Validation Accuracy: 0.8082

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [264/500], Loss: 0.0280, Accuracy: 0.9891
Validation Loss: 3.5400, Validation Accuracy: 0.8095

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [265/500], Loss: 0.0340, Accuracy: 0.9889
Validation Loss: 3.5009, Validation Accuracy: 0.8056

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [266/500], Loss: 0.0360, Accuracy: 0.9893
Validation Loss: 3.6563, Validation Accuracy: 0.8082

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [267/500], Loss: 0.0289, Accuracy: 0.9888
Validation Loss: 3.8582, Validation Accuracy: 0.8076

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [268/500], Loss: 0.0280, Accuracy: 0.9897
Validation Loss: 4.1514, Validation Accuracy: 0.8066

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [269/500], Loss: 0.0306, Accuracy: 0.9889
Validation Loss: 4.2826, Validation Accuracy: 0.8072

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [270/500], Loss: 0.0303, Accuracy: 0.9896
Validation Loss: 4.2659, Validation Accuracy: 0.8104

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [271/500], Loss: 0.0313, Accuracy: 0.9883
Validation Loss: 4.3338, Validation Accuracy: 0.8109

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [272/500], Loss: 0.0320, Accuracy: 0.9892
Validation Loss: 4.3518, Validation Accuracy: 0.8073

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [273/500], Loss: 0.0304, Accuracy: 0.9887
Validation Loss: 4.1481, Validation Accuracy: 0.8038

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [274/500], Loss: 0.0327, Accuracy: 0.9893
Validation Loss: 4.0288, Validation Accuracy: 0.8090

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [275/500], Loss: 0.0324, Accuracy: 0.9900
Validation Loss: 4.3507, Validation Accuracy: 0.8070

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [276/500], Loss: 0.0314, Accuracy: 0.9887
Validation Loss: 4.5310, Validation Accuracy: 0.8072

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [277/500], Loss: 0.0264, Accuracy: 0.9902
Validation Loss: 4.4317, Validation Accuracy: 0.8100

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [278/500], Loss: 0.0331, Accuracy: 0.9889
Validation Loss: 4.3896, Validation Accuracy: 0.8085

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [279/500], Loss: 0.0322, Accuracy: 0.9896
Validation Loss: 4.2795, Validation Accuracy: 0.8051

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [280/500], Loss: 0.0304, Accuracy: 0.9895
Validation Loss: 3.9647, Validation Accuracy: 0.8097

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [281/500], Loss: 0.0583, Accuracy: 0.9894
Validation Loss: 3.7932, Validation Accuracy: 0.8070

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [282/500], Loss: 0.0338, Accuracy: 0.9881
Validation Loss: 3.9614, Validation Accuracy: 0.8081

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [283/500], Loss: 0.0352, Accuracy: 0.9874
Validation Loss: 4.4497, Validation Accuracy: 0.8117

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [284/500], Loss: 0.0342, Accuracy: 0.9875
Validation Loss: 4.8201, Validation Accuracy: 0.8060

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [285/500], Loss: 0.0317, Accuracy: 0.9887
Validation Loss: 4.7313, Validation Accuracy: 0.8062

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [286/500], Loss: 0.0360, Accuracy: 0.9889
Validation Loss: 4.6897, Validation Accuracy: 0.8114

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [287/500], Loss: 0.0353, Accuracy: 0.9879
Validation Loss: 4.8133, Validation Accuracy: 0.8114

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [288/500], Loss: 0.0387, Accuracy: 0.9883
Validation Loss: 5.0477, Validation Accuracy: 0.8073

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [289/500], Loss: 0.0560, Accuracy: 0.9897
Validation Loss: 5.2672, Validation Accuracy: 0.8079

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [290/500], Loss: 0.0346, Accuracy: 0.9886
Validation Loss: 5.1601, Validation Accuracy: 0.8105

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [291/500], Loss: 0.0413, Accuracy: 0.9878
Validation Loss: 5.0888, Validation Accuracy: 0.8088

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [292/500], Loss: 0.0333, Accuracy: 0.9883
Validation Loss: 4.9407, Validation Accuracy: 0.8065

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [293/500], Loss: 0.0356, Accuracy: 0.9883
Validation Loss: 4.9212, Validation Accuracy: 0.8066

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [294/500], Loss: 0.0375, Accuracy: 0.9876
Validation Loss: 5.1878, Validation Accuracy: 0.8132

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [295/500], Loss: 0.0362, Accuracy: 0.9888
Validation Loss: 5.6383, Validation Accuracy: 0.8070

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [296/500], Loss: 0.0388, Accuracy: 0.9873
Validation Loss: 5.7302, Validation Accuracy: 0.8077

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [297/500], Loss: 0.0646, Accuracy: 0.9876
Validation Loss: 5.6142, Validation Accuracy: 0.8139

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [298/500], Loss: 0.0330, Accuracy: 0.9882
Validation Loss: 5.1807, Validation Accuracy: 0.8081

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [299/500], Loss: 0.0376, Accuracy: 0.9876
Validation Loss: 4.8586, Validation Accuracy: 0.8104

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [300/500], Loss: 0.0417, Accuracy: 0.9868
Validation Loss: 4.8918, Validation Accuracy: 0.8094

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [301/500], Loss: 0.0347, Accuracy: 0.9890
Validation Loss: 4.9293, Validation Accuracy: 0.8090

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [302/500], Loss: 0.0342, Accuracy: 0.9874
Validation Loss: 4.7516, Validation Accuracy: 0.8138

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [303/500], Loss: 0.0367, Accuracy: 0.9885
Validation Loss: 4.6403, Validation Accuracy: 0.8080

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [304/500], Loss: 0.0348, Accuracy: 0.9887
Validation Loss: 4.7190, Validation Accuracy: 0.8103

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [305/500], Loss: 0.0378, Accuracy: 0.9879
Validation Loss: 4.8128, Validation Accuracy: 0.8130

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [306/500], Loss: 0.0364, Accuracy: 0.9886
Validation Loss: 4.7908, Validation Accuracy: 0.8095

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [307/500], Loss: 0.0352, Accuracy: 0.9877
Validation Loss: 4.7344, Validation Accuracy: 0.8098

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [308/500], Loss: 0.0334, Accuracy: 0.9883
Validation Loss: 4.4566, Validation Accuracy: 0.8119

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [309/500], Loss: 0.0377, Accuracy: 0.9875
Validation Loss: 4.1494, Validation Accuracy: 0.8071

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [310/500], Loss: 0.0366, Accuracy: 0.9875
Validation Loss: 4.1411, Validation Accuracy: 0.8090

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [311/500], Loss: 0.0330, Accuracy: 0.9883
Validation Loss: 4.6758, Validation Accuracy: 0.8079

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [312/500], Loss: 0.0532, Accuracy: 0.9874
Validation Loss: 4.8554, Validation Accuracy: 0.8070

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [313/500], Loss: 0.0384, Accuracy: 0.9868
Validation Loss: 4.8528, Validation Accuracy: 0.8088

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [314/500], Loss: 0.0563, Accuracy: 0.9879
Validation Loss: 4.6267, Validation Accuracy: 0.8072

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [315/500], Loss: 0.0391, Accuracy: 0.9877
Validation Loss: 4.4310, Validation Accuracy: 0.8062

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [316/500], Loss: 0.0422, Accuracy: 0.9862
Validation Loss: 4.2281, Validation Accuracy: 0.8118

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [317/500], Loss: 0.0376, Accuracy: 0.9859
Validation Loss: 4.2276, Validation Accuracy: 0.8096

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [318/500], Loss: 0.0470, Accuracy: 0.9864
Validation Loss: 4.3305, Validation Accuracy: 0.8074

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [319/500], Loss: 0.0426, Accuracy: 0.9877
Validation Loss: 4.4344, Validation Accuracy: 0.8110

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [320/500], Loss: 0.0464, Accuracy: 0.9851
Validation Loss: 4.5561, Validation Accuracy: 0.8087

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [321/500], Loss: 0.0395, Accuracy: 0.9863
Validation Loss: 4.7872, Validation Accuracy: 0.8090

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [322/500], Loss: 0.0438, Accuracy: 0.9869
Validation Loss: 5.1232, Validation Accuracy: 0.8110

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [323/500], Loss: 0.0476, Accuracy: 0.9863
Validation Loss: 5.0826, Validation Accuracy: 0.8121

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [324/500], Loss: 0.0423, Accuracy: 0.9878
Validation Loss: 4.9768, Validation Accuracy: 0.8090

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [325/500], Loss: 0.0398, Accuracy: 0.9861
Validation Loss: 5.0575, Validation Accuracy: 0.8019

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [326/500], Loss: 0.0400, Accuracy: 0.9861
Validation Loss: 4.9644, Validation Accuracy: 0.8080

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [327/500], Loss: 0.0400, Accuracy: 0.9865
Validation Loss: 4.8075, Validation Accuracy: 0.8095

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [328/500], Loss: 0.0392, Accuracy: 0.9842
Validation Loss: 4.8731, Validation Accuracy: 0.8112

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [329/500], Loss: 0.0489, Accuracy: 0.9858
Validation Loss: 5.1903, Validation Accuracy: 0.8058

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [330/500], Loss: 0.0436, Accuracy: 0.9862
Validation Loss: 5.3766, Validation Accuracy: 0.8065

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [331/500], Loss: 0.0416, Accuracy: 0.9870
Validation Loss: 5.3390, Validation Accuracy: 0.8075

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [332/500], Loss: 0.0386, Accuracy: 0.9869
Validation Loss: 5.1667, Validation Accuracy: 0.8074

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [333/500], Loss: 0.0418, Accuracy: 0.9877
Validation Loss: 5.1573, Validation Accuracy: 0.8104

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [334/500], Loss: 0.0406, Accuracy: 0.9874
Validation Loss: 5.1458, Validation Accuracy: 0.8088

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [335/500], Loss: 0.0415, Accuracy: 0.9869
Validation Loss: 5.2973, Validation Accuracy: 0.8104

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [336/500], Loss: 0.0351, Accuracy: 0.9882
Validation Loss: 5.3577, Validation Accuracy: 0.8099

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [337/500], Loss: 0.0400, Accuracy: 0.9883
Validation Loss: 5.3581, Validation Accuracy: 0.8067

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [338/500], Loss: 0.0395, Accuracy: 0.9860
Validation Loss: 5.3992, Validation Accuracy: 0.8046

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [339/500], Loss: 0.0490, Accuracy: 0.9833
Validation Loss: 5.3038, Validation Accuracy: 0.8048

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [340/500], Loss: 0.0373, Accuracy: 0.9877
Validation Loss: 5.4967, Validation Accuracy: 0.8059

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [341/500], Loss: 0.0387, Accuracy: 0.9875
Validation Loss: 5.7605, Validation Accuracy: 0.8067

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [342/500], Loss: 0.0412, Accuracy: 0.9873
Validation Loss: 5.6777, Validation Accuracy: 0.8070

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [343/500], Loss: 0.0597, Accuracy: 0.9874
Validation Loss: 5.2958, Validation Accuracy: 0.8061

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [344/500], Loss: 0.0490, Accuracy: 0.9864
Validation Loss: 5.1450, Validation Accuracy: 0.8077

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [345/500], Loss: 0.0424, Accuracy: 0.9880
Validation Loss: 5.0762, Validation Accuracy: 0.8086

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [346/500], Loss: 0.0467, Accuracy: 0.9870
Validation Loss: 4.6282, Validation Accuracy: 0.8073

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [347/500], Loss: 0.0392, Accuracy: 0.9869
Validation Loss: 4.2808, Validation Accuracy: 0.8079

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [348/500], Loss: 0.0452, Accuracy: 0.9875
Validation Loss: 4.4177, Validation Accuracy: 0.8097

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [349/500], Loss: 0.0429, Accuracy: 0.9864
Validation Loss: 4.5098, Validation Accuracy: 0.8083

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [350/500], Loss: 0.0521, Accuracy: 0.9867
Validation Loss: 4.3154, Validation Accuracy: 0.8075

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [351/500], Loss: 0.0465, Accuracy: 0.9865
Validation Loss: 4.0244, Validation Accuracy: 0.8038

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [352/500], Loss: 0.0576, Accuracy: 0.9825
Validation Loss: 3.6446, Validation Accuracy: 0.8031

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [353/500], Loss: 0.0529, Accuracy: 0.9845
Validation Loss: 3.2521, Validation Accuracy: 0.8038

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [354/500], Loss: 0.0505, Accuracy: 0.9843
Validation Loss: 3.4748, Validation Accuracy: 0.8030

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [355/500], Loss: 0.0752, Accuracy: 0.9844
Validation Loss: 3.8454, Validation Accuracy: 0.8037

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [356/500], Loss: 0.0486, Accuracy: 0.9839
Validation Loss: 4.1023, Validation Accuracy: 0.8040

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [357/500], Loss: 0.0580, Accuracy: 0.9860
Validation Loss: 4.1140, Validation Accuracy: 0.8059

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [358/500], Loss: 0.0523, Accuracy: 0.9843
Validation Loss: 3.7421, Validation Accuracy: 0.8049

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [359/500], Loss: 0.0720, Accuracy: 0.9838
Validation Loss: 3.4416, Validation Accuracy: 0.8033

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [360/500], Loss: 0.0623, Accuracy: 0.9807
Validation Loss: 3.5207, Validation Accuracy: 0.8015

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [361/500], Loss: 0.0547, Accuracy: 0.9833
Validation Loss: 3.3817, Validation Accuracy: 0.8015

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [362/500], Loss: 0.0561, Accuracy: 0.9837
Validation Loss: 3.2705, Validation Accuracy: 0.8018

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [363/500], Loss: 0.0575, Accuracy: 0.9822
Validation Loss: 3.3021, Validation Accuracy: 0.8013

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [364/500], Loss: 0.0595, Accuracy: 0.9806
Validation Loss: 3.2452, Validation Accuracy: 0.8018

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [365/500], Loss: 0.0594, Accuracy: 0.9819
Validation Loss: 2.9700, Validation Accuracy: 0.8008

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [366/500], Loss: 0.0583, Accuracy: 0.9815
Validation Loss: 2.6767, Validation Accuracy: 0.8002

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [367/500], Loss: 0.0545, Accuracy: 0.9817
Validation Loss: 3.0372, Validation Accuracy: 0.7996

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [368/500], Loss: 0.0524, Accuracy: 0.9830
Validation Loss: 3.4982, Validation Accuracy: 0.8003

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [369/500], Loss: 0.0580, Accuracy: 0.9814
Validation Loss: 3.6917, Validation Accuracy: 0.8019

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [370/500], Loss: 0.0549, Accuracy: 0.9817
Validation Loss: 3.5704, Validation Accuracy: 0.8037

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [371/500], Loss: 0.0613, Accuracy: 0.9839
Validation Loss: 3.3020, Validation Accuracy: 0.8060

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [372/500], Loss: 0.0584, Accuracy: 0.9829
Validation Loss: 2.6176, Validation Accuracy: 0.8066

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [373/500], Loss: 0.0547, Accuracy: 0.9827
Validation Loss: 2.6148, Validation Accuracy: 0.8065

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [374/500], Loss: 0.0561, Accuracy: 0.9825
Validation Loss: 2.9470, Validation Accuracy: 0.8068

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [375/500], Loss: 0.0503, Accuracy: 0.9839
Validation Loss: 2.8535, Validation Accuracy: 0.8067

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [376/500], Loss: 0.0513, Accuracy: 0.9833
Validation Loss: 2.7511, Validation Accuracy: 0.8058

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [377/500], Loss: 0.0621, Accuracy: 0.9842
Validation Loss: 3.2332, Validation Accuracy: 0.8079

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [378/500], Loss: 0.0469, Accuracy: 0.9848
Validation Loss: 3.7350, Validation Accuracy: 0.8086

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [379/500], Loss: 0.0513, Accuracy: 0.9839
Validation Loss: 3.6060, Validation Accuracy: 0.8098

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [380/500], Loss: 0.0529, Accuracy: 0.9833
Validation Loss: 3.1152, Validation Accuracy: 0.8080

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [381/500], Loss: 0.0661, Accuracy: 0.9832
Validation Loss: 2.7321, Validation Accuracy: 0.8063

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [382/500], Loss: 0.0522, Accuracy: 0.9838
Validation Loss: 2.8428, Validation Accuracy: 0.8061

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [383/500], Loss: 0.0522, Accuracy: 0.9835
Validation Loss: 3.1552, Validation Accuracy: 0.8077

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [384/500], Loss: 0.0524, Accuracy: 0.9830
Validation Loss: 3.4228, Validation Accuracy: 0.8080

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [385/500], Loss: 0.0526, Accuracy: 0.9816
Validation Loss: 3.4378, Validation Accuracy: 0.8050

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [386/500], Loss: 0.0517, Accuracy: 0.9816
Validation Loss: 3.3331, Validation Accuracy: 0.8065

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [387/500], Loss: 0.0544, Accuracy: 0.9847
Validation Loss: 3.1714, Validation Accuracy: 0.8071

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [388/500], Loss: 0.0626, Accuracy: 0.9847
Validation Loss: 3.0403, Validation Accuracy: 0.8082

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [389/500], Loss: 0.0484, Accuracy: 0.9846
Validation Loss: 2.9713, Validation Accuracy: 0.8060

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [390/500], Loss: 0.0647, Accuracy: 0.9843
Validation Loss: 3.0444, Validation Accuracy: 0.8042

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [391/500], Loss: 0.0530, Accuracy: 0.9830
Validation Loss: 2.9838, Validation Accuracy: 0.8056

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [392/500], Loss: 0.0541, Accuracy: 0.9813
Validation Loss: 3.2479, Validation Accuracy: 0.8074

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [393/500], Loss: 0.0565, Accuracy: 0.9830
Validation Loss: 3.4359, Validation Accuracy: 0.8054

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [394/500], Loss: 0.0663, Accuracy: 0.9826
Validation Loss: 3.0654, Validation Accuracy: 0.8048

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [395/500], Loss: 0.0612, Accuracy: 0.9820
Validation Loss: 3.1428, Validation Accuracy: 0.8072

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [396/500], Loss: 0.0568, Accuracy: 0.9824
Validation Loss: 2.8768, Validation Accuracy: 0.8073

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [397/500], Loss: 0.0588, Accuracy: 0.9805
Validation Loss: 2.8161, Validation Accuracy: 0.8087

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [398/500], Loss: 0.0669, Accuracy: 0.9806
Validation Loss: 2.8505, Validation Accuracy: 0.8057

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [399/500], Loss: 0.0629, Accuracy: 0.9808
Validation Loss: 3.1238, Validation Accuracy: 0.8042

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [400/500], Loss: 0.0568, Accuracy: 0.9812
Validation Loss: 2.8942, Validation Accuracy: 0.8036

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [401/500], Loss: 0.2066, Accuracy: 0.9820
Validation Loss: 3.3262, Validation Accuracy: 0.8045

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [402/500], Loss: 0.0637, Accuracy: 0.9778
Validation Loss: 3.5990, Validation Accuracy: 0.7962

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [403/500], Loss: 0.0795, Accuracy: 0.9741
Validation Loss: 3.4152, Validation Accuracy: 0.7950

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [404/500], Loss: 0.0838, Accuracy: 0.9736
Validation Loss: 3.5431, Validation Accuracy: 0.7946

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [405/500], Loss: 0.0977, Accuracy: 0.9691
Validation Loss: 3.7054, Validation Accuracy: 0.7955

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [406/500], Loss: 0.1314, Accuracy: 0.9660
Validation Loss: 3.5186, Validation Accuracy: 0.7926

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [407/500], Loss: 0.1039, Accuracy: 0.9660
Validation Loss: 3.1600, Validation Accuracy: 0.7912

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [408/500], Loss: 0.1038, Accuracy: 0.9643
Validation Loss: 3.3290, Validation Accuracy: 0.7918

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [409/500], Loss: 0.0981, Accuracy: 0.9684
Validation Loss: 3.8181, Validation Accuracy: 0.7949

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [410/500], Loss: 0.1019, Accuracy: 0.9702
Validation Loss: 3.5163, Validation Accuracy: 0.7983

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [411/500], Loss: 0.1031, Accuracy: 0.9701
Validation Loss: 3.2220, Validation Accuracy: 0.7965

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [412/500], Loss: 0.0977, Accuracy: 0.9701
Validation Loss: 2.8743, Validation Accuracy: 0.7984

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [413/500], Loss: 0.1005, Accuracy: 0.9700
Validation Loss: 2.9211, Validation Accuracy: 0.7915

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [414/500], Loss: 0.0995, Accuracy: 0.9727
Validation Loss: 3.4073, Validation Accuracy: 0.8013

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [415/500], Loss: 0.0975, Accuracy: 0.9742
Validation Loss: 3.6151, Validation Accuracy: 0.8011

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [416/500], Loss: 0.0954, Accuracy: 0.9727
Validation Loss: 3.4964, Validation Accuracy: 0.7999

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [417/500], Loss: 0.1474, Accuracy: 0.9705
Validation Loss: 3.4283, Validation Accuracy: 0.7991

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [418/500], Loss: 0.0904, Accuracy: 0.9711
Validation Loss: 3.2950, Validation Accuracy: 0.7960

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [419/500], Loss: 0.0930, Accuracy: 0.9674
Validation Loss: 3.0205, Validation Accuracy: 0.7978

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [420/500], Loss: 0.0975, Accuracy: 0.9701
Validation Loss: 2.9916, Validation Accuracy: 0.8011

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [421/500], Loss: 0.0999, Accuracy: 0.9682
Validation Loss: 3.2671, Validation Accuracy: 0.8021

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [422/500], Loss: 0.1021, Accuracy: 0.9724
Epoch 00422: reducing learning rate of group 0 to 1.0000e-06.
Validation Loss: 3.7719, Validation Accuracy: 0.8033

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [423/500], Loss: 0.1035, Accuracy: 0.9714
Validation Loss: 3.7003, Validation Accuracy: 0.8032

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [424/500], Loss: 0.1001, Accuracy: 0.9711
Validation Loss: 3.6133, Validation Accuracy: 0.8021

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [425/500], Loss: 0.0941, Accuracy: 0.9715
Validation Loss: 3.5220, Validation Accuracy: 0.8013

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [426/500], Loss: 0.0918, Accuracy: 0.9709
Validation Loss: 3.4410, Validation Accuracy: 0.8008

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [427/500], Loss: 0.0864, Accuracy: 0.9713
Validation Loss: 3.3609, Validation Accuracy: 0.8010

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [428/500], Loss: 0.0896, Accuracy: 0.9704
Validation Loss: 3.2778, Validation Accuracy: 0.8000

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [429/500], Loss: 0.0899, Accuracy: 0.9709
Validation Loss: 3.1909, Validation Accuracy: 0.7983

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [430/500], Loss: 0.0808, Accuracy: 0.9717
Validation Loss: 3.1265, Validation Accuracy: 0.7968

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [431/500], Loss: 0.0861, Accuracy: 0.9702
Validation Loss: 3.0381, Validation Accuracy: 0.7968

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [432/500], Loss: 0.0875, Accuracy: 0.9701
Validation Loss: 2.9850, Validation Accuracy: 0.7960

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [433/500], Loss: 0.0854, Accuracy: 0.9706
Validation Loss: 2.9646, Validation Accuracy: 0.7960

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [434/500], Loss: 0.0862, Accuracy: 0.9697
Validation Loss: 2.9362, Validation Accuracy: 0.7966

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [435/500], Loss: 0.0904, Accuracy: 0.9700
Validation Loss: 2.9417, Validation Accuracy: 0.7974

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [436/500], Loss: 0.0838, Accuracy: 0.9721
Validation Loss: 2.9683, Validation Accuracy: 0.7982

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [437/500], Loss: 0.0838, Accuracy: 0.9726
Validation Loss: 3.0011, Validation Accuracy: 0.8002

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [438/500], Loss: 0.0844, Accuracy: 0.9734
Validation Loss: 3.0297, Validation Accuracy: 0.8016

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [439/500], Loss: 0.0807, Accuracy: 0.9744
Validation Loss: 3.0526, Validation Accuracy: 0.8020

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [440/500], Loss: 0.0825, Accuracy: 0.9739
Validation Loss: 3.0825, Validation Accuracy: 0.8030

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [441/500], Loss: 0.0792, Accuracy: 0.9742
Validation Loss: 3.0914, Validation Accuracy: 0.8036

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [442/500], Loss: 0.0829, Accuracy: 0.9744
Validation Loss: 3.0925, Validation Accuracy: 0.8039

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [443/500], Loss: 0.0798, Accuracy: 0.9727
Validation Loss: 3.0901, Validation Accuracy: 0.8046

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [444/500], Loss: 0.0814, Accuracy: 0.9736
Validation Loss: 3.1126, Validation Accuracy: 0.8034

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [445/500], Loss: 0.0808, Accuracy: 0.9745
Validation Loss: 3.0988, Validation Accuracy: 0.8043

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [446/500], Loss: 0.0767, Accuracy: 0.9730
Validation Loss: 3.1055, Validation Accuracy: 0.8045

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [447/500], Loss: 0.0783, Accuracy: 0.9741
Validation Loss: 3.0817, Validation Accuracy: 0.8045

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [448/500], Loss: 0.0745, Accuracy: 0.9756
Validation Loss: 3.0386, Validation Accuracy: 0.8033

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [449/500], Loss: 0.0790, Accuracy: 0.9748
Validation Loss: 2.9823, Validation Accuracy: 0.8029

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [450/500], Loss: 0.0830, Accuracy: 0.9736
Validation Loss: 2.9120, Validation Accuracy: 0.8006

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [451/500], Loss: 0.0763, Accuracy: 0.9737
Validation Loss: 2.8403, Validation Accuracy: 0.7998

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [452/500], Loss: 0.0790, Accuracy: 0.9727
Validation Loss: 2.8067, Validation Accuracy: 0.8020

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [453/500], Loss: 0.0739, Accuracy: 0.9745
Validation Loss: 2.7583, Validation Accuracy: 0.8036

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [454/500], Loss: 0.0726, Accuracy: 0.9757
Validation Loss: 2.7245, Validation Accuracy: 0.8043

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [455/500], Loss: 0.0836, Accuracy: 0.9748
Validation Loss: 2.7266, Validation Accuracy: 0.8053

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [456/500], Loss: 0.0796, Accuracy: 0.9727
Validation Loss: 2.7366, Validation Accuracy: 0.8046

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [457/500], Loss: 0.0723, Accuracy: 0.9751
Validation Loss: 2.7607, Validation Accuracy: 0.8058

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [458/500], Loss: 0.0728, Accuracy: 0.9756
Validation Loss: 2.7736, Validation Accuracy: 0.8068

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [459/500], Loss: 0.1015, Accuracy: 0.9764
Validation Loss: 2.7857, Validation Accuracy: 0.8064

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [460/500], Loss: 0.0713, Accuracy: 0.9767
Validation Loss: 2.8005, Validation Accuracy: 0.8072

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [461/500], Loss: 0.0726, Accuracy: 0.9744
Validation Loss: 2.8167, Validation Accuracy: 0.8069

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [462/500], Loss: 0.0727, Accuracy: 0.9750
Validation Loss: 2.8409, Validation Accuracy: 0.8063

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [463/500], Loss: 0.0724, Accuracy: 0.9757
Validation Loss: 2.8677, Validation Accuracy: 0.8060

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [464/500], Loss: 0.0743, Accuracy: 0.9746
Validation Loss: 2.8737, Validation Accuracy: 0.8067

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [465/500], Loss: 0.0705, Accuracy: 0.9758
Validation Loss: 2.8594, Validation Accuracy: 0.8072

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [466/500], Loss: 0.0742, Accuracy: 0.9773
Validation Loss: 2.8124, Validation Accuracy: 0.8083

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [467/500], Loss: 0.0693, Accuracy: 0.9767
Validation Loss: 2.7452, Validation Accuracy: 0.8085

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [468/500], Loss: 0.0708, Accuracy: 0.9766
Validation Loss: 2.6650, Validation Accuracy: 0.8091

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [469/500], Loss: 0.0670, Accuracy: 0.9757
Validation Loss: 2.5973, Validation Accuracy: 0.8077

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [470/500], Loss: 0.0680, Accuracy: 0.9753
Validation Loss: 2.5663, Validation Accuracy: 0.8098

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [471/500], Loss: 0.0674, Accuracy: 0.9774
Validation Loss: 2.5804, Validation Accuracy: 0.8086

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [472/500], Loss: 0.0665, Accuracy: 0.9778
Validation Loss: 2.6002, Validation Accuracy: 0.8085

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [473/500], Loss: 0.0703, Accuracy: 0.9775
Validation Loss: 2.6227, Validation Accuracy: 0.8084

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [474/500], Loss: 0.0685, Accuracy: 0.9777
Validation Loss: 2.6240, Validation Accuracy: 0.8087

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [475/500], Loss: 0.0656, Accuracy: 0.9779
Validation Loss: 2.6310, Validation Accuracy: 0.8088

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [476/500], Loss: 0.0677, Accuracy: 0.9772
Validation Loss: 2.6252, Validation Accuracy: 0.8083

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [477/500], Loss: 0.0688, Accuracy: 0.9780
Validation Loss: 2.6428, Validation Accuracy: 0.8086

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [478/500], Loss: 0.0715, Accuracy: 0.9786
Validation Loss: 2.6500, Validation Accuracy: 0.8098

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [479/500], Loss: 0.0606, Accuracy: 0.9788
Validation Loss: 2.6681, Validation Accuracy: 0.8087

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [480/500], Loss: 0.0667, Accuracy: 0.9775
Validation Loss: 2.6610, Validation Accuracy: 0.8087

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [481/500], Loss: 0.0632, Accuracy: 0.9797
Validation Loss: 2.6337, Validation Accuracy: 0.8080

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [482/500], Loss: 0.0647, Accuracy: 0.9794
Validation Loss: 2.6023, Validation Accuracy: 0.8079

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [483/500], Loss: 0.0662, Accuracy: 0.9784
Validation Loss: 2.5561, Validation Accuracy: 0.8093

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [484/500], Loss: 0.0615, Accuracy: 0.9789
Validation Loss: 2.5174, Validation Accuracy: 0.8093

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [485/500], Loss: 0.0700, Accuracy: 0.9759
Validation Loss: 2.5349, Validation Accuracy: 0.8099

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [486/500], Loss: 0.0637, Accuracy: 0.9781
Validation Loss: 2.5495, Validation Accuracy: 0.8083

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [487/500], Loss: 0.0663, Accuracy: 0.9788
Validation Loss: 2.5809, Validation Accuracy: 0.8090

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [488/500], Loss: 0.0624, Accuracy: 0.9786
Validation Loss: 2.6552, Validation Accuracy: 0.8085

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [489/500], Loss: 0.0645, Accuracy: 0.9788
Validation Loss: 2.6495, Validation Accuracy: 0.8088

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [490/500], Loss: 0.0657, Accuracy: 0.9780
Validation Loss: 2.6328, Validation Accuracy: 0.8094

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [491/500], Loss: 0.0641, Accuracy: 0.9783
Validation Loss: 2.5758, Validation Accuracy: 0.8095

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [492/500], Loss: 0.0627, Accuracy: 0.9792
Validation Loss: 2.5142, Validation Accuracy: 0.8094

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [493/500], Loss: 0.0756, Accuracy: 0.9793
Validation Loss: 2.4608, Validation Accuracy: 0.8102

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [494/500], Loss: 0.0611, Accuracy: 0.9794
Validation Loss: 2.4308, Validation Accuracy: 0.8101

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [495/500], Loss: 0.0618, Accuracy: 0.9791
Validation Loss: 2.4354, Validation Accuracy: 0.8108

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [496/500], Loss: 0.0596, Accuracy: 0.9797
Validation Loss: 2.4757, Validation Accuracy: 0.8103

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [497/500], Loss: 0.0630, Accuracy: 0.9786
Validation Loss: 2.5323, Validation Accuracy: 0.8102

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [498/500], Loss: 0.0601, Accuracy: 0.9795
Validation Loss: 2.5787, Validation Accuracy: 0.8100

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [499/500], Loss: 0.0604, Accuracy: 0.9789
Validation Loss: 2.6440, Validation Accuracy: 0.8100

C:\Users\FSM\AppData\Local\Temp\ipykernel_51976\2221030542.py:8: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_X, batch_y, batch_X_repo, idx in tqdm.tqdm_notebook(loader):

  0%|          | 0/252 [00:00<?, ?it/s]

Epoch [500/500], Loss: 0.0860, Accuracy: 0.9794
Validation Loss: 2.6843, Validation Accuracy: 0.8092

:

In [ ]:
# Save best model to file
model.load_state_dict(best_model)
torch.save(model.state_dict(), 'models/dynamic_lr_2_pipelines_StScaler_pooler_6layers_400epoch.pth')

In [ ]:
# Load model from file
model = CodeDiffNN(code_embedding_dim, repo_input_size, hidden_sizes_pipeline_1,hidden_sizes_pipeline_2, output_size).to(device)
model.load_state_dict(torch.load('models/fixed_model_2_pipelines_400epoch.pth'))

In [20]:
with torch.no_grad():
    # Load best model from previous training cycle
    model.load_state_dict(best_model)
    print(f'Best model accuracy on validation data: {best_accuracy:.4f}')

    model.eval()
    test_loss,test_accuracy,test_outputs,y_test = test_with_data_loader(model=model,loader=test_loader)
    
    print(f'Accuracy on test data: {test_accuracy:.4f}')
    print(test_outputs.shape)

Best model accuracy on validation data: 0.8133
Accuracy on test data: 0.8024
torch.Size([6885, 3])

In [ ]:
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

_, predicted = torch.max(test_outputs.detach().cpu(), 1)  # Get the index of the max log-probability
labels_1d = torch.argmax(y_test, dim=1).cpu() # turn into 1D tensor

# Convert to numpy arrays
y_test_np = labels_1d.numpy()
predicted_np = predicted.numpy()

# Compute confusion matrix
cm = confusion_matrix(y_test_np, predicted_np)
disp = ConfusionMatrixDisplay(confusion_matrix=cm)
disp.plot()
plt.title('Confusion Matrix for Multi-Class Classification')
plt.show()

print(predicted_np)
print(y_test_np)

In [ ]:
import gc
# Free up GPU memory (testing)
print(f"Cached GPU memory before: {torch.cuda.memory_reserved()} bytes")
del model
del best_model
del test_outputs
del y_test
del predicted
del labels_1d
del val_loader, test_loader, train_loader
del cm
gc.collect()
torch.cuda.empty_cache()
print(f"Cached GPU memory after: {torch.cuda.memory_reserved()} bytes")